### ISSUE TITLE
Display favourite stars on home page

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#109]
Only display the yellow star for the user who favourites the profile when we use the search functionanlity;
replicate [condition](https://github.com/FAC-GM/app/blob/b14f1b66a020539935c166ee43cd114b930419a8/lib/home.js#L53-L57) to the [search api](https://github.com/FAC-GM/app/blob/master/lib/search.js)

**Comment by iteles** [comment]
This was closed with PR #110
