### ISSUE TITLE
Highlight search keywords in Candidate pages

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#114]
As a person searching for words I want to see those words highlighted in the text of the candidate profiles so it makes the text easier/faster to scan and I can get the information I need to get on with my work.

<hr/>

We have already implemented this is the _search results page_ ( https://github.com/FAC-GM/app/issues/68),  but this might be a useful feature to persist to the individual candidate pages.

**Comment by iteles** [comment]
Priority to be assigned by Product Owner.

**Comment by SimonLab** [comment]
At the moment the keywords are highlighted on the search page and if then the user click on a candidate the same keywords will be highlighted on the candidate profile.

**Comment by iteles** [comment]
@SimonLab The example I was thinking of was this one:
When I search for Paris, Lisa Sophia Trabert appears with in the search results (first page) with nothing highlighted in the search results.
When I click into her profile, I don't see the highlight either - is this because of the brackets around the word `Paris`?

<img width="1215" alt="screen shot 2015-11-30 at 11 18 23" src="https://cloud.githubusercontent.com/assets/4185328/11470281/4dfd3624-9754-11e5-9dc5-87a0c2e7f6e0.png">

**Comment by SimonLab** [comment]
@iteles thanks for the example. The issue is not the brackets, the summary element doesn't have the class "check-highlight": [L57](https://github.com/FAC-GM/app/blob/5671d9ecffaa2df2c795e90acd8e3a0705897063/views/candidateView.html#L57)

**Comment by SimonLab** [comment]
Resolve with this [PR](https://github.com/FAC-GM/app/pull/117)
