### ISSUE TITLE
Loop on the list of contacts

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#12]
How to get a list of all the contacts? We need to find a way to loop on the list, scan, scroll? By default the number of elements return by a search query with ElasticSearch is 10.

**Comment by nelsonic** [comment]
Search: https://github.com/dwyl/esta#search

**Comment by SimonLab** [comment]
We are at the moment using indeed the search function ([L13](https://github.com/FAC-GM/app/blob/019dc7f5c6b097cddc3fe5a113fec3aa37a64795/lib/home.js#L13)) but from the official package, we will change to esta as it looks much more friendly!
What we are looking now is to iterate on the list of contacts. The idea is to have a button next on the home page which requests the next n contacts from the database. One way to do this is to request the contacts with id between 0-5 then 5-10, 10-15,etc. But unfortunately the ids are not stored as number but as random strings and that's why I am looking for another way to do this.
To conclude I think we need to store our content in Elasticsearch with ids represented as an integer

**Comment by heron2014** [comment]
I think what we are looking for is pagination in elasticsearch https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html

**Comment by SimonLab** [comment]
Looks interesting, did you have a try @heron2014?

**Comment by SimonLab** [comment]
We use ElasticSearch pagination now
