### ISSUE TITLE
Prevent having future duplicates in the app

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#121]
As a user of the app, I don't want to see duplicate content in the application whenever a new version is released that pulls additional data into the app.

At the moment, whenever a candidate is added that is already in the database but has a different URL, the profile appears in duplicate.

**Comment by SimonLab** [comment]
Each candidate has at leas one unique url link to their profile (but they can have more than one which was why we have some duplicates). This url contains a unique username. When we want to update a profile we need:
- Find the url corresponding to a specific profile by searching the username instead of search for the all url
- Update this specific profile

For the current duplicates
- Find the all the urls linked to a profile from a specific username.
- Merge this profiles, there are two ways to do this:
  - We can delete the current profiles and create a new
  - We can keep the profile which has more data than the other one and update this profile

**Comment by nelsonic** [comment]
When the *extension* gets the URL for the Profile page, does it remove any url Parameters?
or does it get it from a field/value *on* the page?

**Comment by SimonLab** [comment]
The application receive the full url linked to a profile. So if this url as some parameters the app will receive them also

**Comment by nelsonic** [comment]
The urls should be unique if we are getting them using:
```js
profile.url = doc.getElementById('relationship-public-profile-link').innerText;
```

**Comment by nelsonic** [comment]
Why would we need to "merge" the profiles? 
Can we not simply remove one of them? or is there data in one that is not in the other?

**Comment by iteles** [comment]
The second profile will have all of the data of the first one _and more_.

**Comment by nelsonic** [comment]
We just need a way of determining which is the profile with more data.

**Comment by iteles** [comment]
**Examples**

<img width="897" alt="duplicate-screenshot" src="https://cloud.githubusercontent.com/assets/4185328/11588834/57ace884-9a7b-11e5-8290-d28397c900db.png">

Profile IDs:
http://global-m.herokuapp.com/candidate/AVCK2mfWEqh9FFCalOm4
<img width="617" alt="screen shot 2015-12-04 at 11 37 52" src="https://cloud.githubusercontent.com/assets/4185328/11588901/d202e39a-9a7b-11e5-88b0-de65dd52395a.png">

http://global-m.herokuapp.com/candidate/AVCK2u_3ol2-ujJIPgjZ/
<img width="667" alt="screen shot 2015-12-04 at 11 38 57" src="https://cloud.githubusercontent.com/assets/4185328/11588886/c0289dfe-9a7b-11e5-90de-6bcfa25d0ebd.png">

**Comment by nelsonic** [comment]
Ok. we can write a `regex` to normalise the url.

**Comment by iteles** [comment]
**Another example:**
<img width="976" alt="screen shot 2015-12-04 at 11 42 02" src="https://cloud.githubusercontent.com/assets/4185328/11588944/52ece41a-9a7c-11e5-9868-3855989febc6.png">

http://global-m.herokuapp.com/candidate/AVCK2u_3ol2-ujJIPgjZ/
<img width="584" alt="screen shot 2015-12-04 at 11 42 50" src="https://cloud.githubusercontent.com/assets/4185328/11588953/648318e8-9a7c-11e5-97fb-5fbe074859b0.png">

http://global-m.herokuapp.com/candidate/AVCLaF0gEqh9FFCalRdb/
<img width="607" alt="screen shot 2015-12-04 at 11 46 32" src="https://cloud.githubusercontent.com/assets/4185328/11589000/cc913b9a-9a7c-11e5-8665-8c2ba4b4587d.png">

**Comment by nelsonic** [comment]
Sorry, clicked on your beautiful face instead of mine while attempting to assign the issue.
I'm working on it. :wink:

**Comment by nelsonic** [comment]
@SimonLab I'm going to need to query the entire ES database to get a list of all the profile urls to *test* the transformer...

**Comment by SimonLab** [comment]
ok, @nelsonic do you want me to write this query? Do you want to save those url in a file or do you want to apply your transformer at the same time you are doing the query?

**Comment by nelsonic** [comment]
Every time a record is saved or updated the url needs to be transformed. see: https://github.com/akitten/linkedin-canonical-url

**Comment by nelsonic** [comment]
@SimonLab we need to write a script that backs up all the data in case of failure. see: https://github.com/FAC-GM/app/issues/57
That script will need to extract all the records and save them somewhere secure.
During that [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load) job we will apply the fix to all the urls.

**Comment by SimonLab** [comment]
![duplicate](https://cloud.githubusercontent.com/assets/6057298/11639911/975b8ba8-9d27-11e5-8786-806d33265fd7.png)

**Comment by nelsonic** [comment]
@iteles + @Adam-JF we need ***acceptance criteria*** for this story so that we *know* when its done. @SimonLab, @heron2014 and I have invested a *considerable* amount of time in this already and we need to know when we can consider it "*done*".

**Comment by nelsonic** [comment]
http://global-m.herokuapp.com/search/all/Alencar/1
![alencar-duplicates-due-to-delayed-index](https://cloud.githubusercontent.com/assets/194400/11658658/a6d613c0-9dbb-11e5-8771-c437c8e04fd7.png)

**Comment by SimonLab** [comment]
From my script:
![duplicatesprofile](https://cloud.githubusercontent.com/assets/6057298/11658769/5c467bd2-9dbc-11e5-9ace-1b173fc784fb.png)

**Comment by iteles** [comment]
I would suggest that at this point it is hard to test this exhaustively. @SimonLab @heron2014 and @nelsonic have done as much as is possible with the _known information_ at this point - i.e. fixes have been implemented for all the _known_ causes of duplicates -  so I propose:
+ We test this manually with 10 profiles, from 2 different GM team member machines, varying in degrees of connection
+ If no duplicates are created, we consider this issue closed
+ Any duplicates that are found in future whilst using the app should be _logged as individual issues_ (including details such as the name and URL of the profile and who's account it was found on) that will need to be investigated and fixed separately

@Adam-JF What are your thoughts on this?

**Comment by Adam-JF** [comment]
Hi @iteles will test this for you on my computer and get another team member to do the same. Will let you know if we get any duplicates.

**Comment by Adam-JF** [comment]
Fixed, great work.
