### ISSUE TITLE
500 Error when clicking on a specific profile after searching for 'judith'

### ISSUE THREAD

**Issue by ahemsley2** [FAC-GM/app#129]
http://global-m.herokuapp.com/candidate/AVFeBJD-NvVvvOw4mkJC/judith

When i click on this link i get the following error:

{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**Comment by iteles** [comment]
This may be linked to #131

**Comment by SimonLab** [comment]
The result of the search contains some profiles where the property connecteTo have some undefined values. Same as [issue 131](https://github.com/FAC-GM/app/issues/131).
Resolved with this [PR](https://github.com/FAC-GM/app/pull/140)
