### ISSUE TITLE
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#130]
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'querySelector' of undefined
    at scrapeNotConnected (chrome-extension://ccgffoipijigdipijolokbjmolfohblm/js/scrapeNotConnected.js:22:73)
    at chrome-extension://ccgffoipijigdipijolokbjmolfohblm/js/background.js:15:19

![screen shot 2015-12-01 at 15 22 21](https://cloud.githubusercontent.com/assets/15364186/11504887/77fd40d6-983f-11e5-885b-2363940d191f.png)

**Comment by heron2014** [comment]
This error appeared because some profiles don't have profile pictures. We need to apply condition to check whether profile has a picture or not.

**Comment by iteles** [comment]
@heron2014 How long did this take to fix?
