### ISSUE TITLE
Search for Paynter returns 500

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#131]
http://global-m.herokuapp.com/search/all/Paynter/1

![screen shot 2015-12-01 at 15 26 37](https://cloud.githubusercontent.com/assets/15364186/11505009/0145d8da-9840-11e5-8c7e-d4fa4de532b5.png)

**Comment by Adam-JF** [comment]
Same for: http://global-m.herokuapp.com/search/all/Bellaiche/1
![screen shot 2015-12-01 at 15 28 18](https://cloud.githubusercontent.com/assets/15364186/11505032/2ea308e8-9840-11e5-99cb-b1ceea3fa85b.png)

**Comment by SimonLab** [comment]
error on the server
![errorpaynter](https://cloud.githubusercontent.com/assets/6057298/11505159/e353b4ae-9840-11e5-9515-3cba9887d790.png)

**Comment by nelsonic** [comment]
@SimonLab is this error screenshot from the code running on your local or Heroku error log?

**Comment by SimonLab** [comment]
@nelsonic It's on my localhost

**Comment by SimonLab** [comment]
Some values of the property connected to are not valid and the [helper](https://github.com/FAC-GM/app/blob/f1bef38f1cbb2daf4b3d7da2c8c82c8d61c871d8/views/helpers/initials_of_connected_users.js#L17) is not able to parse them

**Comment by SimonLab** [comment]
resolved with this [PR](https://github.com/FAC-GM/app/pull/140)
