### ISSUE TITLE
ES6 on front-end

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#135]
As a user I want the application to work on every browser version.
So we don't want to use ES6 on front-end:
- [main.js L12](https://github.com/FAC-GM/app/blob/master/assets/js/main.js#L12)
- [main.js L35](https://github.com/FAC-GM/app/blob/master/assets/js/main.js#L35)

**Comment by iteles** [comment]
**Note:** As per [this comment from @nelsonic]( https://github.com/FAC-GM/app/pull/137#discussion_r46321024), we'll need to test this on Nathan's computer specifically before we can close this issue.

**Comment by iteles** [comment]
Tested on Nathan's computer and search went back to functioning :+1:

**Comment by nelsonic** [comment]
We should use [***es6 everywhere***](http://kangax.github.io/compat-table/es6/) and then wear cowboy hats when we're doing demos. :open_mouth:

**Comment by iteles** [comment]
:yum:
