### ISSUE TITLE
Adding a simple emailing function from the app

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#138]
As a person using the app, I want to be able to send an _email_ **from my email address** to the candidate _from their profile page_ so that I don't have to click back and forward between the app and my email.

<hr/>

As requested by @ahemsley2 earlier today. This is the MVP of a more advanced feature set that allows users to have template emails and mass mailing features - it was agreed these are a lower priority.

**Comment by iteles** [comment]
Two simple fields in the first instance:
<img width="547" alt="form-for-sending-simple-message" src="https://cloud.githubusercontent.com/assets/4185328/11512002/0837ca76-9864-11e5-9c71-42c41a347ee6.png">

**Comment by Adam-JF** [comment]
This idea will be iterated upon on further down the line.
