### ISSUE TITLE
Get connected user to the profile

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#139]
If the connectedTo doesn't exist on profile pass the empty array [L27](https://github.com/FAC-GM/app/blob/f1bef38f1cbb2daf4b3d7da2c8c82c8d61c871d8/lib/api.js#L27)
![connectedto](https://cloud.githubusercontent.com/assets/6057298/11529870/c9777d52-98e7-11e5-8024-94d13afacba4.png)

**Comment by SimonLab** [comment]
resolved with this [PR](https://github.com/FAC-GM/app/pull/140)
