### ISSUE TITLE
profile with an undefined url

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#141]
If the url of a profile is not defined the database won't be able to save the profile.
see [L18](https://github.com/FAC-GM/app/blob/f1bef38f1cbb2daf4b3d7da2c8c82c8d61c871d8/lib/api.js#L18)

**Comment by nelsonic** [comment]
Merged. we need to re-test this on a GM machine tomorrow.

**Comment by heron2014** [comment]
We are saving the profile with undefined url
 
[L67-L78](https://github.com/FAC-GM/app/blob/master/lib/api.js#L67-L78) this is why we have duplicates profile. 

Question: 
Should we don't save profile with undefined url ?

Related [issue 121](https://github.com/FAC-GM/app/issues/121)

**Comment by iteles** [comment]
We couldn't find a profile to replicate this - we'll need to review this issue as soon as we find an example. 

My vote would be to keep the profile if we can.

**Comment by heron2014** [comment]
Resolved by #142
