### ISSUE TITLE
Search should not include initials of who candidate is connected to in results

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#144]
As a user of the app, when I search for a name, I want to see only people with that name and not people who are connected to team members with that name.
<hr/>

In the screenshot below, `Svitlana Onish` appears when I search for 'Waller'. She does not have the term `Waller` anywhere in her profile but _does_ have the initials 'NW' (where the 'W' stands for Waller) attached to her profile.
<img width="873" alt="screen shot 2015-12-03 at 11 33 21" src="https://cloud.githubusercontent.com/assets/4185328/11559723/05b34172-99b3-11e5-84a3-8821406366ef.png">

**Comment by nelsonic** [comment]
Search query should exclude `connectedTo` field by default...

**Comment by Adam-JF** [comment]
This has been fixed.

**Comment by nelsonic** [comment]
Thanks for confirming fixed. :+1:
