### ISSUE TITLE
Initials don't show on the candidate page

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#145]
initials who is connected to who are not defined [L26-L30](https://github.com/FAC-GM/app/blob/511e58e9a448d02d3f5add1edc189d1d7e46e0ac/views/candidateView.html#L26-L30)

**Comment by SimonLab** [comment]
resolve with this [PR](https://github.com/FAC-GM/app/pull/146)

**Comment by iteles** [comment]
This needs to be tested with our Product Owner.

**Comment by Adam-JF** [comment]
Fixed.
