### ISSUE TITLE
Search results with empty profiles

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#147]
As a user I don't want to get empty profiles in the results of the search as it doesn't add information to my search
![emptysearch](https://cloud.githubusercontent.com/assets/6057298/11561700/f28e877e-99c0-11e5-98d4-2621407b7f65.png)

**Comment by SimonLab** [comment]
A simple way to do this: see [PR](https://github.com/FAC-GM/app/pull/148).

**Comment by nelsonic** [comment]
@SimonLab is this live on the site now?
