### ISSUE TITLE
Pagination | Varying number of result entries on each page

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#149]
A search for 'Nick' yields
+ Page 1: full page, 10 people
+ Page 2: 2 people
<img width="1266" alt="page2-search-for-nick" src="https://cloud.githubusercontent.com/assets/4185328/11588738/a53385c8-9a7a-11e5-9b84-51e378ee548b.png">
+ Page 3: 0 people

<img width="437" alt="page3-search-for-nick" src="https://cloud.githubusercontent.com/assets/4185328/11588765/e34d7fbc-9a7a-11e5-9f1e-208600e91b50.png">
+ Page 4: 0 people
+ Page 5: full page, 10 people

**Comment by nelsonic** [comment]
Blanks... @SimonLab this is related to: #151

**Comment by iteles** [comment]
Ah right, because the blanks have been removed from the search results in https://github.com/FAC-GM/app/issues/147 but maybe their position is still there in the searches.

**Comment by nelsonic** [comment]
Precisely. Our script needs to `delete` them from the database *completely*!

**Comment by SimonLab** [comment]
This issue shouldn't appear anymore as the database is up to date

**Comment by Adam-JF** [comment]
Fixed.
