### ISSUE TITLE
Should we get an iMac with the *exact* spec of one of the GM units for our testing?

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#150]
We could order one from [ebay](http://www.ebay.co.uk/sch/i.html?_from=R40&_trksid=p2050601.m570.l1311.R6.TR11.TRC1.A0.H1.Ximac.TRS0&_nkw=imac+24&_sacat=0) and keep it in our office for dev/testing purposes... thoughts?

**Comment by iteles** [comment]
I think this isn't a sustainable solution and it would be more advantageous (though more painful) to us in the long run to trial and find the best process of working with GM on their machines. We can then document and replicate for the future, discussing that as part of our way of working.

**Comment by iteles** [comment]
We have now also resolved this issue by ensuring that we work closely with @Adam-JF to test on GM machines whenever possible.
