### ISSUE TITLE
Empty profiles

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#151]
Profiles like this following example: 

![empty](https://cloud.githubusercontent.com/assets/8476884/11593320/8496fffe-9a9b-11e5-86d5-364c2de2835e.png)

[Example](https://global-m.herokuapp.com/candidate/AVCMlLe1Eqh9FFCalSyP)

Clean empty profile from database.

**Comment by SimonLab** [comment]
One solution is to create a separate script to target these values and to delete them.

**Comment by nelsonic** [comment]
@heron2014 please include the link to the content when creating an issue so others can help investigate.
@SimonLab we can write an ETL script for this.
Have a great weekend guys! :+1:

**Comment by SimonLab** [comment]
The database has been cleaned up. Does it need to be validated by the PO?

**Comment by nelsonic** [comment]
Yes. we should *assign* it to @Adam-JF  for review.

**Comment by Adam-JF** [comment]
Fixed.
