### ISSUE TITLE
Avoid update existing direct profile

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#152]
If a user is not directly connected to a profile we don't want to update the information of this profile in the app as we would be overwriting the profile with _less_ information than is currently available.

**Comment by SimonLab** [comment]
Need to be tested with PO

**Comment by iteles** [comment]
Tested internally between myelf and @heron2014. Works on our end :+1:

**Comment by nelsonic** [comment]
@iteles *ideally* this should be closed by **PO**...

**Comment by iteles** [comment]
Of course! It's on the list to be tested with our PO tomorrow morning as @heron2014 and I discussed, which is why I haven't closed it myself. The above comment was to document that we've finalised our internal testing and are ready for PO testing as @SimonLab mentioned :+1:

**Comment by iteles** [comment]
Example of a 1st degree connection to NW: `Jane Sibthorpe`

We need to test that someone who is a 2nd degree connection to her does not overwrite the existing information.

**Comment by Adam-JF** [comment]
Works beautifully.
