### ISSUE TITLE
timestamp on create/update

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#154]
as a user I want to know when a profile has been updated or created

**Comment by SimonLab** [comment]
see the [elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html)

**Comment by SimonLab** [comment]
The timestamp functionality has been implemented with this [PR](https://github.com/FAC-GM/app/pull/155)

**Comment by nelsonic** [comment]
Thanks for fixing this :+1:
