### ISSUE TITLE
Extract Style from Main Website to Re-Use in App

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#159]
As a person using the app I would like the ***look and feel*** to be similar to the Website so that I don't have multiple interfaces.

http://global-m.co.uk/
![global-m-home-page](https://cloud.githubusercontent.com/assets/194400/11654651/516d9e7e-9d9f-11e5-97d4-734881652e6c.png)

**Comment by heron2014** [comment]
Resolved by the new design.
