### ISSUE TITLE
Re-designing the home page + login page

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#164]
Re-designing the home page + login page according to PO wireframes.

**Comment by iteles** [comment]
As discussed in our sprint 4 planning meeting this morning, we'll need to review the designs as a team first #170, so this time estimate may need re-evaluation for our next sprint :blush:

**Comment by heron2014** [comment]
Clear @iteles :smile:

**Comment by heron2014** [comment]
This has been resolved by new design.
