### ISSUE TITLE
Constructing HTML form and UI for 4 field search

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#167]
Linked to #134.

Constructing the HTML form and UI for the four individual search fields:
+ Skill 
+ Location
+ Job title
+ Name

**Comment by SimonLab** [comment]
Have we defined a display order for these fields? skill - location - Job Title - Name?

**Comment by iteles** [comment]
@Adam-JF My thoughts are that we should place the most used search fields to the left.

Location | Skills | Job Title | Name

What are your thoughts on this?

**Comment by heron2014** [comment]
At the end of today we accomplished following: 
- we added 3 fields : job, name, location 

![search4](https://cloud.githubusercontent.com/assets/8476884/11723230/2b7242fc-9f65-11e5-9e55-093bd5ba49e0.png)

Query is working on the name and the location at this point.

**Comment by Adam-JF** [comment]
Works great.
