### ISSUE TITLE
Notes for Candidates

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#168]
As a person searching for potential technical candidates, I want to attach notes to a prospective candidate so can keep track of what conversation I have had with the person or any other information.

Notes should be *viewable* by anyone on the team.

**Comment by iteles** [comment]
@Adam-JF This is our proposal for the Notes section, combining a drop-down with the various possible statuses (submitted to, phone interview, second interview, etc) with a free form text field for further notes.

They will be displayed in the NOTES box below the simple form in reverse chronological order (newest at the top).

<img width="612" alt="screen shot 2015-12-15 at 09 45 10" src="https://cloud.githubusercontent.com/assets/4185328/11807282/bb11bee8-a310-11e5-866b-3101bb12021a.png">

_**Could you please let us know what the required statuses are in the drop-down**_ and your thoughts on this proposal? We'd like to make the feature as immediately useful as possible.

**Comment by Adam-JF** [comment]
Stages:
1) Submitted
2) Phone Screen
3) Interview
4) Placement

**Comment by iteles** [comment]
:+1: Thanks @Adam-JF, we'll make a start on this.

**Comment by SimonLab** [comment]
As we have update the properties of the user connected, to have the best experience using this featues, the users will need to reconnect to the app!

**Comment by iteles** [comment]
Do you mean log in again @simonLab?

**Comment by SimonLab** [comment]
yes login again. (we might need to delete the cookie to force the login)

**Comment by iteles** [comment]
@SimonLab That was my next question :)

**Comment by SimonLab** [comment]
@iteles I just check just by just closing chrome and it works for me (redirect to login page). It might be a solution but it will be great if you can check it also.

**Comment by iteles** [comment]
:+1: YES! I just quit Chrome and it asked me to log in again. Simple solutions are my favourite.

**Comment by SimonLab** [comment]
We just need to be sure that it works also with Safari (and Firefox).

**Comment by iteles** [comment]
:+1: We'll ask @Adam-JF to get the team to test the ones they use.

**Comment by Adam-JF** [comment]
Works well.
