### ISSUE TITLE
Sprint 4 length?

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#171]
Within the team, @heron2014 and @SimonLab are available to work until 18th December. @iteles and @nelsonic are unavailable on 17th December and available remotely on 18th December due to pre-existing commitments.

In our sprint planning meeting this morning we discussed two possibilities for sprint 4 durations:
+ 5 days, with demo on 16th December
+ 7 days, with demo on 18th December

@heron2014 @SimonLab Could you please make a note here of your thoughts on which option you think is best for you?

**Comment by SimonLab** [comment]
@iteles I think it will be better to have the demo on the 16th as everyone can be here if any question are raised during the demo.

**Comment by heron2014** [comment]
@iteles I think we are working on mini sprint - which is 5 days. Hopefully we will fit in to do demo on 16th December.

**Comment by iteles** [comment]
:+1: Thanks for your thoughts, 5 days it is.
