### ISSUE TITLE
Validate database property on server side?

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#173]
we are checking that some properties of the database exist on the server side, for example:
[home L54](https://github.com/FAC-GM/app/blob/66c116c11fa0d9e62c09e4df774777a1baae440b/lib/home.js#L54).
Do we need to ensure that the database has all the properties required (the value can be empty if needed: 0, empty string, null, undefined?) instead of doing the check on the server side?

**Comment by heron2014** [comment]
Resolved in [define-properties](https://github.com/FAC-GM/helpers/blob/helpers/define-properties.js)

**Comment by heron2014** [comment]
As comment above, resolved.
