### ISSUE TITLE
Search on job

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#177]
As a user I want to be able to search in the application by the job title as I want to have more precise results in my search.
<hr/>
50% done as we have update the database to enable this search, see [issue 3 on helpers](https://github.com/FAC-GM/helpers/issues/3)

**Comment by iteles** [comment]
As agreed this morning, we the 'Job title' search will mimic LI's 'Title' search and search the 'Headline' for the job title.

<img width="431" alt="highlighting-the-headline" src="https://cloud.githubusercontent.com/assets/4185328/11781382/6953880c-a261-11e5-88d1-3be0d1f813d0.png">

**Comment by SimonLab** [comment]
This feature has been implemented with this [PR](https://github.com/FAC-GM/app/pull/181).
@Adam-JF Could you test it and give us your feedback on this functionality? Thanks

**Comment by Adam-JF** [comment]
Good to go.
