### ISSUE TITLE
search on skills

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#178]
As a user I want to search for particular skills as I want to filter the searches.

**Comment by SimonLab** [comment]
The [skill search](https://github.com/FAC-GM/app/blob/dccb26388acb69a1914b5fec874105eda5b52d6b/lib/query.js#L58-L61) seems to work on the real database however we have some problem to pass some test with the fixtures.
We are at 99% on this feature, it might be just a mistake on how we are using our fixtures. We need to check again if the typre of our local fixture is right and if there is no syntax mistake in our query.

**Comment by nelsonic** [comment]
@SimonLab let me know if you need another pair of eyes on this tomorrow morning.

**Comment by SimonLab** [comment]
My fixtures database define the skills property as a [nested object](https://github.com/FAC-GM/app/blob/996d61df840f4517c564f29f43f737fd977024ba/test/fixtures/initialize.js#L11) instead of a normal object. That's why my request with skills failed.

**Comment by iteles** [comment]
@SimonLab Good find :+1:
