### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#18]
Need to encode special characters on search

**Comment by nelsonic** [comment]
:+1:

**Comment by SimonLab** [comment]
see : [-query-string-query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)

and 

Reserved charactersedit

If you need to use any of the characters which function as operators in your query itself (and not as operators), then you should escape them with a leading backslash. For instance, to search for (1+1)=2, you would need to write your query as \(1\+1\)\=2.
The reserved characters are: + - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ /
Failing to escape these special characters correctly could lead to a syntax error which prevents your query from running.

**Comment by iteles** [comment]
@SimonLab Was this fixed with PR https://github.com/FAC-GM/app/pull/32 along with #28?

**Comment by iteles** [comment]
No, still outstanding.

https://uk.linkedin.com/in/ivo-costa-92bb958 - example of `/` in skills: `PL/SQL`

**Comment by Adam-JF** [comment]
#193
