### ISSUE TITLE
Search for fullname with special language character fails

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#182]
Our search fails when we are querying Ines, because Ines is written with special language character: 

Example:
<img width="431" alt="highlighting-the-headline" src="https://cloud.githubusercontent.com/assets/4185328/11781382/6953880c-a261-11e5-88d1-3be0d1f813d0.png"> 

Solution: 
We can apply custom analyzers by combining token filters , eg. the **ascii_folding filter** removes diacritics, converting a term like "très" into "tres" . 

**Reference, page 135 Elasticsearch** and also [analysis-asciifolding-tokenfilter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html)

**Comment by iteles** [comment]
@heron2014 To clarify, do you mean that it ignores them in the search or actually removes them from the data (which not be ideal).

**Comment by heron2014** [comment]
@iteles analyzer doesn't removes it, it just transform the word into searchable term.

**Comment by iteles** [comment]
:+1: Thanks for clarifying :blush:

**Comment by SimonLab** [comment]
Just to clarify again. If we are looking with "Ines", the result of the search will be empty. If we are looking for "Inês" we will have a result. The data is still in the database and will stay in the database!

**Comment by Adam-JF** [comment]
Don't feel name search is used enough to make this a high priority.
