### ISSUE TITLE
As a user I can access the results of a search on the next and previous page

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#189]
The link to the next and the previous page is broken as the skills parameter is [not defined](https://github.com/FAC-GM/app/blob/a4b020a63d459e2656e458d97600bf7113041e6f/lib/query.js#L120-L126)

**Comment by iteles** [comment]
If we want Adam to test this, we need to re-phrase the issue as a user story and remove the `technical` label.

**Comment by SimonLab** [comment]
As a user I can access the results of a search on the next and previous page.

**Comment by Adam-JF** [comment]
Works well.
