### ISSUE TITLE
Skills search for special characters

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#193]
When searching for people with C++ skills, the search does not always match with relevant candidates.
More often than not it will match with people with C# skills - C++ also isn't highlighted inside the candidate profiles.

**Comment by heron2014** [comment]
We need to escape special/reserved characters to be able to search on these keywords 
Reference to list of special characters  [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters)

**Comment by SimonLab** [comment]
link/duplicate to [issue 18](https://github.com/FAC-GM/app/issues/18)

**Comment by SimonLab** [comment]
So we need to escape the list of special charaters in our query with '\'. We can loop.forEach or use a regex. We are now testing these solutions.

**Comment by SimonLab** [comment]
The relevance for these **short** terms (c, c++, c#) are difficult to distinguished in elasticsearch.
Relevance is calculated from:
- Term frequency: How often does the term appear in the field? The more often, the more relevant
- **Inverse document frequency**: How often does each term appear in other documents? The more often, the less relevant. I think this is why the relevance is difficult to calculate as c, c++ c# are very common terms and can be contained in a lot of words
- Field-length norm: How long is the field? The longer it is, the less likely it is that words in the field
will be relevant

**Comment by SimonLab** [comment]
The characters are now escaped and they should be highlighted in the search.

**Comment by iteles** [comment]
Tested on the phone with @Adam-JF earlier today. The second result for a search on `c++` yielded a candidate, [Markus Tastler](http://global-m.herokuapp.com/candidate/AVCK-ihqEqh9FFCalPQw/%20%20%20c%5C%2B%5C%2B) who doesn't have `C++` as part of his skills. 
<img width="1081" alt="screen shot 2015-12-18 at 11 18 42" src="https://cloud.githubusercontent.com/assets/4185328/11895809/684f5574-a579-11e5-9d1f-08fdae2f5f9f.png">

**Comment by SimonLab** [comment]
Instead of a simple query we need to try a query filter ,something like:
```
filtered:{
  match: {} //other criterias, location, headline, name
  filter: {skill: skills} //list of skill
}
```
which will filter on skills

**Comment by SimonLab** [comment]
I tried:
```
                query: {
                  filtered: {
                     filter: {
                       bool:{
                         must: mustClause
                       }
                     }
                   }
                },
```
This works with javascript skill for example but if we search for c++ the list of results is empty. So it might still be a proble with ++. Still looking how to improve the query

**Comment by SimonLab** [comment]
At the moment the field for sill is analysed before being indexed. This means that c++ might be converted to just c

**Comment by SimonLab** [comment]
If we define the skill name to not be analyzed, then the term query will be case sensitive which will limit too much the list of results

**Comment by SimonLab** [comment]
Defining a proper analyser to keep the values in lower case: http://stackoverflow.com/questions/15079064/how-to-setup-a-tokenizer-in-elasticsearch

**Comment by SimonLab** [comment]
c++ is tokenized to c
![analyzer](https://cloud.githubusercontent.com/assets/6057298/11903979/ff4d8078-a5b4-11e5-92f6-b4a4b5328425.png)

**Comment by SimonLab** [comment]
The current solution: reindex to define a simple tokenizer for the skill like in http://stackoverflow.com/questions/15079064/how-to-setup-a-tokenizer-in-elasticsearch

**Comment by heron2014** [comment]
@SimonLab just to clarify on this issue: 

When we use mapping on field: skill into type: string  we  transformed our field from full-text field into exact value which in this case our result is  'c  ' ++ is transformed in 2 empty spaces, this is why we need to escape special characters, so they won't be empty spaces, right?

**Comment by SimonLab** [comment]
I'm using a specific tokenizer in the [helper](https://github.com/FAC-GM/helpers/blob/1569b2a2972096647656133e09626ad2327b191b/copy-to-localhost.js#L9-L38).

When we index a document elasticsearch create a set of token for each value (c++ become c, node.js become node and js...). This tokens allow the user to get better result when they search for a value. But in the case of skills we don't want the value to be tokenize but to be the same. My first solution was to not  analyze (and not tokenize) the values but if we do this the value will be case sensitive which means C++ won't match c++. So I created a specific tokenizer which keep the value but in lower case. That's why now when a user do a search we [need to lower case](https://github.com/FAC-GM/app/blob/e4e074a2c9934fb8832d7fd987e70f6ce47fe7d6/lib/query.js#L35) the search before trying to match the value in the elasticsaerch documents.

This is a quick explanation and maybe not very clear but I will write a better one in a md file.

**Comment by heron2014** [comment]
thanks @SimonLab , is clear now I just haven't seen that you applied tokenizer anywhere, but now all makes sense by seeing it in helpers! :)

**Comment by Adam-JF** [comment]
Fixed.
