### ISSUE TITLE
Mass update candidate connections

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#194]
Would be good to update everyones lists - re-download .csv files for each team member and re-upload them to the app having removed duplicates etc.

**Comment by Adam-JF** [comment]
It has been agreed that the vCard format would be easier to use for the sake of the update.
I have submitted 8/9 vCards from Global {M} team.

The user story for this issue is accurate.

**Comment by iteles** [comment]
We now have over 123,000 profiles in the app (we started with around 50,000).

Are you happy to close this issue for now @Adam-JF ?

**Comment by Adam-JF** [comment]
Great job guys.
