### ISSUE TITLE
Highlight special character

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#201]
if a search contains a special character for a regular expression ([-[\]{}()*+?.,\\^$) the highlighting won't work. [The PR on search-result-keyword-highlighte](https://github.com/dwyl/search-result-keyword-highlighter/pull/16). Should resolved this problem. So as soon as this PR is accepted we can update the dependencies of our app and everything should be ok.

**Comment by Adam-JF** [comment]
Works well.
