### ISSUE TITLE
Month on notes displays wrong number

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#202]
![date](https://cloud.githubusercontent.com/assets/8476884/12090022/cd4043aa-b2e2-11e5-911d-fd7aac3edbf0.png)

Instead of 11 should be 12

**Comment by SimonLab** [comment]
The [getMonth](https://github.com/FAC-GM/app/blob/e4e074a2c9934fb8832d7fd987e70f6ce47fe7d6/lib/notes.js#L30) return s a value between 0 and 11 so we need to add +1 to this value

**Comment by SimonLab** [comment]
resolve with https://github.com/FAC-GM/app/pull/203

**Comment by Adam-JF** [comment]
Good to go.
