### ISSUE TITLE
Add status 'label' to profiles

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#204]
As a user of the app, I want to be able to see at a glance what the candidate's status is, by displaying this near the top of the profile so that I don't have to spent time searching through the notes.

**Comment by iteles** [comment]
Note: This will require some UI work.

**Comment by heron2014** [comment]
This is how we currently display status-label on candidate page: 

![candidate-view-status](https://cloud.githubusercontent.com/assets/8476884/12455717/973a9a3a-bf94-11e5-9bb0-4f05cba97841.png)

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

**Comment by Adam-JF** [comment]
Works well.
