### ISSUE TITLE
Add a 'match score' to search results

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#206]
As a user of the app, I would like to see how good of a match a particular candidate is to my exact search terms so that I don't have to click into each candidate to determine their relevance.

[Update] I added the Wireframe Adam gave us:
![wireframe](https://cloud.githubusercontent.com/assets/8476884/12586241/695a7a4c-c447-11e5-9f58-8885e7f79bed.png)

**Comment by iteles** [comment]
Each field is treated as a full query, so if you search for multiple skills the app searches whether ALL of them exist in a profile - therefore the simple match score will reflect this: whether _all_ or _none_ of them appear in the profile (doesn't deal with individual values separated by commas).

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

**Comment by heron2014** [comment]
Related docs:
- [Theory Behind Relevance Scoring](https://www.elastic.co/guide/en/elasticsearch/guide/master/scoring-theory.html)
- [What Is Relevance?](https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html)

**Comment by heron2014** [comment]
## Explanation how the scoring function works in ES.

ES uses [Boolean Model](https://www.elastic.co/guide/en/elasticsearch/guide/master/scoring-theory.html#boolean-model), [Term Frequency/Inverse Document Frequency (TF/IDF)](https://www.elastic.co/guide/en/elasticsearch/guide/master/scoring-theory.html#tfidf) and [Vector Space Model](https://www.elastic.co/guide/en/elasticsearch/guide/master/scoring-theory.html#vector-space-model) to calculate score.

### Example:

Imagine we have a **bool query** as following:

```
GET /_search
{
  "query": {
    "bool": {
      "should": [
        { "term": { "text": "quick" }},
        { "term": { "text": "brown" }},
        { "term": { "text": "fox"   }}
      ]
    }
  }
}
```
We can calculate score in two ways : with [query coordination]((https://www.elastic.co/guide/en/elasticsearch/guide/master/practical-scoring-function.html#coord) or without. 

We query for ```quick brown fox``` , the weight for each term is 1.5: 

- without query coordination: 

 - document with ```fox``` - score 1.5 
 - document with ```quick fox``` - score 3
 - document with ```quick brown fox``` - score 4.5

- with the query coordination: 

 **Query Coordination factor** multiplies the score by the number of matching terms in the document, and divides it by the total number of terms in the query

 - document with ```fox``` -score 1.5 * 1 / 3 = 0.5
 - document with ```quick fox``` - score 3.0 * 2 / 3 = 2.0 
 - document with ```quick brown fox``` - score 4.5 * 3 / 3 = 4.5 

The **bool query** uses query coordination by default for all should clauses,

**Comment by heron2014** [comment]
### Questions: 
- can we extract these query coordination scores to reuse ?

**Comment by heron2014** [comment]
## Investigations of solutions:
1. For example when we query for : location: London, Skills: Javascript, Node.js we get following results (data from our fixtures)

- score 0.918523 (candidate id - 1)
- score 0.21961421 (candidate id - AVJkGTPTCOYPeyyVcz_3)
- score 0.05080434 (candidate id - 6)
- score 0.05080434 (candidate id - 51)
- score 0.028677149 (candidate id - AVJkGTOLCOYPeyyVcz_2)
and so on..

## Questions: 
Can we rely on score system to create human readable match score system, e.g;
- range of scores  - would corresponds to 25%, 50%, 75%, 100%.

**Comment by iteles** [comment]
Agreed, we need to investigate what _affects_ the score to see if it's realistic to use this score or not.

**Comment by SimonLab** [comment]
http://stackoverflow.com/questions/3986220/how-do-i-normalise-a-solr-lucene-score
![normalizescore](https://cloud.githubusercontent.com/assets/6057298/12550723/82f67aea-c35d-11e5-823c-0987808d3d39.png)

Let's try to find out why we shouldn't normalized scores

**Comment by SimonLab** [comment]
Instead of using the score relevance I try to find out if we can count the number of terms find in a result. We have currently only 5 searched terms (job title, name, location, company and skills). If a list of skills is searched then all the results contain the skills. So our problem is to try to find out how well the other fields match the document. For example if we are searching for the company "Fouders and Coders" the list of results will contain (the order is not important):
- Founders and coders, a perfect match
- Founders coder, the and is missing
- Founder
- and coders
- coders
-and, not a very interesting match but still a match. ES know that and is a very common word so the relevance score will be low. But for now we can consider that "just and" is 1/3 of a match

So the question is to know the words match percentage for each multi tesxt field

**Comment by SimonLab** [comment]
One basic (surely not optimal) solution is once we have the results of a search  to count for each field search (ie if the fiels is not empty) the number of terms of the query (the skill field doesn't matter as is act as a filter to our query). This number is 100%
for  example:
location: london United Kingdom - 3 terms
company: Founders and coders - 3 terms



Now if a result has a location "London" and the company "Coders" the match score is 2 terms so 2 out of 6, which is 33%

Notice that if all the field only contain one word each the score will be 100% for all the documents because the request will find at least one word, the search is then just a filter query

One feature will be to be able to search for multiple terms but considering as just one term, like the double quotes on google. However for that we need to work on a language query to analyze the search.

**Comment by SimonLab** [comment]
Let's try to implement this solution:
- Find out which fields are not empty
- For these fields count the number of words (words.split(' ').length ?, find if there is a word function)
- Add the number of words from each non empty fields

- For each result.
  - count the number of matching word (for each word then indexOf !== -1)
Create a percentage from the number of word found and the total number
return this number to the view and create a nice camembert (how to do this css and html only?)

**Comment by SimonLab** [comment]
- [x] Find out which fields are not empty
- [x] For these fields count the number of words (words.split(' ').length ?, find if there is a word function)
- [x] Add the number of words from each non empty fields
- [ ] count the number of matching word (for each word then indexOf !== -1)

Careful with the case. We need to compare the search with the value as case insensitive.

**Comment by SimonLab** [comment]
The location has often commas: London, United Kingdom. So trying to match london with London, will fail. We need to delete the comma at the end of the words location.

link on how to make pie chart: https://www.smashingmagazine.com/2015/07/designing-simple-pie-charts-with-css/

**Comment by SimonLab** [comment]
- [x] count the number of matching word (for each word then indexOf !== -1)
- [x] Create a percentage from the number of word found and the total number
- [x] return this number to the view
- [ ]and create a nice pie chart

**Comment by heron2014** [comment]
Current pie chart: 
- 100% match 

![100](https://cloud.githubusercontent.com/assets/8476884/12583488/f23e232a-c43a-11e5-8955-47c5eedf7e90.png)

- 50% match 

![50](https://cloud.githubusercontent.com/assets/8476884/12583493/fd05f378-c43a-11e5-907f-7bff0bd805e4.png)

I followed steps in this article:  https://www.smashingmagazine.com/2015/07/designing-simple-pie-charts-with-css/ for SVG pie chart

**Comment by heron2014** [comment]
New suggestions of the match-score pie-chart:
- 60% match: 

![60](https://cloud.githubusercontent.com/assets/8476884/12594758/9bb1236a-c46f-11e5-8c3e-ae54c23b5e38.png)

**Comment by iteles** [comment]
@heron2014 Love that mouse over effect!

Is there a reason we can't take the match score out of the box and display it next to the search results, similarly to Adam's design?

**Comment by heron2014** [comment]
Example:

![hacky](https://cloud.githubusercontent.com/assets/8476884/12596171/98413ff6-c476-11e5-9b2a-efc3dca496d8.png)

Although I would probably recommend to redesign this page according to product owner wireframe, because this above solution isn't the most efficient and would need some correction with the new design. What do you think?

**Comment by nelsonic** [comment]
@heron2014 looking good. :+1:

**Comment by heron2014** [comment]
Restructure the home page to fit pie chart outside the candidate view box.

**Comment by heron2014** [comment]
Current view for match score:
![match-score](https://cloud.githubusercontent.com/assets/8476884/12614274/c68c82c8-c4f6-11e5-8be3-742c31719e10.png)

**Comment by Adam-JF** [comment]
@heron2014 That looks great ^^

**Comment by heron2014** [comment]
Short note how the match-score works:
- all the searchable fields (job title, name, location, company, skills) are connected between each other as "AND", which means, that if you search for example for : 

Developer as job title 'AND' Anita as name 'AND' London as location 'AND' Founders as company 'AND' CSS 'AND' Javascript as skills -  search results would only show the candidate with these keywords - meaning the match score should be 100%, if any candidate with these query exists in database.

Example: 
![100-score](https://cloud.githubusercontent.com/assets/8476884/12643306/4565f266-c5b3-11e5-8b3d-87aa6359fdd2.png)



- if you search for multiple words in one field, the match score is more relevant, for example:
Developer IOS as job title, Anita Czapla as name, Founders and Coders as company, London UK as location, CSS, Javascript, Python as skills - search result will be as follow: 

### Important note:

For multiple words in fields:  job title, name, location, company - search works as 'OR' which means that our search result from above query will be : 

Developer 'OR' IOS, Anita 'OR' Czapla, Founders 'OR' and 'OR' Coders (these fields are separated by space) but skills field are treated as 'AND' - CSS 'AND' Javascript 'AND' Python (skills field - keywords are separated by comma)
Match score will show candidates with the highest score if the query is most met.
 
For the following example I took my name off - to get more results.

![multiple-words-score](https://cloud.githubusercontent.com/assets/8476884/12643317/4e6cf4fe-c5b3-11e5-88d0-437a8eace948.png)


@Adam-JF I hope this explanation is clear, please do give us feedback after testing this feature.

**Comment by Adam-JF** [comment]
Currently testing with team.

**Comment by Adam-JF** [comment]
Works great.

Will look to increase complexity with further sprints when we begin to input more information into the app.
