### ISSUE TITLE
Adding status label to search results

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#207]
As a user of the app, I want to see the status of the candidate (i.e. 'Submitted', 'Phone interview' etc) in the search results so that I can immediately see the status without having to click into each individual candidate.

**Comment by SimonLab** [comment]
The current status are:
- Submitted to
- Phone screen at
- Interview at
- Placement at

@Adam-JF What do you think is the best way to display this information on a profile in the search page?

**Comment by heron2014** [comment]
![status](https://cloud.githubusercontent.com/assets/8476884/12449871/112f4dbc-bf78-11e5-811c-e5a8ba418bd2.png)

This is how currently we display status on main page.

@Adam-JF please feel free to comment your vision how to display status.

**Comment by iteles** [comment]
@Adam-JF didn't have a chance to comment on this issue before we started working on it, but he also mentioned that we needed to add this information to the top of the candidate page to make the status immediately clear.

**Comment by SimonLab** [comment]
@iteles do you refer to this [user story](https://github.com/FAC-GM/app/issues/204)?

**Comment by iteles** [comment]
@SimonLab EXACTLY. Good find! :raised_hands:

**Comment by Adam-JF** [comment]
I like the status proposal submitted by @heron2014 It's very clear like that.

**Comment by Adam-JF** [comment]
Works well, good to go.
