### ISSUE TITLE
Search Capabilities

### ISSUE THREAD

**Issue by jrans** [FAC-GM/app#21]
How hard would it be to implement a search that takes more than one skill and narrows down the result, ie I'm looking for a developer who strictly knows redis AND node AND hapi?

**Comment by nelsonic** [comment]
Good question. Did you *try* a sample query?

**Comment by SimonLab** [comment]
@jrans the search is using a OR at the moment (redis OR node OR hapi)

**Comment by iteles** [comment]
Rephrasing as a user story for confirmation with Product Owner, @nwallerGlobalM:   
As a user, I would like to ensure that _all_ of the search terms I enter appear in the results given so that I can run more targeted searches when I'm looking for a specific set of skills.

**Comment by Adam-JF** [comment]
Skill search enables this.
