### ISSUE TITLE
Adding candidate's skills to the search results view

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#210]
As a user of the app, I would like to see the candidate's skills (and number of endorsements for that skill) displayed within the search results view, so that I don't have to click into the candidate's profile page to have a quick understanding of their specialties.

The skills displayed within the search results should _first_ show the skills that were **searched for** and only then go on to show the candidate's other skills, ordered by 'most endorsements first'.

**Comment by iteles** [comment]
We need to test the UI and confirm with @Adam-JF for this but I would suggest starting with no more that 4 skills displayed.

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

Furthermore, I agree, 4 skills would be the best starting point. The skills displayed should be prioritised by the ones the user has searched for.

ie. User searched for 'PHP, Java and CSS'
Candidate skills listed as 'PHP, Java, CSS and Ruby' (Ruby would be the highest endorsed skill after the searched skills)

**Comment by SimonLab** [comment]
Just to recap the goal of this feature:
A search with a list of skills defined (separate with a comma ex: javascript, c++, haskell) will return profiles with these skills (if the a profile only have javascrt and c++ it won't appear in the result because it doesn't have haskell). For me the advantage of display the skills of the search comes from display at the same time the number of endorsment to show the strength of this skill.
If there are less than 4 searched skill then we display the next best skills.
However some profiles doesn't have the number of endorsement, so do we then display the first skill in the list?

**Comment by iteles** [comment]
@SimonLab Correct. We display the skills that were searched for and their endorsements. Then the next-best skill based on highest number of endorsements. 

@Adam-JF Would you say that if the other skills (which were not in the search) _don't have the number of endorsements_ we should just display other skills at random until we have 4 skills displayed?

**Comment by heron2014** [comment]
Logic of this feature: 
1. Our search on the field skills, e.g: css, javascript, python is an array of strings: ['css', 'javascript', 'python'].
2. For each of the results from the search in Elasticsearch (each candidate profile) 
- check if these skills are in these candidate profiles
- get the level number for these skills
- sort these skills by level (highest first)
- display skills on candidate headline
3. Display only 4 skills
- check how many from searchable skills exist in the candidate profile
- if the 4 of searchable skills exists in the candidate profile - display them
- if less than 4, get remaining number of skills based on level

**Comment by heron2014** [comment]
Current UI for displaying searched skills: 

- if candidate has endorsement:
![skills-display](https://cloud.githubusercontent.com/assets/8476884/12653004/675f1ca8-c5e5-11e5-91ba-5f1b292ce308.png)
 
- if candidate has no endorsement:
![no-score-skills](https://cloud.githubusercontent.com/assets/8476884/12653018/770594e8-c5e5-11e5-818f-bd84ca148b77.png)

**Comment by iteles** [comment]
I would suggest we:
+ Keep the corners straight and not rounded
  + For the final app we will be rounding everything, but seeing as we currently have straight corners on everything else, the rounded corners make the look a little disjointed
+ Make the background of the number of endorsements fit in with the rectangle as a whole so that the whole rectangle looks like one fluid piece of information
+ Consider changing the colour of the rectangle so that is stands out a little more - we know that skills are one of the most important things in the search

To illustrate the points above and as a mere example:
<img width="266" alt="screen shot 2016-01-28 at 19 54 30" src="https://cloud.githubusercontent.com/assets/4185328/12657065/6df4a3da-c5f9-11e5-8271-e8ab79afdd17.png">

**Comment by heron2014** [comment]
Updated UI:

![new](https://cloud.githubusercontent.com/assets/8476884/12662881/4c2b19ba-c61b-11e5-97e9-5a3f7aa2c3ed.png)

**Comment by nelsonic** [comment]
@heron2014 nice. What are your thoughts on using the Client's colorscheme for this new feature? :question:

**Comment by heron2014** [comment]
@nelsonic sure:

Example with Client's scheme colour: 

![green](https://cloud.githubusercontent.com/assets/8476884/12663161/82874b94-c61d-11e5-8b4e-869205633598.png)

Clients scheme colours: 

![pallette](https://cloud.githubusercontent.com/assets/8476884/12663088/c570bd92-c61c-11e5-8983-e871bf80d05b.png)

**Comment by iteles** [comment]
@heron2014 I would suggest we need more whitespace around the wording - it's all a little bunched up (and there is less space on the right than on the left). We also need to ensure the colour of the endorsement numbers don't clash.

But great job for today, hope you get some rest!!

**Comment by heron2014** [comment]
@iteles what you think about this one:

![new](https://cloud.githubusercontent.com/assets/8476884/12671096/4db4651c-c665-11e5-8bfa-51e7f0463529.png)

This is using only the green colour for both numbers and background.

**Comment by iteles** [comment]
Sorry @heron2014, still in my meeting! I think we probably need to make those numbers bold or do a completely different colour. Sadly those are pretty hard to see :(

**Comment by SimonLab** [comment]
@Adam-JF do you also want to see the list skills on the home page without having to do a search?

**Comment by Adam-JF** [comment]
Getting team feedback regarding @SimonLab comment.

**Comment by iteles** [comment]
@Adam-JF From our sprint demo earlier today, Nick and yourself signed off this issue. Let's close this one and create a new one relating to the homepage view specifically if we find it's required :+1:

**Comment by Adam-JF** [comment]
Works great.
