### ISSUE TITLE
Email a candidate from within the application [outgoing emails only]

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#211]
As a user, I want to be able to email a candidate from within the application so that all of my communications with them are tracked.

<hr/>

+ Linked to #212 
+ As discussed with @Adam-JF, this will be basic for sprint 5, keeping track of outgoing communications only for now.
+ The email  to the candidate will need to appear to come from the company email address with which the user has logged in

**Comment by iteles** [comment]
Assigning to @nelsonic initially for the architecture and initial work.

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

**Comment by SimonLab** [comment]
@nelsonic Do you have any reading/testing suggestion concerning the email functionality. We are going to have a look at the official doc: https://developers.google.com/gmail/api/guides/sending . Did you find more doc on your side? Thanks

**Comment by heron2014** [comment]
Each candidate with en email address has a button (send email). We are reusing the same endpoint and view as for multiple emails. 

Current basic wireframe, not styled for this feature: 

![email-candidate](https://cloud.githubusercontent.com/assets/8476884/12844545/d7e95566-cbf7-11e5-9197-d30c75827b6a.png)

**Comment by Adam-JF** [comment]
Works great.
