### ISSUE TITLE
Email multiple candidate from within the application [outgoing emails only]

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#212]
As a user, I want to be able to email multiple candidates at once from within the application so that the application can help to speed up my workflow and doesn't make me go into each candidate's profile to send individual emails.

<hr/>
+ Linked to #211
+ As discussed with @Adam-JF, this will be basic for sprint 5, keeping track of outgoing communications only for now.
+ The email  to the candidate will need to appear to come from the company email address with which the user has logged in

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

**Comment by heron2014** [comment]
Wireframe propositions for an email functionality: 

- home view 

![home_page_view_with_email](https://cloud.githubusercontent.com/assets/8476884/12782305/3761ad90-ca72-11e5-9a28-bf299a35a7d7.png)

- email dashboard

![email-dashboard](https://cloud.githubusercontent.com/assets/8476884/12782326/645d4070-ca72-11e5-923d-dff1ac059bde.png)

@iteles @Adam-JF @SimonLab @nelsonic please share your thoughts.

**Comment by Adam-JF** [comment]
Looks great.

**Comment by SimonLab** [comment]
Just a reminder for the dev team: Display only the checkbox if the profile has an email (or make t uncheckable?)

**Comment by heron2014** [comment]
@SimonLab good shout.

**Comment by heron2014** [comment]
Proposition of an email dashboard for this sprint :

![email-basic](https://cloud.githubusercontent.com/assets/8476884/12785837/55b95d7e-ca86-11e5-90f5-9a33b65a3c8e.png)

**Comment by heron2014** [comment]
Currently on a home view page we have checkboxes referenced to each candidate and email button (this is basic view for now - not styled):

![home-view-email](https://cloud.githubusercontent.com/assets/8476884/12843834/d36a7c30-cbf3-11e5-8edb-084f7158bef4.png)

View with selected checkboxes look as following: 

![checkboxes-email](https://cloud.githubusercontent.com/assets/8476884/12843858/f6e4805c-cbf3-11e5-889a-9a14bac7c297.png)

User is redirected to the email dashboard. At this point we are populating relevant information: emails, user name and image

![email-endpoint-basic](https://cloud.githubusercontent.com/assets/8476884/12843951/5d0803c2-cbf4-11e5-8db7-ebfa3be15074.png)

**Comment by heron2014** [comment]
Current styled email-dashboard - multiple emails attached: 

![multiple-emails](https://cloud.githubusercontent.com/assets/8476884/12853096/1fd90f10-cc2a-11e5-97eb-b11086460e14.png)

(orange is taken from client's colour palette)

@iteles please share your thoughts.

**Comment by iteles** [comment]
@heron2014 Looks good!

My only comment is around the white writing on yellow background as per the dashboard discussion, usually isn't great for accessibility, but we can test this if you like.

Will the profile photo and name 'Anita' be part of the initial iteration?

**Comment by heron2014** [comment]
@iteles yes it comes from Google login reference [L37-L39](https://github.com/FAC-GM/app/blob/email/lib/email.js#L37-L39). 

Ok great we will test it tomorrow and amend accordingly.

**Comment by heron2014** [comment]
Currently we have managed to send emails to multiple candidate although we have this issue:
- in our loop [here]() we are calling the reply interface twice

screen shot of the response: 

![send_multiple](https://cloud.githubusercontent.com/assets/8476884/12922286/bab21f24-cf48-11e5-9fd3-9e1c5bfd22c8.png)

**Comment by heron2014** [comment]
Current **basic** email display feature: 

![emails-basic](https://cloud.githubusercontent.com/assets/8476884/12978529/5e585dce-d0c9-11e5-9d0b-cb3bc09b8333.png)

When click on subject - message will be shown and close button to close it. 

@iteles please share your thoughts

**Comment by iteles** [comment]
@heron2014 Where will this be displayed on the profile?

**Comment by SimonLab** [comment]
@iteles the list of emails are currently display under the note section.

**Comment by iteles** [comment]
I don't think that's where is will go permanently, but let's discuss it with GM tomorrow. Thanks @SimonLab

**Comment by SimonLab** [comment]
![emaildisplay](https://cloud.githubusercontent.com/assets/6057298/12991817/f4219232-d108-11e5-90bf-0311a0edf0ea.png)

**Comment by Adam-JF** [comment]
Testing:
A few bugs occur sporadically with this feature: 

- When sending an email to more than one candidate on the email creation screen, there is an error screen that appears having clicked 'send mail' however, the email itself **does ** send.
- Occasionally the 'send email' on the search results page becomes 'un-clickable'

**Comment by iteles** [comment]
@Adam-JF To test the application you'll need to quit the browser and log into the app again as we changed a fair amount of things for this email feature which will only be triggered with logging back in.

Can you please do so and test again so we know whether that's the issue?

**Comment by Adam-JF** [comment]
I have done so on my machine and have told everyone else to do the same.

The 'send email' becoming un-clickable only happens when you scroll down to the very bottom of the page - i'll demo this during the meeting.

**Comment by SimonLab** [comment]
To investigate
![errorgmail](https://cloud.githubusercontent.com/assets/6057298/13085143/a4c0c206-d4d4-11e5-94cf-eedc6aaec8ce.png)

**Comment by SimonLab** [comment]
![errorgmail2](https://cloud.githubusercontent.com/assets/6057298/13085260/2f7674ae-d4d5-11e5-8d82-71aba4329559.png)

**Comment by SimonLab** [comment]
http://stackoverflow.com/questions/24098461/nodemailer-gmail-what-exactly-is-a-refresh-token-and-how-do-i-get-one

**Comment by SimonLab** [comment]
@Adam-JF Do you still have some issue when sending some emails?

**Comment by Adam-JF** [comment]
@SimonLab Just tested this again and i'm getting the same error message however, this time the emails didn't send either.

**Comment by SimonLab** [comment]
ok Thanks, you should still be able to send some emails if you logged again to the app

**Comment by SimonLab** [comment]
@Adam-JF after getting a new token from Google we manage to send some emails without any errors. Can you please follow these steps
 
1. Navigate to your gmail settings: https://security.google.com/settings/security/permissions

2. Click on gm-app

3. Click "Remove" to remove the access of the app (this will force the app to give you a fresh token)

4. Close Chrome to be able to login again into the app, make sure that you reconnect to the app via the login page!

5. Test again if you can send some emails

Can you please test again if you can some emails after one or two hours after you have logged in into the app. Let us know if there are still some issues thanks.

**Comment by Adam-JF** [comment]
Fixed, works great.
