### ISSUE TITLE
Search for a company/client

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#214]
As a user, I want to be able to see all of the people in the app who are currently working for a specific company that I search for, furthermore I would like those individuals to be grouped into said companies.

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

**Comment by heron2014** [comment]
The current search fields include company field looks as follow: 

![search](https://cloud.githubusercontent.com/assets/8476884/12480414/0c04c80e-c03a-11e5-896a-1aed417a7eba.png)

**Comment by Adam-JF** [comment]
This features works well.
