### ISSUE TITLE
Create a homepage dashboard for *my* candidate's statuses

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#215]
As a user of the app, I would like to have a dashboard which shows me all of _my_ candidate's statuses at the current time, so that I can see where everyone is in the process at a glance.

<hr/>

As agreed with @Adam-JF, for the purposes of this task, a candidate's **owner** is defined as "the last person who changed the 'Notes' ( #168) section on a candidate's profile.

**Comment by iteles** [comment]
This will require some UI design, most of which has been started by @Adam-JF. We need to review the existing UI proposals and discuss them within this issue.

**Comment by Adam-JF** [comment]
The user story for this issue is accurate.

**Comment by heron2014** [comment]
Suggestion of the wireframe for this feature:

![dashboard](https://cloud.githubusercontent.com/assets/8476884/12674037/7c6f717c-c678-11e5-836a-ecbcd317a269.png)

@iteles @Adam-JF please share your thoughts about above wireframe. 


For the future iteration when we apply view for Clients, one of the options to display clients view could be (this is a suggestion to separate clients and candidates): 

- click able user picture in the right top corner with menu to swap views for candidates and clients
- tab at the top of the page, just below name of the user: Candidates, Clients: 

Basic illustration: 

![options](https://cloud.githubusercontent.com/assets/8476884/12674441/ec965004-c67a-11e5-976a-354eb712a56f.png)

**Comment by iteles** [comment]
:+1: :+1: 
+ The strip across the top with totals isn't part of the agreed scope for this sprint
+ The name and target at the top are also not a part of the scope, however, we will need some way to get to this page (the profile picture you have in the top right hand corner for example)
+ Have you had any thoughts on how we might be able to include the company that the status is at?

**Comment by heron2014** [comment]
@iteles just to clarify: 
- are we also include in this sprint company which we understood is the client view. Our first suggestion for clients is to be separate view accessed by clicking the tab, to not cluttered the candidates (could be lots of candidates)
- or do you mean that, for example under the picture of the candidate we will display:  fullname and company that this candidate is submitted to, interview at etc ?
- also by clicking on fullname under the picture - user will be redirected to the candidate profile where detailed information is provided (like to company name where this candidate is submitted)

- "target" is only hardcoded, and user picture is for future iterations as you said :)

**Comment by heron2014** [comment]
Open suggestion for accessing dashboard page: 

- currently we don't have user picture, which possibly in a future could be a link to the dashboard
- currently our wireframe looks as follow: 

![link](https://cloud.githubusercontent.com/assets/8476884/12680276/d1c6727e-c6a0-11e5-84cd-66fed64bfbcb.png)

One of the proposition for the sprint 5 could be:
- change the width of the fields at the top and add a link (button, fake picture) next to the star to access dashboard.  (on desktop there is a space without changing width )

@iteles please share your thoughts :smile:

**Comment by heron2014** [comment]
Can we start using flexbox? @iteles @SimonLab @nelsonic

**Comment by SimonLab** [comment]
I think the dashboard is a good place to start flexbox!

**Comment by iteles** [comment]
@Adam-JF Could you please confirm that you're happy for us to **not support Internet Explorer** as per our phone conversation this morning? http://caniuse.com/#search=flexbox

@heron2014 We should start with getting the correct data on the page first _anyway_, the CSS is step 2 :+1:

**Comment by Adam-JF** [comment]
@iteles Happy to move ahead with this.

**Comment by heron2014** [comment]
@iteles just to clarify: Dashboard will be only accessible by currently logged in user, for example: 
- if Adam is logged in he can accessed his dashboard but he can not access other people dashboard (to see their progress)
- only the Admin/ Manager has the right to access all users dashboard to see their progress

**Comment by iteles** [comment]
@heron2014 Correct.

Note that for _this_ sprint, the individuals' view is in scope but the admin/manager view is not. Worth putting some thought into it for overall architecture purposes though :+1:

**Comment by heron2014** [comment]
Current look of dashboard: 

![dashboard](https://cloud.githubusercontent.com/assets/8476884/12750566/ecb2d458-c9af-11e5-88f2-2de6577d7228.png)

@iteles @Adam-JF please share your thoughts.

**Comment by Adam-JF** [comment]
Looks great.

**Comment by iteles** [comment]
@heron2014 Can we go with the white background for now? We need to finalise the design in general but a black background will create a very disjointed look and feel from the rest of the app at the moment!

**Comment by iteles** [comment]
But other than that, I love it!

**Comment by heron2014** [comment]
White version:
![dash](https://cloud.githubusercontent.com/assets/8476884/12756230/b8e76e48-c9ca-11e5-9b37-8a8c55762794.png)


@iteles should I create PR with the above dashboard?

**Comment by iteles** [comment]
@heron2014 What flows better with the app? If we keep the white version we need to put the dividing lines back in between the phases?

**Comment by heron2014** [comment]
@iteles There are yellow/orange lines between rows. Just hard to see on above png :)

**Comment by heron2014** [comment]
Current look of the dashboard (we have changed the background from dark to light to not disjoint current design).

![dash-final](https://cloud.githubusercontent.com/assets/8476884/12780290/f18dc838-ca64-11e5-8d8e-b6bc8b9fa8f7.png)

**Comment by SimonLab** [comment]
The icon use is dislayed on the candidate view:
![icononprofilepage](https://cloud.githubusercontent.com/assets/6057298/12785392/49b94c84-ca84-11e5-81ee-c06e71903d84.png)

The [fa-user](https://github.com/FAC-GM/app/blob/b12e69e9e3be04a4bb5fe03b5a633f1ba0618cda/views/candidateView.html#L54) needs to be deleted

**Comment by Adam-JF** [comment]
Myself and Nick have been testing the dashboard feature and it works well.
However, Luke's isn't working - he is using an older iMac which may have something to do with it, let me know if there's anything I could try to make it work.

**Comment by iteles** [comment]
Hi @Adam-JF, thanks for letting us know so quickly :+1: 

Could you please drop in some screenshots so we can see in what way it's not working? It would be good to know:
+ The steps we would need to replicate the issue (i.e. Exactly what steps are being taken on Luke's machine)
+ What is not working
+ What browser and version of that browser is being used

Please :blush:

**Comment by Adam-JF** [comment]
Hi @iteles 

- Luke was on Jim Yip's profile on his Early 2009 iMac and created a note indicating he was at the 'Phone Screen' stage of the process with 'Further notes' saying - 'Monday 8th of February at 14:00 - 14:45hrs'
- This did not appear on his dashboard.
- We repeated it again with the same note and it didn't reappear, we tried refreshing the page on Jim Yip's profile, the dashboard and the whole app and it still didn't work.
- We then made a new note indicating he was at an 'Interview' stage and that again failed to show up.
- He was using Chrome - Version 48.0.2564.97 (64-bit)

![screen shot 2016-02-03 at 16 09 59](https://cloud.githubusercontent.com/assets/15364186/12788237/ba72bb8e-ca90-11e5-841f-5bd2a06b6136.png)
![screen shot 2016-02-03 at 16 09 49](https://cloud.githubusercontent.com/assets/15364186/12788240/bbbc1fbc-ca90-11e5-999f-c06fe6c346af.png)
![screen shot 2016-02-03 at 16 09 36](https://cloud.githubusercontent.com/assets/15364186/12788242/bd4a606e-ca90-11e5-830a-42444c16713b.png)

**Comment by SimonLab** [comment]
Thanks @Adam-JF.
We are using the first name of the Google account to define the "owner" of a candidate and it seems that Luke's first name doesn't appears. Can you try to reconnect to the app by closing all the Chrome windows and accessing the app again, you should be redirect to the login page. Then you can try first adding a new note to a candidate (the first name should appears next to the date) and accessing again the dashboard page. Let us know if this steps work, thanks.

**Comment by Adam-JF** [comment]
I've done all of the above. Closed Chrome completely, restarted the app, was prompted to login, repeated the steps to add the note and it didn't appear on the dashboard. Unfortunately Fritjof is having the same issue.

**Comment by SimonLab** [comment]
Thanks for checking. My other thought is that their Google accounts don't have a first name defined. Can you check in the preference on Google if it is defined or not (I'm going to search for the link of the Google preferences at the same time)?

**Comment by SimonLab** [comment]
You should be able to verify if a first name is defined on Google on this link: https://aboutme.google.com/

@Adam-JF can you let us know if the first names are defined for Luke and Fritjof. Thanks

**Comment by Adam-JF** [comment]
Hi @SimonLab I have checked both Fritjof's and Luke's first names on Google and they're both correct.

Ciaran is having the same issue with the dashboard.

**Comment by heron2014** [comment]
@Adam-JF thanks for confirming that. We are going to work to fix that. [Here](https://github.com/FAC-GM/app/issues/238) is the related issue for this.

**Comment by SimonLab** [comment]
@Adam-JF  We just deploy a new version of the app. Can you please test again this functionality. Thanks.

**Comment by Adam-JF** [comment]
Hi @SimonLab, great work. It's working properly on everyone's computers now. Thank you.

**Comment by SimonLab** [comment]
Good news! Thanks

**Comment by iteles** [comment]
Grand, thanks @Adam-JF, please go ahead and close this and any other issues you're happy with :blush:

**Comment by Adam-JF** [comment]
Dashboard works well.
