### ISSUE TITLE
Add contact owner's initials into mass candidate update

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#220]
As we're bringing in more data (part of our mass candidate update #194), we should look to include the initials of _who this candidate is connected to_ on the team.

**Comment by iteles** [comment]
@SimonLab @heron2014 Please _think_ through what the process to do this might be, _estimate_ how long it will take and we can then get approval from @Adam-JF before moving forward.

**Comment by iteles** [comment]
@SimonLab @heron2014 Approved by Nick! Please go ahead with this in Sprint 5 as part of the data migration.

**Comment by SimonLab** [comment]
:+1:

**Comment by Adam-JF** [comment]
Done.
