### ISSUE TITLE
See list of everyone connected to initials when any initials are clicked on

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#225]
As a user of the app, I would like to be able to see a full list of the people connected to me (or anyone else in the app) quickly and easily.

Linked to #194 .

**Comment by iteles** [comment]
The proposed UI (agreed with Nick) is that as a user, when I click on my (or anyone else's ) initials in the app, that will bring up a full list of everyone connected to whoever those initials belong to.

So for this example below, when I click on `FA`, I will see all of the people connected to `FA`.
<img width="989" alt="screen shot 2016-01-26 at 17 23 09" src="https://cloud.githubusercontent.com/assets/4185328/12588729/f3a68092-c451-11e5-8cd6-f0d48a20f074.png">

**Comment by Adam-JF** [comment]
This feature works well however, when going onto a particular person's list, I want a way of returning to the home screen without reloading the app/pressing the back button several times.

Can we put in a home button in the top left hand corner of the app which remains there at all times for quick navigation back to the front page?

**Comment by Adam-JF** [comment]
Please see issue #234

**Comment by Adam-JF** [comment]
Works great.
