### ISSUE TITLE
Update UI from wireframe given by product owner

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#226]
As a user I want the design of the platform to be matching with the current company branding design.

**Comment by iteles** [comment]
@Adam-JF All our past conversations have indicated that this is relatively low priority for Nick at the moment. Please let us know if that is not the case.

**Comment by Adam-JF** [comment]
Having spoken to Nick we have decided that when we have a client portal feature for the app (where clients can log in and view their pipeline etc.) that's when UI will become more of a priority. Naturally any small changes we can make to existing and new features to get them closer to the design would be great, but only if they are things that can be done in a few minutes as opposed to devoting a lot of time on them - a full overhaul isn't needed just yet.

**Comment by heron2014** [comment]
Resolved by new design #484 and #482
