### ISSUE TITLE
Connection not displayed

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#229]
on the home page the first degree connections are not display anymore:
![connectionotdisplay](https://cloud.githubusercontent.com/assets/6057298/12695923/84a5bb08-c754-11e5-84bc-e3743428d8b1.png)

**Comment by nelsonic** [comment]
@SimonLab it appears that the initials now appear *twice*: 
![gm-app-dupe-initials](https://cloud.githubusercontent.com/assets/194400/12697824/8964adb8-c784-11e5-8342-fac8eb0e4d63.png)

**Comment by heron2014** [comment]
@nelsonic It looks like it still appears that bug! I just checked the website. Investigating now.

**Comment by heron2014** [comment]
@nelsonic My bet! It's ok now, had to hard refresh haha

**Comment by nelsonic** [comment]
see: #232 ... :disappointed:

**Comment by SimonLab** [comment]
resolved with PR #233 and #232
