### ISSUE TITLE
Search by name

### ISSUE THREAD

**Issue by rub1e** [FAC-GM/app#23]
Is there a reason you can't search by name? If you type in "Jones" it performs a search, but doesn't display the profiles:

![screenshot 2015-10-22 at 11 22 56](https://cloud.githubusercontent.com/assets/11595920/10662896/5bdb9826-78af-11e5-866d-b3ab8151779d.png)

**Comment by rub1e** [comment]
OK, it seems that as you go through the pages, you there are profiles when you search by name. But it always seems to put these blank profiles first.

Also, I've tried searching for "Rubner" and "Labondance" and nothing - but "Czapla" gives me one result (not anita) - why is this?

**Comment by SimonLab** [comment]
@rub1e some empty data manage to be saved in our database unfortunately. Also the data is specific to the project and that's why you don't have some result for specific names

**Comment by rub1e** [comment]
Fair enough - but that only serves to underline the need for #20 

Can you filter out the empty data, or at least relegate it to the bottom of the results?
