### ISSUE TITLE
Click on Candidate name gives 404 Error

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#232]
![gm-app-candidate-view-error](https://cloud.githubusercontent.com/assets/194400/12698976/56a31166-c7a3-11e5-89ca-ced50a0a5fc3.png)

Steps to re-perform:
+ Open the App Dashboard
+ Click on the initials of the person who is connected to the first candidate
+ Once you are viewing the page of connections for a given person, click on the name or profile pic of the first person in the results page

@SimonLab  / @heron2014 please confirm if you see the same 404 error... thanks.

**Comment by iteles** [comment]
I see the same error.

**Comment by nelsonic** [comment]
the link is not being correctly rendered when viewing the results relating to a particular person... (*the `id` of the record is not in the url...*)

**Comment by SimonLab** [comment]
Yes I spotted this error yesterday but didn't have the time to create the issue. I correct it today!

**Comment by heron2014** [comment]
thanks @SimonLab

**Comment by iteles** [comment]
@nelsonic As per #233 and seeing as this was raised by you - could you confirm this is now fixed?

**Comment by nelsonic** [comment]
@iteles yes, I consider this fixed. closing. :+1:
