### ISSUE TITLE
Home Button

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#234]
As a user of the app I would like a permanent home button to be placed in the top left hand corner of the app screen so that I am able to quickly navigate back to the front page from anywhere within the app (candidate pages / search results).

**Comment by iteles** [comment]
:+1: Couldn't agree more! High priority?

**Comment by heron2014** [comment]
Current look of the home button at the top of each page: 

![home-button](https://cloud.githubusercontent.com/assets/8476884/12784503/75f70084-ca7f-11e5-8ce5-debed0c20e6f.png)

**Comment by Adam-JF** [comment]
That looks great. Exactly as I imagined it.

**Comment by Adam-JF** [comment]
Works great.
