### ISSUE TITLE
My name...

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#237]
If I search for my name, be it 'Adam Foster' or just 'Adam' I get the following screen message - '{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}'

Also, Nick has noted that my name also appears several times on the app - flattered as I am, do you know why this happening?

![screen shot 2016-02-03 at 16 27 55](https://cloud.githubusercontent.com/assets/15364186/12788915/7d946a7a-ca93-11e5-891f-2056dc8cb197.png)

![screen shot 2016-02-03 at 16 29 42](https://cloud.githubusercontent.com/assets/15364186/12788887/5f8ca75e-ca93-11e5-90a2-c8b1b070fc39.png)

**Comment by SimonLab** [comment]
It seems the chrome extension of  the user accessing your profile can't find your url
![adamprofile](https://cloud.githubusercontent.com/assets/6057298/12789294/1f8ca65c-ca95-11e5-8a3b-9ba29b805c3c.png)
 
To avoid duplicate into the database and to know when to update or create a new profile we are using this url as it is unique. Unfortunately your url is undefined so each time someone is accessing your profile a new one is created. This might be a result of a change of the structure of your page and the chrome extension doesn't recognise this structure. We are going to make more test with the extension and your profile to target the issue.

**Comment by iteles** [comment]
Thanks for raising this @Adam-JF and thanks for diagnosing the problem @SimonLab :+1:
We'll need to dedicate some time to understanding if there's a solution to this problem after we've finished the current sprint.

**Comment by SimonLab** [comment]
concerning the error it is due to the list of skills on Adam's profile which are currently undefined (see the previous screenshot). So the [toLowerCase function] crash because it can't be applied to the undefined skills:
![skillundefined](https://cloud.githubusercontent.com/assets/6057298/12790447/34c94200-ca9a-11e5-948b-427a0ad5d6e6.png)

**Comment by heron2014** [comment]
@SimonLab should we always check if skills actually exist before applying toLowerCase().

**Comment by Adam-JF** [comment]
Fixed.
