### ISSUE TITLE
App integration with website

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#240]
This story is an [epic](https://confluence.atlassian.com/agile/jira-agile-user-s-guide/working-with-epics) and will need to be broken down into multiple steps as we work them out.

Currently there is a **deadline of 31st March 2016** to integrate the application with the website to replace the current BH solution.

Flows of information required:
+ Client and job information: _app :arrow_right: website_
+ Candidate applications to specific jobs: _website :arrow_right: app_

**Comment by Adam-JF** [comment]
Working great so far - well done guys.
