### ISSUE TITLE
Get list of information required for website from TOAD

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#241]
We will need the list of properties that TOAD will require in our JSON object to allow them to pull the client and job information from the app into the website and the properties that they will be sending as part of the candidate application from the website to the app.

_Linked to #240_

**Comment by iteles** [comment]
From TOAD:

**Jobs Request**
Let's start with the request we're making to fetch all the jobs and to display them on the website.

At the moment we're trying to get all of the jobs available in Bullhorn, hence the request fetches the latest 200 jobs which are currently open and are ordered by their start date (descending) and title (ascending). 

The Bullhorn fields we are currently using for each job are:
+ id
+ title
+ description
+ startDate
+ dateAdded
+ dateEnd
+ skillList
+ address — Just city and countryID
+ categories
+ businessSectors
+ customText1 — Seniority
+ customText3 — Subtitle
+ customText5 — Square 1 Description
+ customText6 — Square 1 Image
+ customText7 — Square 2 Description
+ customText8 — Square 2 Image
+ customText11 — Square 3 Image
+ customText12 — Salary Currency
+ customTextBlock1 — Intro
+ customTextBlock2 — Square 3 Description
+ salary
+ payRate
+ owner
+ source
+ employmentType

**Additional requests**
Other than the job request, in order to render the page we're making two more:
+ **Countries** — we're making a request to fetch all the countries so that we can display the countryID as a string
+ **Business sectors** — these are needed for one of the filters. They include Fintech, Big data, eCommerce, etc.
+ **Owners** — we need to know the job owner to whom we're sending an email notification when someone applies for their job

**Rendering of the job pages**
The above requests for jobs, countries, sectors and owners are currently made every hour using a cron job. All data received is stored into JSON files, which are rendered server-side through PHP on the jobs pages — both for the listing and the single job page. This is due to request speed issues when doing the request on every page load, as well as limitations on Bullhorn's side for the amount of requests and concurrent sessions we can have through their API.


**Filtering on the job page**
On the jobs page we have several different filters. At the moment all of our filtering is done through JS — as we are loading all of the jobs on the same page, we can use data attributes to assign different parameters to them, which we can later use to filter them out. As you might imagine, that is quite a messy way to do filtering, but as we are restricted with the amount of requests we can make to Bullhorn, it seemed like the only feasible solution.
+ Country
+ Location (cities)
+ Role — backend, frontend, Android, iOS, etc.
+ Sector — eCommerce, startup, fintech, etc.
+ Seniority — junior, midway, senior, director
+ Type — permanent, contract
+ Salary Range — fixed ranges: < 40K / 40-60K / 60-80K, 80-100K / >100K

The filters work on an exclusive basis — when you select the "iOS Developer" role from the filter, all the other filters adjust to match the available jobs in there. So for example, if all the jobs available have a salary range of 60-80K, only that range will be displayed in the Salary Range filter. This is to avoid a case in which no jobs are displayed on the screen.


**Candidates**
With the current website, we have two different forms in which a candidate is registered with Bullhorn.

There is a form on the jobs listing, which sends all the data of the candidate, but does not shortlist them for a job.

If the user applies through a single job page however, they are assigned to the job through the Bullhorn shortlisting functionality.

The fields for both forms are the same: name, surname, email, phone, skill set, CV, comments.

**Candidate Requests**
In order to create a candidate's profile in Bullhorn, we are making 2 or 3 different requests, depending on the situation.
+ Create the actual "Candidate" object in the Bullhorn database: this includes persisting their name, surname, email, phone, skill set and comments from the form.
+ Upload their CV to the Bullhorn servers and associate it with the candidate which was just created
+ If the request is sent from a single job page as a job application, the candidate is also shortlisted for that job.

**Team Submissions**
At the moment there is an option on the Global {M} website to register teams, but that's not integrated into Bullhorn and is done entirely over email.

**Email notifications**
At the moment we are handling quite a few email notifications on our end, because of the lack of support for those in Bullhorn.
+ When someone applies for a job on the single job page — candidate confirmation and job owner notification
+ When someone RSVPs for an event — user confirmation and Global {M} team notification
+ When someone submits a team on the Teams page — team creator notification, team member notification, as well as a special email if there is only one team member who has applied; also a Global {M} team notification.
+ When someone submits an enquiry on the Clients page — enquiry confirmation for the user and a notification for the Global {M} team
+ When someone registers as a candidate on the jobs listing page — candidate confirmation and Global {M} team notification
+ An email when someone signs up for the Campaign Monitor newsletter

**Comment by SimonLab** [comment]
When we will created a form to updload the new jobs, do we need to upload the images on the website, do we need some special access or do we need to store the images in another new server (aws?)

**Comment by SimonLab** [comment]
The process need to be added in the documentation. see #333
