### ISSUE TITLE
User dashboard - photos overlap instead of wrapping to next line

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#244]
From @ahemsley2:

"I have attached a photo of a glitch that i have found when you add more than 6 people to a section, it overflows onto the section below:"

![screen shot 2016-02-10 at 17 16 41](https://cloud.githubusercontent.com/assets/4185328/12956110/3563dd90-d01e-11e5-8979-bbb0b43f5673.png)

**Comment by Adam-JF** [comment]
Fixed.
