### ISSUE TITLE
Minor padding imbalance

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#246]
The name text is hitting a little too close to that dividing line, making the whitespace feel a little imbalanced:
<img width="894" alt="screen shot 2016-02-10 at 19 17 48" src="https://cloud.githubusercontent.com/assets/4185328/12958909/e0b88f30-d02b-11e5-9a07-f6cf51872a3b.png">

**Comment by iteles** [comment]
Now looks like this:
<img width="862" alt="screen shot 2016-02-10 at 19 29 56" src="https://cloud.githubusercontent.com/assets/4185328/12959161/2f5ce13a-d02d-11e5-93a1-a27465f6c131.png">

**Comment by iteles** [comment]
@heron2014 Note: Equally happy to reduce the whitespace above the pictures (rather than increasing the whitespace below them as I have done)

**Comment by heron2014** [comment]
@iteles nice one!
