### ISSUE TITLE
UI optimazation for home page

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#249]
To be able to make a position fixed in our navabar where is Select all and {M} we need to change layout from flexbox to regular - at least that row. 
Rejoint this particular row from the rest of the page create alignment issue but its positioned fixed.

screen-shot:

![fixed-navbar](https://cloud.githubusercontent.com/assets/8476884/12980807/f41eee52-d0d5-11e5-8b35-d45e0eecbe6d.png)

Questions are : 

Should we go for this option with alignment not exactly placed? 
Should we re-factor home layout to fit perfectly new features in the next sprint?
Should we place button send email at the bottom (for now)

@iteles please share your thoughts, thanks you.

**Comment by heron2014** [comment]
At the moment we placed the button- send email at the buttom fixed position so its always visible. 

screen shot:
![current](https://cloud.githubusercontent.com/assets/8476884/12982147/7525615c-d0db-11e5-90a5-cc750092c547.png)

**Comment by iteles** [comment]
I like that idea, let's test it with GM and see how they feel about it

**Comment by heron2014** [comment]
Resolved by the new design #482
