### ISSUE TITLE
Disable prev and next when it's only one page

### ISSUE THREAD

**Issue by rub1e** [FAC-GM/app#25]

**Comment by nelsonic** [comment]
:+1: 
well spotted.

**Comment by SimonLab** [comment]
:+1:

**Comment by heron2014** [comment]
Resolved by this [PR](https://github.com/FAC-GM/app/pull/27)

**Comment by rub1e** [comment]
@heron2014 we're supposed to be setting an example for the next generation of FAC, and here you are closing other people's issues? HAVE YOU NO SHAME?

**Comment by heron2014** [comment]
ups :fish: memory
