### ISSUE TITLE
Additional statuses for candidates 

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#250]
As a user of the app, I want to be able to place my candidates into a few more statuses than those that exist now so that I can have a more detailed view of the candidates I put forward.

Requested statuses from @ahemsley2:
+ Submitted
+ Phone screening 
+ Technical assessment 
+ Technical Interview 
+ Final interview 
+ Placement 

_Linked to #247_.

**Comment by heron2014** [comment]
Resolved by #431 (this PR contains status and notes)
