### ISSUE TITLE
Mass emailing with First Names

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#257]
As a user I would like to be able to send a mass email out to a list of people whilst also addressing them by their first names in the email aka. 'Hi Adam,' when I simply typed or selected, 'Hi [First Name]' - like a choose salutation option.

The following link may be a solution - http://steffondavis.com/customize-mass-emails-with-gmail-mail-merge-tutorial/

**Comment by heron2014** [comment]
Currently , if user will type in a message area : 

Hi {name},

Hope you're well {name}! 

{name} will be replaced by the first name of the candidate.

**Comment by Adam-JF** [comment]
@heron2014 Will this work in the subject line for an email?

**Comment by heron2014** [comment]
@Adam-JF at the moment we are testing on message area, then we apply to subject as well.

**Comment by heron2014** [comment]
### Note! First name is populated as follows: 
example: 'Anita Czapla' - we split on space and take the first part. We also added function to capitalize first letter in case candidate name is all in lowercase.

<br/>


#### Summary:

- in the subject, to populate name user must type: **{name}**
- in the message area, to populate name user must type: **{name}**
- also if user types couple of times **{name}**  in message area - name will be replaced by candidate name.

#### Example of the email sent to the candidate looks as below:
<br/>
![email-hot](https://cloud.githubusercontent.com/assets/8476884/13283815/05db7fd6-dae8-11e5-952e-bf71837eb12f.png)

**Comment by heron2014** [comment]
Update:
Instead of typing {name} - we are dynamically populating in message area: 

**Hi {name}**  

If the user needs to use again candidate's name must type **{name}**

**Comment by Adam-JF** [comment]
Works great.
