### ISSUE TITLE
Sent Email Notification

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#258]
As a user of the app I would like to see an icon on candidate search results indicating I have sent an email to that individual without having to go into their profile - preferably with a time stamp indicating when this email was sent.

**Comment by iteles** [comment]
We will add the timestamp of the last email sent to that person in the search results view and make it red if that date is _less than **1 month ago**_ as agreed in our meeting yesterday :+1:

**Comment by SimonLab** [comment]
Just to be sure, users will still be able to send emails to this candidate but the indicator will indicate in red  if an email has been send during the current month?

**Comment by iteles** [comment]
Yes! Please drop in a screenshot of the proposed UI to this issue when you can @SimonLab @heron2014 :blush:

**Comment by heron2014** [comment]
This is just a working version: 

![current-email](https://cloud.githubusercontent.com/assets/8476884/13142765/4c2e6454-d637-11e5-8ab9-247a1217d87d.png)

The date become red if the email was sent within 1 month.

**Comment by iteles** [comment]
@Adam-JF Do we need this information to be further up the chain? Is it more important than skills and info for example?

Could we replace the '@' icon in the bottom right hand corner with this now that it is obvious from the checkboxes whether there is an email for that person or not? (for example)

**Comment by Adam-JF** [comment]
@iteles I've attached what my version would be.

![screen shot 2016-02-18 at 12 27 03](https://cloud.githubusercontent.com/assets/15364186/13143308/f5fa3ca8-d63a-11e5-89dd-c4252552de6e.png)

If that's too complex at this stage then yes, I think the '@' sign has become redundant when the presence of a tick box means we know they have an email address on their profile. As such, we can replace this with this date feature which turns red if its within a month.

**Comment by heron2014** [comment]
@Adam-JF Do you want to keep writing as well or just different colours of an envelope?

**Comment by Adam-JF** [comment]
@heron2014 Personally I think the colour of the envelope would be enough, its only three versions to remember and the colour coding is relatively obvious - Green is good, Red is bad, Blue you can get away with. That's how i'd explain it anyway.

**Comment by heron2014** [comment]
@Adam-JF thanks for confirmation :)

**Comment by iteles** [comment]
@Adam-JF Thanks for this, very useful.

I would suggest that adding in the blue might make it go from intuitive to less intuitive - if you're going to use a colour there **I would go with amber ** instead of blue ('email, but be aware they've heard from us this quarter).

And furthermore, in the individual profiles, I would suggest writing the explanation alongside the envelope to make it absolutely clear :+1:

**Comment by heron2014** [comment]
@Adam-JF @iteles new suggestion: 
instead of envelope we can use send icon as below, because we use envelope on candidate detailed view: 
![send](https://cloud.githubusercontent.com/assets/8476884/13146178/5fa2134a-d64c-11e5-976d-26ec813c4b01.png)

Tell me which one you prefer.

**Comment by heron2014** [comment]
@Adam-JF @iteles this is a current look of the email indicator: 
- email has been sent within 1 month
![30day](https://cloud.githubusercontent.com/assets/8476884/13146549/4048e8fa-d64e-11e5-8457-96db823d0ae5.png)

-email sent within 3 months time (blue)
![blue](https://cloud.githubusercontent.com/assets/8476884/13146577/584bbe78-d64e-11e5-9a26-671c6fd63498.png)

- amber 

![amber](https://cloud.githubusercontent.com/assets/8476884/13146811/309e0074-d64f-11e5-843d-d95bbb88db0f.png)


- regular view
![green](https://cloud.githubusercontent.com/assets/8476884/13146600/6fdde7f0-d64e-11e5-95dd-97864086df42.png)

@Adam-JF @iteles please confirm: 
- if we need to swap icon to envelope
- if we need to add text next to icon
- and which colour  (amber or blue)

Thank you

**Comment by Adam-JF** [comment]
@iteles Agreed with both points (changing colour to amber and adding explanation for the in profile view)

@heron2014 Let's go for the envelope.

**Comment by iteles** [comment]
@heron2014 Looks so cute! I would try making it a little bigger so the red is very obvious.

**Comment by Adam-JF** [comment]
Hate to throw a spanner in the works, but how difficult would it be to make it so we can filter candidates by how recently we sent them an email?

As in, I would want to prioritise those labelled as Green or as Amber as showing up before those listed as Red...

(I feel bad for asking already)

**Comment by iteles** [comment]
@Adam-JF A good question, best asked as a separate issue so we can estimate how long it will take to build in and figure out how to stop it conflicting with all the other filtering we are already doing :wink:

**Comment by Adam-JF** [comment]
@iteles Point noted, will do!

**Comment by heron2014** [comment]
@Adam-JF @iteles Minor change to email indicator regards  to text : Not contacted: 

- if candidate hasn't been contacted at all -  we **don't display sent-icon at all**
- if candidate has been contacted after 3 months we display sent-icon **green** with text: **Sent after 3 months** instead of **Not contacted**
- if candidate has been contacted within 1 month we display sent-icon **red** with text: **Sent within a month**
- if candidate has been contacted within 3 months time we display sent-icon **amber** with text : **Sent within 3 months**

**Comment by heron2014** [comment]
Currently the look at this feature: 
- sent within a month

![home-view](https://cloud.githubusercontent.com/assets/8476884/13175237/00f3876a-d701-11e5-8e98-d9265032dbac.png)


- this is how it look at the candidate view page with text 

![candidate-view-email](https://cloud.githubusercontent.com/assets/8476884/13175220/e8afde1a-d700-11e5-9f97-208f2f940f3f.png)

**Comment by iteles** [comment]
Thanks @heron2014, @nelsonic and I will take a look at the PR. Let's test this size of icon and then let @adam-JF and the team tell us if it should be bigger in the search view 👍🏻

**Comment by Adam-JF** [comment]
Potentially some issues with the reliability of this.

Will double check with the team tomorrow morning, have a suspicion it's related to people not logging out of the app first before they started using the new features. Will make sure everything is tested again before the demo.

**Comment by iteles** [comment]
@Adam-JF If you could add some examples here of the profiles you're not sure the indicator is correct for, that would be very useful :relaxed:

**Comment by Adam-JF** [comment]
Works well. Issue surrounded people not logging out and then back into the app after the update was pushed.
