### ISSUE TITLE
Ellipsis before email text

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#260]
When sending an email to candidates en masse or individually the email will appear in someones inbox with a grey ellipsis before it.

Can we make it so this doesn't happen as it might make the email appear 'spammy'.

![screen shot 2016-02-16 at 15 45 24](https://cloud.githubusercontent.com/assets/15364186/13081416/9ebb2c58-d4c4-11e5-9440-266b96ec7881.png)
![screen shot 2016-02-16 at 15 45 31](https://cloud.githubusercontent.com/assets/15364186/13081418/a0dc81c6-d4c4-11e5-8982-27087780062c.png)

**Comment by iteles** [comment]
Good job on quickly fixing this @heron2014 !

@Adam-JF This is now working from my tests, could you please test again on your side?
