### ISSUE TITLE
Add signatures to emails

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#261]
As a user of the app I would like to be able to include my personalised signature at the bottom of new emails when sending them to candidates, including my title and working links to our social media pages.

![screen shot 2016-02-16 at 15 49 48](https://cloud.githubusercontent.com/assets/15364186/13081484/ed193110-d4c4-11e5-9361-dc74a8672aaf.png)

**Comment by iteles** [comment]
@Adam-JF Could you please provide the signatures for each member of the team?

I assume we'll also want to update:
+ The twitter link to https://twitter.com/Global_M_
+ The facebook link to https://www.facebook.com/GlobalMethod

(these look like they still lead to old versions of both on Nick's signature at least)

**Comment by SimonLab** [comment]
One solution to display the signature while creating the email: http://www.w3schools.com/tags/att_global_contenteditable.asp

**Comment by SimonLab** [comment]
- [ ] We need to get all the information for each user (phone numbers, LinkedIn url). I think that the Twitter, Facebook and Google links are unique.
- [ ] Store this information in Elasticsearch users type:
```
{idGoogle: {Names: {firstname: -, lastname: -, fullname: -}, email: -, phones: {office: -, mobile: -}, role: -, linkedin: -}
```
- [ ] When we load the email page we want to retrieve all the user information and generate the right signature

**Comment by heron2014** [comment]
Signatures also appear on email dashboard, as below: 

![email-dash](https://cloud.githubusercontent.com/assets/8476884/13284240/f270e35c-daea-11e5-993c-4a6e93750754.png)

@Adam-JF what do you think?

**Comment by Adam-JF** [comment]
@heron2014 - Looks great.

**Comment by Adam-JF** [comment]
Works great.
