### ISSUE TITLE
Filter number of candidates on a page

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#262]
As a user when I am looking to send out a mass email I would like to be able to filter the number of candidates on a page to more than 10 people per page.

Preferably up to 5000 at a time (the number of people we normally email for our events)

I'm aware when sending out that many emails at a time there will be a delay in them all sending - however, having the functionality to do so, regardless of the time it takes for them to go out would be really helpful.

**Comment by iteles** [comment]
@Adam-JF For a simplified version of this (given our BH integration deadline), we propose displaying 100 people per page for now. I have emailed Nick about this in response to an email he sent me just now requesting this.

Displaying 500 would drop performance of the app significantly and I would suggest this would end up doing more harm than good. Once the BH integration is done, we can look to extend this feature with a 'Show 500' option in the app for even faster emailing.

**Comment by SimonLab** [comment]
We are now displaying 100 profiles per page

**Comment by Adam-JF** [comment]
Works great.
