### ISSUE TITLE
Blacklisting client emails

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#264]
As a user I would like to have a safeguard ensuring I cannot contact a candidate about a job opportunity who is currently employed at a client company. This safeguard should be in the form of a popup warning which shows the offending address and gives us the chance to then remove that address.

An alternative would be to flag any profiles we have on the app which are listed as working at a client and then hiding them from search results until we have a client portal where we can store them.

**Comment by iteles** [comment]
@Adam-JF We thought we could improve on the user experience from the suggestions above (I imagine you will still want to be able to search for employees of clients to see if you can match skill sets for example), so we have a slightly different proposal: disable the ability to email a person if they are the employee of a client.

Steps to achieve this:
+ Create list of clients
  + Create list of alternative company names (to account for spelling mistakes in LinkedIn profiles, such as 'Transferwise' and 'Transfer wise'
+ Check if candidate is an employee of a client on the homepage and search page
  + If so, remove checkbox from next to that candidate's box in search results
  + Add 'Client employee' indicator to search results (to explain why you can't email that person)
+ Check if candidate is an employee of a client on the individual candidate page
  + If so, hide the 'Send email' button
  +  Add 'Client employee' indicator to individual candidate page

All possible solutions to this rely on the candidates in the app having an up to date 'Headline' as this is where the most reliable 'company of current employment' information comes from (see #214).

@Adam-JF Are you happy with this solution see as it's slightly different to your proposed ones above? :blush:

**Comment by Adam-JF** [comment]
That's a much better idea 👌

**Comment by iteles** [comment]
Excellent, thank you!

**Comment by SimonLab** [comment]
Now that we have the notes we can also check if a candidates has been submitted to a company:
![notesobject](https://cloud.githubusercontent.com/assets/6057298/13141621/32b36134-d630-11e5-9d13-8f344df3e652.png)

Should we even sent an email if the candidate has a note, or a specific status. For example do we want to send an email if a candidate has been submitted to a company? I don't think we should send an email if the candidate has been place in a company? 
@iteles @Adam-JF @heron2014  any thoughts?

**Comment by iteles** [comment]
@SimonLab I think that is an entirely separate feature which @Adam-JF will create as a separate issue if required. It's not a blocker for this issue though.

The question of whether people should be allowed to email candidates which are already at some stage of the process with another owner is a good one!

**Comment by iteles** [comment]
@Adam-JF Could you please provide us with a list of client names?

**Comment by SimonLab** [comment]
- [ ] Create type clients in Elasticsearch to store the list of clients. For each client we associate possible names:
```
{transferwise: {names: [transfer wise, transfer-wise, transferwise]}
```

- [ ] When loading the home page, the query page or a candidate page we will check if the current company of a profile exists in the list of clients' name. If yes we disable the checkbox or disable the button send email on the candidate page

**Comment by Adam-JF** [comment]
@iteles In the process of putting this together for you.

Would it be possible to be able to add/edit these 'client statuses' manually from our end?

So the initial upload just blacklists active clients, but we'd want to upload prospects as well - then we'd want to be able to turn a filter on to blacklist the client (so we can't email them) or off, if we for instance stopped working with them.

**Comment by iteles** [comment]
@Adam-JF Could you please add that as a separate issue? 

It's certainly doable but will make most sense when we're building out the client side of the app during the Bullhorn integration. https://github.com/FAC-GM/app/issues/240
We will also need to think about how we introduce the possible 'alternative spellings' in that scenario.

**For this sprint, we will hard-code this list in as a stop-gap but can build this out in upcoming sprints.**

**Comment by SimonLab** [comment]
We are currently testing the feature and at the moment we are checking if the current status of a profile match perfectly a company name: if we have "Founders and Coders" and the current status of a candidate is "**developer** at Founders and Coders" we are not blacklisting this profile. We can improve the feature toward this way by checking if a company exists in the current status of a profile, the only problem is that we can blacklist some profiles with a similar company name. For example if the company name is Founders it's going to match the profile with the status "Founders and Coders". I don't think there are a lot of these cases but it can still occur. @iteles @Adam-JF what are you thoughts on this?

**Comment by iteles** [comment]
@SimonLab Could we limit the search to containing the full string we give it? i.e. if 'Transferwise' and 'Transfer Wise' are on the client list, it will search for straplines that contain 'Transfer Wise' as a full string.
Therefore if the 'strapline' in a person's profile says 'developer at Transfer wise' it will block them, but if it says 'developer at Wise' it will not.

_Question: We're talking about the strapline here and not the status (which is created by GM team and not on linkedin), right?_

**Comment by SimonLab** [comment]
@iteles yes we are using the strapline (called current in the database)

To rephrase the question, when we search for profiles working at "Kayak" for example, we are going to have these profiles:
![kayak](https://cloud.githubusercontent.com/assets/6057298/13251053/c7e02834-da25-11e5-8bad-4b09e0b13005.png)

We are checking if the word "kayak" exists in the strapline, if yes we blacklist the profile. But:

The first profile works at "Jackson Kayak" and we shouldn't blacklist it.
The second profile works at Kayak and we should blacklist it.

The problem here is that we can't distinguish between a role ("Software Engineer at") and a similar company name ("Jackson Kayak").

I think this kind of cases is rare. The basic solution for this is to only blacklist profile where the strapline is only "kayak" but we are going to miss a lot of profiles like "engineer at kayak", "developer at kayak"...

@Adam-JF do you have any preferences on this issue? Thanks

**Comment by Adam-JF** [comment]
@SimonLab Like you said, I feel these cases will be rare.

However, this raises the issue that if there is a mistake with the blacklisting (aka. that person isn't employed at KAYAK), we'll need a way of being able to contact that individual. 

For instance, if someone then goes onto a person's profile and clicks send email even if they've been blacklisted on the main list, there's some kind of override so we can still send that person an email, they however, remain excluded if we're trying to mass mail a list of candidates.

**Comment by SimonLab** [comment]
Thanks @Adam-JF . So to recap: It is not possible to select on the home/search page a blacklist profile to send an email. However by accessing the profile itself we can still click on send email button.

**Comment by Adam-JF** [comment]
@SimonLab Yes, that's right.

Will there be any way to manually blacklist people?

For instance, a few contractors we placed list themselves as working in their own limited company, not the client we've placed them at, as such it would be helpful to blacklist these people by going onto their profiles. Again, this isn't going to be particularly common, but one example just came to mind.

**Comment by iteles** [comment]
@Adam-JF That's a well remembered edge case. Could you please open the manual blacklisting as a separate issue so you can prioritise it in relation to the rest of the backlog?

**Comment by heron2014** [comment]
Currently: 

on home/search view:

![client-employee](https://cloud.githubusercontent.com/assets/8476884/13258284/7c5d66e0-da4a-11e5-8c77-de1cfecb881d.png)

On detailed view:

![client-employee-detailed](https://cloud.githubusercontent.com/assets/8476884/13258331/a67553c0-da4a-11e5-9993-6d2924358021.png)

**Comment by iteles** [comment]
@Adam-JF That's a well remembered edge case. Could you please open the manual blacklisting as a separate issue so you can prioritise it in relation to the rest of the backlog?

**Comment by Adam-JF** [comment]
Works great.
