### ISSUE TITLE
Provide exported jobs from BH

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#271]
@Adam-JF can you please provide the list of exported jobs from bullhorn. We need this to determine the format they are in so we can bring in to the app. 

Thank you.

**Comment by Adam-JF** [comment]
This is our list of 'Active Accounts' - Clients we currently do business with

[Client List.xlsx](https://github.com/FAC-GM/app/files/137871/Client.List.xlsx)

**Comment by Adam-JF** [comment]
This is a full list of all of our clients who we've previously worked with, or are prospects for the future.

[Full Client List (Including Prospects).xlsx](https://github.com/FAC-GM/app/files/137873/Full.Client.List.Including.Prospects.xlsx)

**Comment by SimonLab** [comment]
Thanks @Adam-JF we just download the files and deleted the comments to limit the access
