### ISSUE TITLE
Sent emails should display in reverse chronological order

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#274]
As a user I would like to see the _latest_ email that has been sent to a candidate at the _top_ of the Email History list as I care more about what was last sent to this person than something that might have been sent months ago.

@Adam-JF Can you confirm this is the case?

<img width="607" alt="screen shot 2016-02-21 at 11 57 17" src="https://cloud.githubusercontent.com/assets/4185328/13202430/9336e81e-d892-11e5-8be0-b3182fc15d4a.png">

**Comment by SimonLab** [comment]
@iteles The list of emails should already be ordered this way. Did you test it on the current app or on your localhost?

**Comment by iteles** [comment]
@SimonLab localhost when testing #272 . Agreed this is closed in the main app! :blush: Thanks!
