### ISSUE TITLE
Create endpoints for jobs

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#286]
Here is the list of enpoints:

* [x] GET **/jobs/list** return the list of jobs
* [x] GET **/jobs/create** return a form to create a job
* [x] POST **/jobs/create** create a new job into the database
* [x] GET **/jobs/:id** display a specific job
* [x] POST **/jobs/update/:id** update a job

The first endpoint will be use to get all the jobs to display on the website.

@nelsonic @iteles do you think the naming is correct? Based on https://dev.twitter.com/rest/public and https://github.com/dwyl/learn-api-design

**Comment by heron2014** [comment]
Currently, we have created following endpoints:
 
- get /jobs/list
- get /jobs/create
- post /jobs/create

and very basic form with Toad attributes as follows: 

![basic-form](https://cloud.githubusercontent.com/assets/8476884/13359565/e024b322-dcac-11e5-8e44-c5d10d057760.png)

**Comment by nelsonic** [comment]
@SimonLab looks good. 
Are you going to use the same url endpoints for both `text/html` and `text/json` ?
(*so that you can access them in a browser or as an API...*)

**Comment by SimonLab** [comment]
@nelsonic nice question, I'm not sure if we should use the same name for the endpoint if they return html or json. We could precise the format in the endpoint: /jobs/list/html and keep the json format by default. Is it a good idea?

**Comment by SimonLab** [comment]
Also I'm not sure if the the website define properly the accept property in the header request. So I think th e simple solution is to return a json format by default or if the optional format in the url we return this format (for now just html but in the future we could return yaml or other formats)

**Comment by SimonLab** [comment]
We are using the access property in the header of the request to determine the format we need to return so html or json

**Comment by heron2014** [comment]
We are populating countries, owners and business sectors to the form on endpoint /jobs/create from elasticsearch, form is improved with properties from toad and bullhorn. 

To do list: 

* [ ]  Add validation 
* [ ]  Add date picker
* [ ] Double check if properties are the same
* [ ] Convert dates to timestamp
* [ ] Tests
* [ ] Check order of input fields to match the client preferred order

**Comment by SimonLab** [comment]
all the endpoints are ready with #362
