### ISSUE TITLE
Upload image for job

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#287]
A job can be linked to some images. At the moment they are updload directly to the wordpress website in a upload folder.

- Can we upload the images from our form job on the server to this folder? Do we need some credentials to access the wp server?
Or
- Can we updload the images in another server (AWS)?

@nelsonic @iteles @heron2014 what are your thoughts?
@iteles Can you get a confirmation if we can access the wordpress updload folder from our server to upload the images and what are the access credentials.

**Comment by iteles** [comment]
@nelsonic Would it be simpler to store these in AWS with the rest of our images and send through the link? This might imply a change on TOAD's end.

But I think it might be simpler if in the future GM want to build in functionality to re-use images for example.

**Comment by SimonLab** [comment]
We have the confirmation from Laura that the images are uploaded into the website then the link of the image is just copy/past to the image url field in BH.
So we don't need to upload the pictures to AWS as this process is done manually with the wordpress interface.

**Comment by iteles** [comment]
It makes sense for us to simplify this process where possible. Let's also keep that in mind.

**Comment by SimonLab** [comment]
For this first version we are going to keep the same manual way of uploading the pictures. We need to check if an automatic way to do this is required.
