### ISSUE TITLE
Post candidates endpoint

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#288]
create a post endpoint to create a candidates.
- [x] Find the details of the payload passed to the post /candidates endpoint
- [ ]  Add a mandatory field (LI url) to the candidate form on the website
- [x] Create a simple endpoints which log the payload received by the website (Do not create a candidate yet)
- [ ] Update a candidate with the new detail if the candidate already exists in Elasticsearch (search by email and the LI url)
- [ ] Create a new candidate in the Elasticsearch if the candidate couldn't be found by email or LI url

@iteles can we ask if it is possible to get the payload send to the future /candidates endpoints

**Comment by SimonLab** [comment]
Also we need to know how the cvs are uploaded to BH. Is the website doing this directly on the backend or can we get the cv file from the payload that we will receive on the endpoint?

@iteles Can we ask for more details on the upload of the file? The website might need to update the way it does it!

**Comment by iteles** [comment]
@SimonLab I get your second comment/question, but not so sure what you mean by the first. Do you mean you'd like an example of what is sent back to BH for candidates at the moment?

**Comment by SimonLab** [comment]
@iteles Yes I was wondering what is the data send to BH when a candidate submit her data through the website.

**Comment by SimonLab** [comment]
The cv is send with a specific request in the payload as an base64 encoded string. Can we save this cv in Elasticsaerch

**Comment by SimonLab** [comment]
So we need to create a specific endpoint for the CVs: **/cv/create**. This endpoint will receive this format of payload:
```
{
	"externalID": "Resume",
	"fileContent": $fileEncodedInBase64,
	"fileType": "SAMPLE",
	"name": $filename,
	"contentType": "application/octet-stream",
	"description":"CV",
	"type": "document"
}
```

- [ ] Create the endpoint and save the data  (except the fileContent) into ES ( to check what information we receive)
- [ ] Read documentation on Google on how to upload a file to Google Drive with the api and create a documentation for that
- [ ] Create a Hapi plugin to upload a file easily to Google Drive

**Comment by SimonLab** [comment]
We can use the google client to upload a file: https://github.com/google/google-api-nodejs-client#media-uploads

**Comment by SimonLab** [comment]
The cv is send as a base64 encoded string to the cv endpoint, so we are receiving something like:

JVBERi0xLjUNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFu\r\nZyhlbi1VUykgL1N0cnVjdFRyZWVSb290IDEwIDAgU...

At the moment we are saving this string into Elasticsearch. The base64 contains some \r which break the decoded function. Either the payload is not properly passed or Elasticsearch convert the string, test is progress

**Comment by iteles** [comment]
TOAD have confirmed that they can remove the special characters and will test this early next week.

**Comment by SimonLab** [comment]
This issue is now split into two sub issue #337 and #330
