### ISSUE TITLE
Links between Bullhorn and the website

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#291]
We know already that the website is using Bullhorn to store the list of jobs. Are there any other links between Bullhorn and the website?
- Testimonials
- Blog
- Clients
- Contact form
- Events
- Other links?
@iteles can we confirm that only the job list is linked to Bullhorn or are there any other data to migtrate?

**Comment by iteles** [comment]
@Adam-JF Do you think this is a question for TOAD or for you guys at GM?

**Comment by Adam-JF** [comment]
@iteles Best people to ask would be TOAD.

**Comment by SimonLab** [comment]
TOAD confirmed that the jobs are the only links between BH and the website
