### ISSUE TITLE
Json list job  vs Json detail job 

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#292]
@iteles Can we ask if the website need different properties for the list of jobs and for the detail of job? The list of jobs might have less data because the website display a resume of the job description.

**Comment by iteles** [comment]
@SimonLab The only thing I didn't find in the JSON object we were sent was the date (1st March in this case). Is that what you mean?

**Comment by SimonLab** [comment]
@iteles the date is in a timestamp format unders the property startDate.
There are two views on the website:
- the list of jobs with
- the detail page for a specific job
I was wondering if the list of jobs is built from the same objects as for the detail view or if for example the json object for the list is more succinct and with other names for the properties

**Comment by SimonLab** [comment]
The website use only one api /jobs/list which give all the information.
