### ISSUE TITLE
Import existing list of jobs to Elasticsearch

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#294]
From BH we can only export the resume of the jobs in the csv format. If we want all the details we need to use the api which is going to take more time to use.
A simple solution is to ask the website if they can export the list of jobs in the JSON format. They manage to quickly the detail for one job so I don't think it will be to complicated to have the all list.

@iteles Can we ask if it is possible to get the json format of all the jobs?

**Comment by iteles** [comment]
:+1: We'll have to run this one past Nick first as it may be cheaper for us to do it than for TOAD.

**Comment by SimonLab** [comment]
The website gave us the list of jobs
