### ISSUE TITLE
Reset Dashboards

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#300]
I think it would be a good idea to reset the dashboards on the application to clear the out of date statuses and so we can start fresh with the notes feature on the app.

**Comment by Adam-JF** [comment]
This issue has been sorted for now by simply deleting profiles in the app which then removes them from the dashboard.

We are able to re-add the candidate to the database simply by visiting their profile again.

**Comment by iteles** [comment]
:+1:
