### ISSUE TITLE
Update to Hapi 11.0.1 and node.js 4.2 ?

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#31]
https://david-dm.org/FAC-GM/app
<img width="970" alt="deps" src="https://cloud.githubusercontent.com/assets/194400/10667079/53c0f410-78cd-11e5-9785-c477dc1a2789.png">

**Comment by SimonLab** [comment]
With the [pull request 50](https://github.com/FAC-GM/app/pull/50) the dependencies are now all updated
![dependencies](https://cloud.githubusercontent.com/assets/6057298/11094746/6fc5e852-8889-11e5-80f8-2ed311b4a3ec.png)
