### ISSUE TITLE
Emails are going to spam

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#322]
All of the consultants are finding that their emails are going to spam.

I did a check to see if the Global M domain was blacklisted after Henry mentioned one of his emails had gone to spam, I also separately checked his IP address and there was no issue - I did this on Friday, 4th March 2016.

It's of vital importance we look into this asap otherwise people are going to stop using the app.

**Comment by nelsonic** [comment]
@Adam-JF how *many* emails did Henry send? :confused:

**Comment by Adam-JF** [comment]
@nelsonic He sent 800 (ish) in total on Friday

**Comment by Adam-JF** [comment]
According to the below link we should be able to send approximately 2000 without issue per day

https://support.google.com/a/answer/166852?hl=en

**Comment by Adam-JF** [comment]
https://support.google.com/mail/bin/answer.py?hl=en&answer=69585

**Comment by SimonLab** [comment]
@Adam-JF Have you try with your emails? Do you have the same problem? Also all the emails are going  to the spam folder? How do you manage to know when an email is in a spam folder?

**Comment by SimonLab** [comment]
Some documentation to investigate:
- https://support.google.com/mail/answer/6227174

**Comment by Adam-JF** [comment]
I've just spent about an hour on the phone to a guy at google support -

We've done some verifications on Go Daddy and he said that that will help us not to be listed as spam.

We're not on any blacklists and there aren't any notes on our account.

His explanation was that when we're sending lots of emails at the same time, if one person marks that as spam, some other people being sent the same message will also find their email in spam, even if they don't think it is. It's a safety measure, but it's not an issue with Gmail or the app.

**Comment by Adam-JF** [comment]
When we send emails through the app - that all runs through Gmail right? Not a separate thing through the app?

**Comment by SimonLab** [comment]
@Adam-JF yes we are using directly gmail to send the emails

**Comment by Adam-JF** [comment]
@SimonLab It's hard to say because we only hear about it if someone spots it and emails us back.

**Comment by Adam-JF** [comment]
Email correspondence from Google support guy after our conversation earlier.

Hello Adam,

Thanks for calling today, it was a pleasure speaking with you. 

You explained that some of your messages are reported by the recipients to land in the spam folder. 

Like we discussed the reason that messages are marked as spam can be due to literally 1000 different reasons. If the users reported this happening in their Gmail accounts, then it is Google's filter that is making the decision to act on those messages. 

Its decision, as mentioned, is based on various criteria where an important part plays the reports that other people send back. If multiple people report different or the same message as spam then those message are likely to be spam and will be treated as such by the filter even for other people that don't consider it as spam. 

To counter act this it is imperative to tell users that do want your messages to "teach" the filter by reporting the message as "Not spam". This happens by entering the Spam folder, selecting the message from you and clicking the button "Not spam". The more people do this, the better your reputation will be. 

Additionally your domain didn't have any authentication. As domains that are not legitimate usually don't have authentication, it is best to simply set SPF and DKIM authentication. Here is more about this https://support.google.com/mail/answer/180707?hl=en. 

As you are sending communication in Bulk, along with users reporting back to the system your messages, this can cause the system to be more "alert" about your mail. Therefore I advise on carefully going trough our bulk senders guidelines which are designed to keep you away from the spam folder as much as possible. Here it is https://support.google.com/mail/answer/81126?hl=en.

I also would suggest to remove any links, pictures or signatures in the messages at least until you can see this situation starting to improve. 

I’ll go ahead and close your case for now and you’ll receive an email notification. Your time is much appreciated and we aim to offer all of our customers an excellent support experience. With that in mind, if you need any additional assistance you can reply back to me anytime in the next 30 days and I’ll be happy to help.

For more information on the life of a support case, and it’s possible solutions please visit http://support.google.com/a/bin/answer.py?hl=en&answer=1047213.

It was a pleasure working with you, and thanks again!

**Comment by nelsonic** [comment]
@Adam-JF yes, the number of emails a given account can send via Gmail is 2000 per day. 
However if the *content* of the email is not perceived as relevant by the recipients and enough of them mark the email as "*Junk*" or "*Spam*" the sender will *quickly* be placed on the (*recipients*) email provider naughty list. pretty much as the Google Support guy has explained...

**Comment by Adam-JF** [comment]
Understood. What would you recommendation going forward be?

I've told the guys to get anyone who found our messages in their spam to unmark them, but apart from that - would limiting the number we send at a time help?

**Comment by nelsonic** [comment]
Quality over Quantity. 
Unless the people have *opted* in to receiving a message from you, they will *usually* consider it to be spam. Developers are *especially* quick to mark messages as spam because they get a *lot* of unsolicited email...
The best approach is still to start a *genuine* conversation with the prospective candidate.
This *can* be done through email, but sending email where the person's name is not mentioned *anywhere* (i.e. it looks like spam) is virtually *guaranteed* to result in the naughty step.

Its *always* a good idea to have company-wide communications plan.
In the first instance I would disable "*select all*" until you start getting a better response rate.
Ideally expand the email tracking so that its *clear* which of your contacts have opened/replied to a message and which ones have requested *not* to be emailed.

**Comment by nelsonic** [comment]
@Adam-JF is there a *Handbook* that everyone @GM reads when they join?

And/or do you have a recommended reading list? e.g: 
+ http://www.amazon.co.uk/The-Ultimate-Sales-Machine-Turbocharge/dp/1591842158
+ http://www.amazon.co.uk/The-Sales-Acceleration-Formula-Technology/dp/1119047072
+ http://www.amazon.com/Predictable-Revenue-Business-Practices-Salesforce-com/dp/0984380213/

I know you guys are all v. experienced at sales/recruitment, but sending impersonal email in bulk should be on a list of what *not* to do ... at least if you're making phonecalls you can hide your phone number, but email from a company domain is *way* too easy to get black-listed if *one* person sends out bulk impersonal messages...

**Comment by iteles** [comment]
Linked to the implementation of #301 !

**Comment by nelsonic** [comment]
@iteles agree 100%. if we don't give people a way to communicate their interest/disinterest with buttons they can use to un-subscribe then they will *inevitably* reach for the "*Report Spam*" button ...
![gmail-report-spam](https://cloud.githubusercontent.com/assets/194400/13571371/6a1f3bbc-e46c-11e5-8e15-37546688eee2.png)
