### ISSUE TITLE
Create endpoint for clients

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#326]
API for clients (following the design api for our jobs - for the consistency [jobs api](https://github.com/FAC-GM/app/issues/286#issue-136729726) ): 
* [x] GET /clients/list -returns a list of all clients
* [x] GET /clients/:id -returns a client with the given id
* [x] GET /clients/edit/{id} - return an edit client page
* [x] GET /clients/create  - return a link to create a client page 
* [x] POST /clients/save - update/create a client with the given id

We use POST instead of PUT and DELETE because these methods are not supported in html5 - [stackoverflow](http://programmers.stackexchange.com/questions/114156/why-are-there-are-no-put-and-delete-methods-on-html-forms)

Twitter API - don't use PUT nor DELETE - [ref](https://dev.twitter.com/rest/public)

**Comment by heron2014** [comment]
Real time update? How to make updates automatic without need to refresh the page?

- [https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html](https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html)

**Comment by heron2014** [comment]
@Adam-JF can you please confirm: 

- when you create a new client , do you assign new client to the person who created it? (do clients has owners?)

- currently we have one input field for the name of the new client, do you need any more input fields?

**Comment by Adam-JF** [comment]
@heron2014 
Yes, when there's a new client at the moment whoever uploaded it onto Bullhorn 'owns' the client.
Where are these input fields?
We need to be able to assign these clients to different consultants, this is with the view to eventually having a client portion of the dashboard where we can each see the clients we own.

**Comment by heron2014** [comment]
@Adam-JF ok thanks. We will create a drop down which will include all the names (user picks who is the owner)

**Comment by iteles** [comment]
@Adam-JF @heron2014 This feeds into the conversation around having updated UI designs. They should answer these questions before we end up having to rework code to retrofit things in.

**Comment by heron2014** [comment]
Re factoring clients endpoints to include new database structure, related to #338

**Comment by SimonLab** [comment]
done with #337
