### ISSUE TITLE
Dashboards aren't updating

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#327]
Myself and Luke have found that our dashboards are not updating when we submit candidates for different interview stages, they are not appearing in our dashboards.

**Comment by SimonLab** [comment]
Sometimes our database take a few seconds to index the new data. @Adam-JF do you still have this problem if you wait a bit and refresh the page?

**Comment by Adam-JF** [comment]
Unfortunately yes - i'll have a look at the logs and see if there's some kind of error and get back to you.

**Comment by Adam-JF** [comment]
Doesn't look like theres an error - the dashboards aren't updating, but the profiles register the changed status.

**Comment by SimonLab** [comment]
Ok thanks, it might just be a typo error in your email or name in the environment variables, I will have a look.

**Comment by SimonLab** [comment]
@Adam-JF can you give an id of a candidate who doesn't appear on your dashboard, thanks.

**Comment by Adam-JF** [comment]
Marc Liddell - Placement Status - https://www.linkedin.com/in/marc-liddell-a577a618 - Kibana ID - AVLHBbpRi_HarVsEEsoX
Ruben De Graaf - Interview Status -  https://www.linkedin.com/in/newneon - Kibana ID - AVMNUC8wi_HarVsEE7sb

Both submitted by myself.

**Comment by SimonLab** [comment]
This issue is resolved with #423
