### ISSUE TITLE
loaion of experiences

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#33]
We might have to change the property locaion to location as soon as we store into the database the right property

[L43](https://github.com/FAC-GM/app/blob/f55c4763daa100417c568994242299cfd92049ac/views/candidateView.html#L43)
[L54](https://github.com/FAC-GM/app/blob/f55c4763daa100417c568994242299cfd92049ac/views/candidateView.html#L54)

**Comment by nelsonic** [comment]
:+1:

**Comment by SimonLab** [comment]
The database has been re-indexed with the right name and the [pull request 50](https://github.com/FAC-GM/app/pull/50) has updated the name of the property [experienceHelper L6](https://github.com/FAC-GM/app/blob/master/views/helpers/experienceHelper.js#L6)

**Comment by nelsonic** [comment]
Thanks again for *correcting* this @SimonLab :+1:
