### ISSUE TITLE
Upload cv to Google Drive

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#330]
Linked to #288

We are going to save the CVs into Google Drive.
At the moment we are testing the following features
- [x] Receive a base64 encoded string which represent the cv. It can be a pdf, doc or in any other formats
- [x] Convert the base63 to a binary file
- [x] Upload the file to Google Drive 
- [x] Create a link to download/preview the document
- [x] Create tests for uploading a file, use nock

The above features are working for a specific user. We need now to have a specific Google tokens which are going to be use only to upload the files

- [x] Create and save the tokens used to upload the files
- [x] Test that the tokens are refreshed when expired

**Comment by SimonLab** [comment]
We have tested that we could upload a cv to a share folder and it works. We are still checking the Google  tokens validity on a long term. From the google documentation the token should be automatically refresh but it seems that some issues have been noticed: https://github.com/google/google-auth-library-nodejs/issues/67

Moreover the library hasn't been updated for a while and the build are failing: https://github.com/google/google-auth-library-nodejs

@nelsonic is it wise to maybe rethink and build a package which use directly the api of google instead of the nodejs client?

**Comment by SimonLab** [comment]
see also [this file](https://github.com/google/google-api-nodejs-client/blob/master/lib/auth/oauth2client.js). 
Explain that google-api-nodejs-client is using google-auth-library-nodejs

**Comment by SimonLab** [comment]
By looking at the code of the [google api nodejs client](https://github.com/google/google-api-nodejs-client) and by adding some log, it seems that the tokens are refresh automatically.

**Comment by Adam-JF** [comment]
Works great.
