### ISSUE TITLE
Interface for clients

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#331]
Design an interface for clients which will include: 

* [x] - link/button from home page or any page to clients page
* [x] - clients page where we list all of the clients
* [x] - when clicked on specific client, redirection 
* [x] - on clients list page, button/link to redirect to the Create Client Page or place  the form for creating new client on the same page 
* [x] - update/create form for updating/creating a client (possibly create client form can be merged with update form)

**Comment by heron2014** [comment]
@Adam-JF could you please attach some wirerames how you would like to see this feature?

**Comment by Adam-JF** [comment]
![screen shot 2016-03-10 at 15 26 31](https://cloud.githubusercontent.com/assets/15364186/13674203/8635b3f2-e6d4-11e5-8988-cfd9c89c958c.png)
![screen shot 2016-03-10 at 15 26 22](https://cloud.githubusercontent.com/assets/15364186/13674202/86345598-e6d4-11e5-895f-2ef264483a06.png)
![screen shot 2016-03-10 at 15 26 15](https://cloud.githubusercontent.com/assets/15364186/13674200/862d983e-e6d4-11e5-86d3-3dba9fdd11e3.png)
![screen shot 2016-03-10 at 15 26 03](https://cloud.githubusercontent.com/assets/15364186/13674201/862f9526-e6d4-11e5-9b87-d2c74cc0fcce.png)

**Comment by Adam-JF** [comment]
![screen shot 2016-03-10 at 15 26 03](https://cloud.githubusercontent.com/assets/15364186/13674225/94a85d86-e6d4-11e5-90b5-d1c81c538aba.png)
![screen shot 2016-03-10 at 15 26 15](https://cloud.githubusercontent.com/assets/15364186/13674230/96653220-e6d4-11e5-9f8b-437b854af23b.png)
![screen shot 2016-03-10 at 15 26 15](https://cloud.githubusercontent.com/assets/15364186/13674238/9d1b2872-e6d4-11e5-8b3f-3730ee87b51d.png)
![screen shot 2016-03-10 at 15 26 31](https://cloud.githubusercontent.com/assets/15364186/13674249/a5a2d5b2-e6d4-11e5-892b-f16b4a87fad5.png)

**Comment by iteles** [comment]
Note @heron2014 Please don't consider this the final designs as the integration of #332 may still affect this (particularly the jobs list addition to navigation, which is becoming very unwieldy)

**Comment by heron2014** [comment]
@iteles @Adam-JF We created the basic wireframes for client interface which look like this: 

![client-list](https://cloud.githubusercontent.com/assets/8476884/13701166/e17e4b12-e77d-11e5-8a55-c169149f51fd.png)

And the following view is for saving new client or updating new client.

![create-client](https://cloud.githubusercontent.com/assets/8476884/13701179/f70aba42-e77d-11e5-8d5f-1b0a31f4918f.png)

@Adam-JF just to confirm, active roles are the jobs available from that client?

@iteles what do you think?

**Comment by Adam-JF** [comment]
@heron2014 Yes, active roles are the current job openings for the company.

**Comment by Adam-JF** [comment]
Client Icon - <i class="fa fa-briefcase"></i>
Jobs Icon - <i class="fa fa-tasks"></i>

**Comment by heron2014** [comment]
thanks @Adam-JF

**Comment by Adam-JF** [comment]
Works great.
