### ISSUE TITLE
Interface for jobs

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#332]
Design an interface for jobs which will include: 

* [x] - link/button from home page or any page to jobs page
* [x] - jobs page where we list all of the jobs
* [x] - when clicked on specific jobs, redirection to detailed view job page
* [x] - on jobs list page, button/link for creating new job which will redirect to create new job page
* [x] - create new job page - form with all input fields, related to  #286

**Comment by heron2014** [comment]
@Adam-JF could you please attach some wirerames how you would like to see this feature?

**Comment by heron2014** [comment]
@Adam-JF this is a screenshot with following input fields from BH (create a job fields)
![job-form](https://cloud.githubusercontent.com/assets/8476884/13856745/900b19c2-ec6e-11e5-9bad-66d0e81fd3b7.png)
![job-form2](https://cloud.githubusercontent.com/assets/8476884/13856751/97157dac-ec6e-11e5-967a-7a46312dc8c0.png)

**Comment by Adam-JF** [comment]
Interface for job uploads:

Client, Team, Owner, Contract/Permanent = Drop Down Menus
Country, City, Salary/Day Rate = Manual Input

Everything else - manual input.

![screen shot 2016-03-18 at 14 29 36](https://cloud.githubusercontent.com/assets/15364186/13880845/2b4aebd6-ed16-11e5-91ef-449d85b741a5.png)

**Comment by Adam-JF** [comment]
![screen shot 2016-03-18 at 14 45 34](https://cloud.githubusercontent.com/assets/15364186/13881270/20237c9e-ed18-11e5-96cc-d56a5bb31d3d.png)

**Comment by Adam-JF** [comment]
Thats the main information we'd like displayed on the jobs list view - the initials on the right hand side are for the job owner, similar to what we have for connections.

![screen shot 2016-03-18 at 15 03 06](https://cloud.githubusercontent.com/assets/15364186/13881832/93bbff08-ed1a-11e5-8008-07885b46cfee.png)

**Comment by Adam-JF** [comment]
Detailed Job View
Open/Close Job - Toggle, not delete.
Candidate Submissions Tracking - if possible this Sprint

![Uploading Screen Shot 2016-03-18 at 15.32.07.png…]()

**Comment by Adam-JF** [comment]
Detailed Job View

Open/Close Job - Toggle not delete
Candidate Submissions - Profile images of submitted candidates

![screen shot 2016-03-18 at 15 32 07](https://cloud.githubusercontent.com/assets/15364186/13882769/cd6dc6a6-ed1e-11e5-9208-2495d119cfe8.png)

**Comment by iteles** [comment]
@Adam-JF Thanks for this. Some comments below.

**Individual job creation view:**
+ Should country, city and day rate be drop downs? I'm not sure I see the logic for having day rate be a preset list for this field
+ What is the team?

**Job list:** Displaying the initials and the required skills in the way you are proposing is not 'basic' and will require some further logic - we may find a simpler way to get this done for this sprint so you can still _see_ the information.

**Individual job view:**
We will have to simplify this for this sprint. @SimonLab @heron2014 and I will discuss on Monday and come back to you.

**Comment by Adam-JF** [comment]
@iteles 

**Individual job creation view:**
Day rate, Country and City are manual input - as in we'd type in the City Name, Country and Salary/Day Rate - thought this would save time so we didn't need to input currency differences or have to save a huge list of countries so that it would autofill.

**Job List**
Ok sounds great - with regards to the skills displaying, I mean it just displays the text of the first 5 skills entered in the job creation field - no matching/weighting at this stage.

**Individual job view:**
Sounds good 👌

**Comment by heron2014** [comment]
Populate client to the related job

**Comment by Adam-JF** [comment]
Works great.
