### ISSUE TITLE
Merge candidates created from the website

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#337]
When a candidate apply through the website we need to merge this candidate the one in the application if it exists.
For that every candidate created with the website must have a LI url.

**Comment by SimonLab** [comment]
The post endpoint /candidates/create receive the following payload:
```
{
"firstName":"NewTest3Firstname",
"lastName":"NewTest4Surname",
"email":"newTest4@example.com",
"phone":"2139847583",
"comments":"Just testing",
"skillset":"Ruby",
"name":"NewTest3Firstname NewTest4Surname",
"source":"Company Website",
"jobID": 12343244,
"linkedInURL": "theurl"
}
```

We need to confirm JobId and linkedInURL property names and values.

However from this information we need to create/update a candidate in the database.
When we receive these data
- [ ] Create an empty candidate object (create all the properties from and add the default values, the image url should be the image from #340 
- [ ] Add the information of the payload to this object
- [ ] If new cadidate ie the url doesn't exists in the database, create a new candidate
- [ ] Update the profile if the url exists already in the database

**Comment by SimonLab** [comment]
We need some validation on the url. It can be an empty string or a non valid url. So we need to create a validation on this property (is http://linkedin.com exists?)

**Comment by SimonLab** [comment]
When we update a profile (ie a url has been found in our database) we can update all the following values
```
"email"
"phone"
"comments"
"skillset"
"name"
"source"
"jobID"
"linkedInURL"
```
However we can have some edge cases. For example the names enter on the website and the name we have in the database can be different (accent, middle name added, nickname). Some user can also enter a url from a different profile with some wrong data (wrong data, wrong email...). @Adam-JF what do you think we should do,update everything or only the contact information (email, phone)?

**Comment by SimonLab** [comment]
At the moment if a LI url is found in the database we are updating the candidate with the contact infomrmation (phone, email) and with the information of the application (jobID, timestamp, skillset and comments)

**Comment by heron2014** [comment]
Things to do : 
* [ ] add validation to the url field
* [ ] test
* [ ] improve UI to display attached job to the candidate

**Comment by heron2014** [comment]
Display information regards the job on candidate view when candidate is applying for specific job.

**Comment by Adam-JF** [comment]
Working great thus far.
