### ISSUE TITLE
Image profile for candidates from the website

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#340]
For new candidate we need to add a specific profile image. At the moment we are retreive the profile image from a specific external url. We have two solutions:

- Upload a specific image to a cloud service to create a url and then use this url.
- Create an image and store it on the app and use the path to this image: /assets/img/profileImageWebsite.png

**Comment by SimonLab** [comment]
First version:
![ghost_person_150x150_v1](https://cloud.githubusercontent.com/assets/6057298/13743829/14a1c6d0-e9dc-11e5-8429-5ab5603c1002.png)

**Comment by SimonLab** [comment]
We are saving the image profile on the assets/img folder and we are defining the picture profile of the candidate with the same path

**Comment by iteles** [comment]
@Adam-JF Please see above - the proposition is that we have the above default image for any candidates we get from the website which are not already in the system. This should immediately explain why these profiles are so sparse.

**Comment by Adam-JF** [comment]
@iteles Were we not looking to add a field to the website applications/sign ups which would request their LinkedIn profile to be put in?

If we have this information will the profiles populate as expected with the images etc?

Personally, I don't think it's the most aesthetically pleasing image ever - perhaps using our 'M' logo would be better.

**Comment by iteles** [comment]
@Adam-JF The information that the candidate inputs into the form (name, email, URL) will be populated into the application, but as you know, the application doesn't automatically bring in additional information from LinkedIn.

Very happy to have the {M} logo instead if this is preferred.

**Comment by SimonLab** [comment]
New version: ![website-candidate](https://cloud.githubusercontent.com/assets/6057298/13753668/c9dd8690-ea0b-11e5-8c22-adb598ee27da.png)

**Comment by Adam-JF** [comment]
@SimonLab - Much better 👌

**Comment by SimonLab** [comment]
The image is saved in assets/img/website-candidate.png
