### ISSUE TITLE
Display website applications information

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#341]
As a user I want to see the applications data for a specific candidate

**Comment by iteles** [comment]
UI required from @Adam-JF on how to link the job to the candidate profile.

**Comment by SimonLab** [comment]
First version:
![applicationjob](https://cloud.githubusercontent.com/assets/6057298/13879159/d47339a6-ed0d-11e5-8b28-d72c349d5efe.png)

**Comment by iteles** [comment]
@Adam-JF Still need the updated UI from you on this please :relaxed:

**Comment by Adam-JF** [comment]
How do I test this?

**Comment by SimonLab** [comment]
@Adam-JF I'm doing some modification but I can already have a preview if you go to my profile on the app
