### ISSUE TITLE
Adding New Consultants (users) to the App

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#342]
As a Director of Global {M} I would like to be able to add new consultants (users) to the app easily and efficiently.

What are the steps I would need to take to add a new consultant email address to the app (eg. x@global-m.co.uk), allow them permission to access it including a download link for the scraping tool and include the functionality so that their initials are recorded next to the candidates they bring into the app.

**Comment by iteles** [comment]
Currently this needs to be done in the code and is part of our documentation. However, we can make the documentation a little more step-by-step for this particular purpose.

**Comment by heron2014** [comment]
Resolved by #422
