### ISSUE TITLE
What is the capacity of Google Drive

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#345]
If we are uploading the file to Google Drive we need to be sure that there will be always enough space. What is the current free space of the Google Drive?

**Comment by nelsonic** [comment]
Standard Google Apps for Work is **30GB** of storage: https://apps.google.com/pricing.html
If a standard CV is around 100kb (*its less I'm being conservative*)
Then you can fit **300,000 CVs** in 30GB of Google Drive Storage.
see: http://www.wolframalpha.com/input/?i=how+many+100kb+files+30gb

**Comment by SimonLab** [comment]
:+1:
It should be enough!
