### ISSUE TITLE
Add property jobs to the client structure

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#349]
We need to get a link between the clients and the jobs. So we need to add a property jobs to each client which is an array of ids of jobs
```
{
  name: "TheName"
  possibleNames: ["other name1", "other name2"],
  accountManager: idOfTheOwner,
  terms: "the terms agreed with the client",
  contactName: "The name of the client contact",
  contactEmail: "The email of the contact",
  contactPhone: "the phone number",
  createdAt: timestamp,
  active: true/false,
  **jobs: [id1, id2]**
}
```

**Comment by iteles** [comment]
Technical task?

**Comment by SimonLab** [comment]
Done with a helper.

**Comment by SimonLab** [comment]
Maybe the structure is not the right one:

Instead of having a list of IDs job inside the Client object:

```
{
  name: "TheName"
  possibleNames: ["other name1", "other name2"],
  accountManager: idOfTheOwner,
  terms: "the terms agreed with the client",
  contactName: "The name of the client contact",
  contactEmail: "The email of the contact",
  contactPhone: "the phone number",
  createdAt: timestamp,
  active: true/false,
  jobs: [id1, id2]
}
```

Should we only have the id of the Client in each Job object? Is there a good practice for this situation, @iteles @heron2014 @nelsonic do you have any recommendations?

**Comment by iteles** [comment]
@simonlab In this case it's a question of thinking about how we need to display the data and what the most efficient strategy is for retrieving it. Let's discuss in the morning.

**Comment by SimonLab** [comment]
We are keeping the current version: the list of the ids job in the client object
