### ISSUE TITLE
Add a property active/inactive to the job object

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#350]
When a job is "deleted" (or inactive) we need also to delete the id in the client.jobs value

**Comment by iteles** [comment]
Are you deleting the link or deactivating it? What happens if he job becomes active again (eg candidate backs out and the search has to start again)? How is the job linked back up to the client?

**Comment by SimonLab** [comment]
Yes I don't think we should delete the job, we should have an active, inactive property like with the client object. And when the website request the list of jobs we should only return the active jobs. Concerning the list of Ids in the client we are not going to delete them we will only display on the view of the client if the job is active or not.

**Comment by heron2014** [comment]
Break-down list for this feature:
* [ ] create a helper to insert new property {active: true } on jobs object - see [add_active_property_job.js](https://github.com/FAC-GM/data-copy/blob/6385f537512f7840c84938f0a15c6ef394a02d8b/helpers/add_active_property_job.js)
* [ ] - add active checkbox on create/edit jobs
* [ ] - separate active and non active jobs by filtering based on active property
* [ ] - from T request only response active jobs
* [ ] - UI

**Comment by heron2014** [comment]
Proposed basic UI:

![activejobs](https://cloud.githubusercontent.com/assets/8476884/14243081/5779776c-fa4b-11e5-8408-5712789c2d30.png)

@iteles @Adam-JF please let me know what you think?

**Comment by Adam-JF** [comment]
Perfect 👌

**Comment by heron2014** [comment]
This is how currently active/nonactive tabs looks like :
Active Jobs: 
![active-tab](https://cloud.githubusercontent.com/assets/8476884/14252041/7e8b918c-fa7d-11e5-9baf-611ea5f26512.png)

Non Active
![non-active](https://cloud.githubusercontent.com/assets/8476884/14252049/8a0c9ede-fa7d-11e5-84e4-977aba0f2ef0.png)

@iteles @Adam-JF what you guys think?

**Comment by nelsonic** [comment]
https://www.google.co.uk/search?q=nonactive

**Comment by heron2014** [comment]
@Adam-JF can you please confirm name for the tabs: Active Jobs, Inactive Jobs?

**Comment by Adam-JF** [comment]
Works great.
