### ISSUE TITLE
Add logo field for client

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#352]
- [x] Update the current client objects with the new property **logoUrl**
- [x] Add a text field on the client form to add a logo. The field will contain the url of the logo 
- [x]  Save the new data logoUrl into Elasticsaerch
- [x] Display the image on the client page and list of clients if the logoUrl is not empty

**Comment by SimonLab** [comment]
@Adam-JF do you want a default image if the url of the logo is not defined yet? If yes which image/logo?

**Comment by Adam-JF** [comment]
Working great - did some tests this morning, changed a few logos - all seems to be working well.

**Comment by iteles** [comment]
@Adam-JF Feel free to close this issue when you're satisfied it's working :smile:

**Comment by SimonLab** [comment]
@Adam-JF I don't see any new logo on the list, did you put back the default images?

**Comment by Adam-JF** [comment]
Tested - working great.

![screen shot 2016-03-24 at 15 17 38](https://cloud.githubusercontent.com/assets/15364186/14021513/b36c876a-f1d3-11e5-9414-35f0fc0f6a78.png)

**Comment by SimonLab** [comment]
:+1:
