### ISSUE TITLE
Client Employee - BUG

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#353]
I don't wish to cause alarm but I just added onefinestay as a client on the app and when I returned to the homepage every profile is now listed as a 'Client Employee'...

Help.

**Comment by heron2014** [comment]
thanks @Adam-JF. We are on it.

**Comment by SimonLab** [comment]
@Adam-JF we find the solution the new version of the app will be online as soon as possible

**Comment by Adam-JF** [comment]
@SimonLab @heron2014 Great work - thanks guys.

**Comment by SimonLab** [comment]
@Adam-JF I just reset the database for the clients to the previous state so you shouldn't see anymore all the contacts as "company clients". However @nelsonic is going to review the patch for the bug and publish the new version vert soon but during this time could you avoid updating/creating new clients as it going to recreate the bug. I let you know when the new version is online. Thanks

**Comment by nelsonic** [comment]
Merged.

**Comment by Adam-JF** [comment]
Dreadful timing that I just updated all of the client owners then 👀 

Haha - woops. I will hold fire on doing it again until you let me know.

**Comment by SimonLab** [comment]
@Adam-JF it should be ok now, sorry for your updates. Can you please check when you update just one client to see if everything is ok. If it's fine you can update the rest of the list

**Comment by Adam-JF** [comment]
Re-rested this: 
- Changed a client owner 
- Re-uploaded 'onefinestay' as a client

No longer had the issue.

Thank you for fixing this so promptly - will continue to test the client features.
