### ISSUE TITLE
Display application on specific job

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#359]
The skill set is not defined when a candidate apply for a specific job so we shouldn't display it. We also need to display the job title with a link to it

![specificjob](https://cloud.githubusercontent.com/assets/6057298/14015689/d71b4960-f1b2-11e5-9dd7-e006945f374e.png)

```
{"timestamp":1458817413754,"jobID":"166","comments":"Apply for a job"}],"cvDocumentLink":"https://drive.google.com/file...
```

**Comment by iteles** [comment]
Agreed!

**Comment by SimonLab** [comment]
resolve with #361 see also #341
