### ISSUE TITLE
Update skills selector

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#36]
The skills will be store as an object an not an array of string.
```javascript
profile.skills = ['javascript', 'redis'];

// will be

profile.skilss = [{endorsment: 9, skillName: 'javascript'}, {endorsment: 45, skillName: 'redis'}] 
```

**Comment by nelsonic** [comment]
@simon any reason you can't store these as a *simpler* object?
```js
profile.skills = { "javascript" : 9, "redis" : 13 };
```
Or are you planning on searching **ElasticSearch** by the `skillName` or `level` ?

**Comment by SimonLab** [comment]
Agree that it is an easier way to store the skills and I think we will search by the skillName

**Comment by nelsonic** [comment]
@SimonLab It makes sense to have `explicit` labels for the data inside the object if you intend to make it ***searchable***...
```js
profile.skills = [{ "level" : 9, "skill" : 'javascript' }, { "level": 45, "skill": 'redis'} ] 
```
Or if you want to conserve a bit of data in memory:
```js
profile.skills = [{ "x" : 9, "s" : 'javascript' }, { "x": 45, "s": 'redis'} ] ; 
// why "x" ? ... https://www.ted.com/talks/terry_moore_why_is_x_the_unknown
```

**Comment by SimonLab** [comment]
The database has been re-indexed with the format:
```
profile.skills = [{ "level" : 9, "skill" : 'javascript' }, { "level": 45, "skill": 'redis'} ] 
```

**Comment by nelsonic** [comment]
Nice one. :+1:
