### ISSUE TITLE
Delete Duplicate Clients

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#377]
We have some duplicates in the client list we would like deleting.

- [x] VPAR Live Golf Scoring
- [x] YouSoft Ltd
- [x] Yousoft.com
- [x] WeSwap.com
- [x] Borderguru
- [x] Founders and Coders
- [x] Judo Payments
- [x] TestCompanyA
- [x] TestCompanyB

**Comment by SimonLab** [comment]
@Adam-JF I'm not sure the key contact information for VPAR are correct, they are the same as in YouSoft

**Comment by Adam-JF** [comment]
They are correct - the contact is the same for both companies.

**Comment by SimonLab** [comment]
:+1:
