### ISSUE TITLE
new database structure

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#39]
The Elastic Search data structure needs to change from an `array`: 
```json
skills:["JavaScript", "C++" "Python","etc"] 
```
to an `object` with properties:
```js
{
  "skills": {
    "level": 10,
    "skill": "JavaScript"  
  }
}
```

We need to reindex the data, and need to find the best way to apply it to our actual data

**Comment by nelsonic** [comment]
Hi @SimonLab, the ***only*** way we can do this is by updating the records *as* we get the better data (i.e. when people visit First-degree-connection Profiles in a browser with the extension...)
What that means is that the app needs to display ***both*** the "*basic*" skills information (***without skill level***) ***and*** "*enhanced*" version with the data parsed by the extension.

**Comment by SimonLab** [comment]
Elasticsearch don't let you update the data if the type of this data differ from the other documents.
The way we resolve this problem is by reindexing our current data (with a default level: 0). We will be then able to update the skill with the new values.
https://www.elastic.co/blog/changing-mapping-with-zero-downtime

**Comment by nelsonic** [comment]
So are you going to set all the existing records to have a skill level `0` ?

**Comment by SimonLab** [comment]
In the database yes. In the front end if the level is 0 we only display the name of the skill (as it is at the moment). As soon as we have more information about the skills we will then be able to display the level.

**Comment by nelsonic** [comment]
Sounds good. :+1:

**Comment by SimonLab** [comment]
The data structure has been change and re-indexed (array to a nested object) and the UI updated with the [PR50](https://github.com/FAC-GM/app/pull/50) and the [skill helper](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/views/helpers/skillsHelper.js#L1-L8)

**Comment by nelsonic** [comment]
@SimonLab we need to *document* this structure in ***detail*** in a Markdown Document. (e.g: `DATA.md` ) where the schema is explained and a *sample* record is stored. Would you mind creating a **Tech Task** for this?

**Comment by SimonLab** [comment]
You can find the task here: [task 73](https://github.com/FAC-GM/app/issues/73)
