### ISSUE TITLE
Job Posting

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#390]
The following job https://global-m.herokuapp.com/jobs/AVPLzX-Y1ztZUbCCBnqp - is listed as having 75,000 euros as the starting salary on the job creation, however, it is currently being displayed on the website as being 75,000/day - http://www.global-m.co.uk/jobs/?id=AVPLzX-Y1ztZUbCCBnqp

It has been selected as a permanent position and the entries are correct.

Why is this happening?

**Comment by iteles** [comment]
We think we have understood what's causing the issue on our side (around 'Pay rate') being an empty string, but can't test this due to the GM website malfunction. We are waiting for TOAD to deal with this before we can test our proposed solution.

**Comment by Adam-JF** [comment]
An example of a job posting that is displaying correctly - 

Advertising Sales Manager - EMEA
https://global-m.herokuapp.com/jobs/256
http://www.global-m.co.uk/jobs/?id=256

**Comment by heron2014** [comment]
Would it be possible to confirm with Toad , what properties from json object they populate in this field: 

![populate-data-toad](https://cloud.githubusercontent.com/assets/8476884/14315057/01654014-fbf3-11e5-9bd5-9a903511afa7.png)

- we want to make sure that this property is related to payRate as our first assumption is.

**Comment by Adam-JF** [comment]
Having spoken to Henry from TOAD the issue is the addition of a comma in the salary value.

The salary must only be figures, no special characters.

75000 NOT 75,000

**Comment by heron2014** [comment]
thanks @Adam-JF

**Comment by iteles** [comment]
@Adam-JF I created a linked issue to add validation so I think we can close this one for now if you're happy it's resolved.
