### ISSUE TITLE
Small display issue with jobs list 

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#392]
Looks like PR #391 inserted a small CSS bug where the intials overlap the information on the job list view:
<img width="1039" alt="screen shot 2016-04-04 at 22 53 11" src="https://cloud.githubusercontent.com/assets/4185328/14264882/415c0428-fab8-11e5-8fef-12443ddaf397.png">

**Comment by heron2014** [comment]
ohh yeah! thanks @iteles.

**Comment by heron2014** [comment]
Resolved by this [PR - 393]( #393)
