### ISSUE TITLE
CV Upload for non-website profiles

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#398]
We would like the ability to add CVs to the profiles that already exist in the app.

Considering this functionality is already live for the ones coming from the website would this be hard to implement?

Linked to #330

**Comment by SimonLab** [comment]
@Adam-JF you can now test this feature on the staging area.

**Comment by Adam-JF** [comment]
Tested browsing for new file before uploading previous one.
Tested upload with file types:
- [ ] .rtf 
- [ ] .pdf 
- [ ] .docx
- [ ] .doc
- [ ] .txt
- [ ] .png

Working great. Awesome work guys.

**Comment by iteles** [comment]
Thanks @Adam-JF ! Please close the issue if you're happy with it :)
