### ISSUE TITLE
Removing ability to mass email candidates if they have already been emailed within the last month

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#401]
As a user I don't want to accidentally span people if we already sent an email within last month

**Comment by heron2014** [comment]
First approach is to filtered emails array to only return emails which timestamp is larger than last 30 days, I was testing in the repl.it [repl](https://repl.it/CDac)

**Comment by Adam-JF** [comment]
This is no longer in scope for Sprint 8.

**Comment by iteles** [comment]
@Adam-JF As we discussed, we are already at the end of sprint 8 and time has already been spent on this feature - it's one code review away from being ready to go. I'm happy to have a call with Nick about this tomorrow if needs be.
