### ISSUE TITLE
Add Elizabeth to the app

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#406]
Elizabeth has installed the extension and now she would like full access to the application.

Her email address is: ask @Adam-JF

**Comment by SimonLab** [comment]
Hi @Adam-JF , Elizabeth should be able to access the app now.

**Comment by heron2014** [comment]
Looks like Elizabeth hasn't yet logged in to the app. To be able to add her to database we need Elizabeth to login to the app. This way we can get her id and add her to database so she can fully use the application with the extension.

@Adam-JF Do you know if Elizabeth has used the platform?
