### ISSUE TITLE
Website Image Text 3: Issue

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#418]
The website currently displays the 'Image Text 3:' inputs on job postings in a different size and format compared to Image Text 1 and 2.

Is this a TOAD problem or an app problem? Do we just need to change the formatting defaults for that text input?

![screen shot 2016-04-20 at 14 52 43](https://cloud.githubusercontent.com/assets/15364186/14677002/a664d86c-0707-11e6-8c8a-eabba24fd26e.png)

**Comment by heron2014** [comment]
From inspecting element on the website , it looks like the third text is a paragraph tag as opposed to the others - span tag which has some styling. We think it is worth to ask Toad to possibly change the way they render the third text to apply the same html tag/styling to all of the image texts.

**Comment by iteles** [comment]
It's definitely a TOAD thing. I asked about that and I was told that it was done on purpose as image text 3 is supposed to be a larger paragraph and therefore should be in smaller text.
