### ISSUE TITLE
Add users to the platform

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#419]
As a admin/manager of the application I would like to add new users as well as have possibility to inactive the users who are no longer in the company. I also want to be able to give permissions to the relevant users. (admin, recruiter rights)

**Comment by heron2014** [comment]
Steps: 
- [ ] restructure database

At the moment we have two tables: users and owners. We need to merge these tables into one and check relevant features related to these tables.

Current db structure:

- **owners:** {"firstName": "Anita", "lastName": "Cz", "id": 1, "name": "Anita Cz", "email": "a@gm.com"}
- **users**: {"names": {"firstname": "Anita", "lastname": "Cz", "fullname": "Anita Cz", "linkedinName": "Anita"}, "email": "a@gm.com", "phones": {"office": "0202", "mobile": "0709"}, "role": "Director", "linkedin": "https://url" }

- [ ] make a list of where we using these two tables data
- [ ] create a new structure with new properties: inactive, active, permissions: admin, recruiters
- [ ] update new table into relevant features
- [ ] update the tests with the new structure
- [ ] create new endpoint to create new users accessible from dashboard (Admin)
- [ ] replace env file with the list of emails to the new solution which could be: check if email exist in the new database structure and allow the access to the application
- [ ] UI for creating new users with the permissions
 - form fields: 
  - firstname, lastname, fullname, linkedinName, phones:mobile, office, role, active, linkedin url
  - as a default the users will have a recruiters rights, unless the managers changes to admin rights

**Comment by heron2014** [comment]
List of plugins which uses env file  
```
MAP_ID_USER = {"goggle id": "firstname"}
EMAILS_ALLOWED="string with emails seperated by comma" - we use this to authenticate
```
First step: 
authentication with Google  [L3](https://github.com/FAC-GM/app/blob/master/lib/google_oauth_handler.js#L3)

EMAILS_ALLOWED we use to to save user to redis [google_oauth_handler](https://github.com/FAC-GM/app/blob/master/lib/google_oauth_handler.js)

analytics/ query -[L67](https://github.com/FAC-GM/app/blob/master/lib/query.js#L67)

**Comment by heron2014** [comment]
Replaced MAP_ID_USER in emails.js [L22](https://github.com/FAC-GM/app/blob/master/lib/handlers/email/get_email.js#L22) also merged userProfile and userObject into one object 'user' , and replaced MAP_ID_USER in [L42](https://github.com/FAC-GM/app/blob/master/lib/handlers/email/post_sendmail.js#L42), updated the signature based on new structure object 'user' in generate_signature [L33-L39](https://github.com/FAC-GM/app/blob/master/lib/helpers/generate_signature.js#L33-L39)

**Comment by heron2014** [comment]
Restructured the user object in 'owners/list' from new user-table to be exactly as we send to Toad.

**Comment by heron2014** [comment]
Replaced fully MAP_ID_USER from env file, owners and users database by new database structure.

**Comment by Adam-JF** [comment]
Works great.
