### ISSUE TITLE
Restructed Notes Feature

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#420]
Currently notes feature is tracking  status of the particular candidate. The new notes feature will only track who posted additional notes. On top of that the consultant will be able to edit default information about the candidate such as: 

- salary (current)
- salary (expected)
- notice period
- interested in locations

Basic wireframes for this feature: 

![notes](https://cloud.githubusercontent.com/assets/8476884/14915588/1a9507a6-0e0c-11e6-8b94-bf77038361f0.png)

**Comment by heron2014** [comment]
Steps: 
- create a new plugin for **info** (we can call it something else). This property represents the default information about the candidate, example: 

```
info: {scurrent: "", sexpected: "", locations: [], notice: ""}
```
 - info plugin has two endpoints: 
 
```

  {
      method: 'GET',
      path: '/jobs/edit/{id}',
      config: {
        description: ''return an edit info form',
        auth: {
          mode: 'try',
          strategy: 'jwt'
        },
        handler: getInfoForm
      }
    },

    {
      method: 'POST',
      path: '/info/save',
      config: {
        description: 'update/save the candidate info ',
        auth: {
          mode: 'try',
          strategy: 'jwt'
        },
        handler: postSave
      }
    }
```


- add info property into all candidates as an empty object  (create helper for it in our helpers repo) 
- in getInfoForm handler call new helper **getInfo**
- create getInfo helper (example): 

```js
 module.exports = function (id, callback) {
  client.get({
    index: index,
    type: type,
    id: id,
    _source: ['info']
 },function (err, info) {
   //save id into info
  return callback(err, info);
 });

```

- create a form in html , for example:

```js
<form action="info/save" method="POST"
  <input type="text" name="scurrent" value="{{info.scurrent}}"> //scurrent - salary current
  <input type="hidden" name="id" value="{{info.id}}">
</form>
```
- in postSave handler create new helper updateInfo or saveInfo
  - create a object info
  example: 

  ```js
  var info = {};
  info.scurrent = request.payload.scurrent;
  ...

  ```
   call helper function saveInfo (id, info, callback)

 - we don't need to save all the info objects into array, whenever one info is already existing we can replace this one with the new one.
- in elasticsearch we can only get info and index info, instead using update? (to be confirm)

example: 
```
module.exports = function (id, info, callback) {
 client.get({
  index: index,
  type: type,
  id: request.payload.id
}, function (err, res) {
   
  var currentInfo = info;
  
   es.index({
     index: index,
     type: type,
     id: request.payload.id,
     body: currentInfo
 }, function (error, response) {  
    
     return callback(err, response)
  }
})
```

Our handler info/save redirect to candidate/ + request.params.id

<hr />

The additional notes logic will be very similar what we already have in [notes.js](https://github.com/FAC-GM/app/blob/master/lib/notes.js).

Currently our notes structure is:

```
  "notes":[{"createdAt":"02.02.2016", "author": "Simon", "id": "12", "notes":"", "status": "phone-screen", "company": "FAC"}],
```

We don't need anymore "status" and "company " - this will be replaced by [issue 421](https://github.com/FAC-GM/app/issues/421)

@SimonLab can you have a look at these steps, thanks :+1:

**Comment by SimonLab** [comment]
Just to be sure, the info structure needs to be added to the candidate objects, it is not an other type in elasticsearch. When we create/update the info structure we are going to update the property info of the candidate with the new value so we are going to use "client.update" but just on the property info. I'm not sure we should redirect to the candidate, it will reload the page and it might looks a bit strange. Instead we can have the browser sending an ajax post request to "info/save" and depending of the response (it can be whatever we want, 200 if it as update or 500 if there is an error for example) we can change the DOM structure of the page to display the new info data.
The main steps are ok we just need to remember about the interface and the ajax requests.

**Comment by heron2014** [comment]
Currently this is our basic UI:

![default-info](https://cloud.githubusercontent.com/assets/8476884/14984594/72ec972a-113b-11e6-8a15-565629edfccc.png)

On click Edit - form is displaying: 

![info-form](https://cloud.githubusercontent.com/assets/8476884/14984648/ae13588e-113b-11e6-91a1-c6e3194c83ab.png)

**Comment by heron2014** [comment]
The steps for this feature are slightly different than above comment. The way we do now is using Ajax call - [L84-L118](https://github.com/FAC-GM/app/blob/info-candidate/assets/js/candidate_view.js#L84-L118)

There is only one endpoint in [info.js](https://github.com/FAC-GM/app/blob/info-candidate/lib/info.js) which is **/info/save** which saves or update info property on candidate object in ES.

IF we have some error while saving/updating info we reply code: 500 otherwise code: 200 and info object [L13](https://github.com/FAC-GM/app/blob/info-candidate/lib/handlers/info/post_save.js#L13)

**Comment by heron2014** [comment]
@Adam-JF you can now test the first part of the notes feature [see](https://github.com/FAC-GM/app/issues/420#issuecomment-216528332) on our testing domain.  Looking forward to your feedback, thanks :+1:

**Comment by Adam-JF** [comment]
@heron2014 Works perfectly.

**Comment by heron2014** [comment]
Thanks @Adam-JF

**Comment by Adam-JF** [comment]
@heron2014 Oops, sorry, there was one more thing - i've updated my comment accordingly.

**Comment by heron2014** [comment]
@Adam-JF please test it again :+1:

**Comment by Adam-JF** [comment]
Same issue remains sorry. The info is being removed.

Did it with Mohammad Adil's profile - https://globalm-test.herokuapp.com/candidate/AVSFb_MkWMr7QbX1Hx-4

https://www.linkedin.com/in/adilchang

**Comment by heron2014** [comment]
@Adam-JF can you please test this feature by changing url in the extension into the test domain one. IF you need any help, let us know.

**Comment by Adam-JF** [comment]
All fixed - working great.

Well done guys.

**Comment by heron2014** [comment]
Thanks @Adam-JF

**Comment by Adam-JF** [comment]
Will these fields be searchable through Kibana?

For instance, if I input a salary onto a profile, will there be a field for this displayed with the value on Kibana?

**Comment by Adam-JF** [comment]
Also, could we input an additional info field which selects whether or not they are contract or permanent?

**Comment by SimonLab** [comment]
@Adam-JF I think you will be able to access the fields with Kibana. For the additional field what kind of field do you think, checkbox with a tag permanent or a dropdown with the two options? Also I think some candidate might be happy with contract and permanent jobs. Another solution is to precise this choice in the section further info.
