### ISSUE TITLE
REstructured dashboard 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#423]
As a consultant I would like to see all my jobs/clients/candidates and all relevant information to my created jobs and clients.

![dashboard-new](https://cloud.githubusercontent.com/assets/8476884/14918929/371877e8-0e1e-11e6-8945-e20c1b4b2c55.png)

@Adam-JF is this dashboard correct?

**Comment by Adam-JF** [comment]
@heron2014 Looks great guys

**Comment by heron2014** [comment]
@iteles what do you think about the following: 

- clients (possiblity to have lots of clients - for example Manager, this means this horizontal scrolling can be really long, we could fit clients in the next row but this will clutter the view - maybe one of the solution would be regular dropdown? )
- we have now 10 stages instead of 4 as shown in above wireframes
 - which means the user won't be able to see all the stages without need to use horizontal scroll
- on each stages could be multiple candidates 
 - we could possibly fit 2 candidates per stage per row, if more candidates per stage they will be placed in next row
- each job (row) would have horizontal scroll

I made simplified version what potentially this could look like according to the above wireframes:

![new-dash](https://cloud.githubusercontent.com/assets/8476884/15094887/fd6e29d8-14a9-11e6-9eb4-96813117c141.png)

The orange line is what the user would see on avarage screen - 4-5 stages, the rest is on scroll

**Comment by iteles** [comment]
We're trying to put far too much into one screen, but until we show the team that it's not particularly reasonable or useful to cram all this information into a single view, there's not much we can do!

I would suggest that we should have *far fewer* stages (10 stages is **not** an MVP, it's pandering to everyone's needs) and then filter by client for a full view and by jobs with a drop down. The aggregate (mangers') dashboards are going to be unusable in the current design.

**Comment by Adam-JF** [comment]
@iteles For now would it be better to only display stages if there is a candidate at said stage?

At least until we have jobs with custom stage lengths. 

I can say with a degree of certainty that there will never be an interview process which is as long as 10 stages. The maximum would probably be 5. I put the full list of 10 possibilities because that covers more or less every variant.

**Comment by SimonLab** [comment]
@Adam-JF the new version of the dashboard is now online

**Comment by Adam-JF** [comment]
Working great.
