### ISSUE TITLE
Email Notification Icon is Innacurate

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#426]
We need to investigate whether or not the sent email notification icon is working as it should.

Some consultants believe that it is not completely accurate and as a result people are being contacted multiple times when they should not be.

The biggest offender is the search for people with the skill 'Python'

**Comment by iteles** [comment]
@Adam-JF If you can find us one or two concrete examples of this, that would be great. Otherwise we're searching for a bit of a needle in a haystack!

Thanks!
