### ISSUE TITLE
Find better icons from font-awesome

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#43]
As a user I want my sections on profile page to have self-explanatory icons so I can quickly navigate/ find specific part and I don't need spend some time to read the label.

Example of current experience icon:
![icon](https://cloud.githubusercontent.com/assets/8476884/10970867/20b0c2ba-83c9-11e5-9a9f-06dace51c998.png)

**Comment by iteles** [comment]
@heron2014 We need to frame this as a _user story_ and explain the benefit derived from spending time on this (_thank you!_)

**Comment by heron2014** [comment]
As a user I want my sections on profile page to have self-explanatory icons so I can quickly navigate/ find specific part and I don't need spend some time to read the label. 

@iteles Do you want me to create a new issue with this user story or leave it in here?

**Comment by iteles** [comment]
@heron2014 I would suggest we alter the original comment to re-write it as a user story!

**Comment by Adam-JF** [comment]
This will be part of a design overhaul we will discuss later down the line.

**Comment by heron2014** [comment]
Resolved by the new design.
