### ISSUE TITLE
Client Login

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#433]
As directors of Global {M} we would like a way for our clients to login to a separate part of the herokuapp where they can review the recruitment activity specifically associated with their vacancies.

**Comment by iteles** [comment]
- How separate is this to the view that Global {M} employees see? 
- How do we restrict access to this area (i.e. How do we identify a person as belonging to a specific company and ensure not just anyone can register?)
  - User created by GM 
  - GM sends email to client with username and password
  - This implies a way to change a password - GM will need to do this manually for now
  - When client logs in they see the client page
+ We'll need a separate login system to the one we have now

**Comment by Adam-JF** [comment]
Clients will only be able to access the client page with their relevant job postings and will only be allowed access to the candidate profiles associated with their vacancies. However, they will not be able to view the notes, contact details, or info sections of those profiles.

We will have pre-approved email addresses which are registered under the Global {M} or that specific companies domain - preferably using that companies email address because we pay per Global {M} address so it's not scalable to create a custom address each time.

**Comment by heron2014** [comment]
@Adam-JF Do clients are able to logout ? We don't think it is a high priority, but what do you think?

**Comment by Adam-JF** [comment]
@heron2014 No, I agree it's not high priority.

**Comment by heron2014** [comment]
General steps: 
- Differentiate access to the application as a gm user and client 
- Create an endpoint where the client can enter its email and password 
- Find if the email exists in our database and validate the password (decrypte) 
- Redirect to the dashboard of the client if login successful or login page if not successful
- Update current endpoints with the right permission 
- UI/UX

**Comment by SimonLab** [comment]
We are already using hapi-auth-jwt2 for the login of the users (via Google oauth2):
 - register the [hapi-auth-jwt2](https://github.com/FAC-GM/app/blob/4ba1c7606f806266dcc8f7fddfaebcd87ade4bb0/lib/index.js#L57) scheme on the server
- Create a [jwt startegy](https://github.com/FAC-GM/app/blob/login-client/lib/authentication.js)
- Use this strategy on most of the routes for example on [home](https://github.com/FAC-GM/app/blob/4ba1c7606f806266dcc8f7fddfaebcd87ade4bb0/lib/home.js#L20)
- The validate function flow: decode token (cookie) -> get from redis the object match the id found from the decoded token -> check the property validate of this object

Now we want to reuse almost the same strategy for the login client. Only the validate function need to change:
- Create a [jwtclient strategy](https://github.com/FAC-GM/app/blob/login-client/lib/client_authentication.js)
- use this new strategy on the [client-dashboard route](https://github.com/FAC-GM/app/blob/4ba1c7606f806266dcc8f7fddfaebcd87ade4bb0/lib/client_dashboard.js#L13)
- Try to use the validate function to check another property of the object we retreive from Redis.

Our problem is that the validate function of the jwtclient is not called. Is it possible to use mutliple strategy based on the scheme hapi-auth-jwt2?

**Comment by SimonLab** [comment]
Creating two different strategies based on the same scheme seems to produce some conflicts. Instead of creating two strategies we can distinguish our cases on the validate function.

**Comment by nelsonic** [comment]
@SimonLab is this so people can login using username/email & password instead of Google Auth?

**Comment by SimonLab** [comment]
Yes it's for login with email/password. We manage to create two strategies based on hapi-auth-jwt2. Our error was from our token which was undefined, we just needed to precise the cookieKey property.

**Comment by Adam-JF** [comment]
UI

This is the bare bones version of the client login.

![screen shot 2016-05-31 at 15 36 13](https://cloud.githubusercontent.com/assets/15364186/15678256/87fa4480-2745-11e6-88d2-aff973fe37a4.png)


This however, is the kind of aesthetic I'd like to recreate if possible.

![21df4887f2938164c3e7d7c853bdfc44](https://cloud.githubusercontent.com/assets/15364186/15678253/850e3236-2745-11e6-9f7d-555bad61b526.jpg)

**Comment by iteles** [comment]
A few questions:
+ Could you please provide the colour (hex) codes for the colours you've used?
+ If this is a squirrel HR product, shouldn't it be branded as such rather than Global {M}
+ I would advise that we keep this page very clean/without a background colour, otherwise there will be _big_ clashes with the colour scheme when they get to their dashboard
+ A forgotten password link was not in our original spec and I'll let @SimonLab and @heron2014 if it requires additional work (we need to attach the email to the request so we need to have validation to make sure the email address field has been filled in and if not, display an error message asking for it to be filled in, but I have a few comments on this:
  + The 'forgotten password' method you're suggesting is not a familiar user pattern
  + What you're using here is a user pattern for a password 'hint' or something users click on to help them understand what a field is for - this means people may not think to click there if they've forgotten their password
  + I would suggest a small link that read 'Forgotten password?' and a message after it is clicked that say 'thank you, an email has been sent to the administrator and they will send you your new password'
![example-forgotten-password](http://turbo.designwoop.com/uploads/2014/11/29-clean-flat-login-form.jpg)

**Comment by Adam-JF** [comment]
We don't have a Squirrel HR logo yet so we cannot brand it as such. Global {M} is what we're working under for now.

With regards to the colour, a translucent background in any colour variation is fine, it doesn't have to be purple. An off-white or grey would suffice.

The forgotten password button isn't necessary at this stage. 

However, will there be any kind of notification from the app though that a client is unable to login? We cannot always rely on people emailing us to let us know that they're having trouble - they may just not use it and that would be awkward when we're asking for their feedback (irregardless of whether it's their fault or not).

**Comment by SimonLab** [comment]
@Adam-JF you can test the login page on the staging area now.

The dashboard is not done yet but you can try to access the "test" dasboard by going to /client-dashboard (try first without being logged and then after the login provess)

you can access the login page for the client on /client-login

Let us know your feedbacks thanks.

**Comment by Adam-JF** [comment]
- [ ] I was unable to access the dashboard if I hadn't logged in. (as expected)
- [ ] Attempting to access the dashboard without logging in meant I was redirected to login page. (as expected)
- [ ] After logging in I was able to reach the dashboard page. (as expected)
- [ ] I de-authorised my user and was then unable to login to the app (as expected) - as an addition, if reauthorised a prompt similar to the incorrect password one should appear saying 'User not authorised' - gives feedback to a user as to why they're unable to proceed.
- [ ] I typed in my password incorrectly and received a prompt telling me my email or password were incorrect. (as expected)
- [ ] Re-authorised my account and was able to login to the app. (as expected)

Great work guys.

**Comment by heron2014** [comment]
Thanks @Adam-JF for your feedback.

**Comment by iteles** [comment]
@Adam-JF On this point:
> As an addition, if reauthorised a prompt similar to the incorrect password one should appear saying 'User not authorised' - gives feedback to a user as to why they're unable to proceed.

This is not a common use pattern and not really something the user would expect.
If the password or email are typed in incorrectly, there should be an error message saying something like 'username or password is not recognised, please try again or email the administrator' (I wouldn't specify which for security purposes. Does this not cover the same use case?

**Comment by Adam-JF** [comment]
![client login](https://cloud.githubusercontent.com/assets/15364186/15962310/23c70b28-2f02-11e6-8cad-930dc69f0c0d.png)

**Comment by heron2014** [comment]
@Adam-JF Could you send over the email the logo ?

**Comment by heron2014** [comment]
Resolved by #466
