### ISSUE TITLE
Client Dashboard - Candidates

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#434]
As directors of Global {M} we would like our clients to have the ability to monitor the candidates they have in process for their vacancies and be able to progress them through a hiring process using 'drag and drop functionality' between stages.

**Comment by iteles** [comment]
+ Does each client have completely different stages?
  + Should a client dictate the stages?
  + If a client want to eliminate a stage, what do we do with candidates who are already in that stage?
  + This will have a deep impact on the status feature in the individual candidate page
  + Does pressing the 'x' on the candidates mean that they get a status of rejected?

+ All stages will need to be visible
+ Drag and drop will have to update throughout the app - complex testing required

**Comment by Adam-JF** [comment]
- Each client should have the capacity to select the stages from the pre-determined list from issue #421 
- The client should be unable to delete a stage with candidates within it. They must choose to either progress the candidates from that stage or reject them. Only an empty stage may be removed.
- Clients should not have the capacity to delete people from their dashboard, only to progress or reject them - a rejected status will remove them from the dashboard but they should **not** do this using an 'X' button.
- The simplicity of a drag and drop feature from a user perspective makes it highly valuable and it is certainly something we will want to include in the future throughout the app. Would integrating this functionality now make it easier to do so in the future or will it always take a similar amount of time to get up and running?


If there is any benefit to adding it sooner rather than later then it may be best to proceed now during this Sprint (naturally this is dependent on Nick and Alex's feelings on it)

**Comment by SimonLab** [comment]
@Adam-JF When a client reject a candidate do we need to display in a separate section the rejected candidate?

**Comment by iteles** [comment]
@Adam-JF Could you please remember to also propose a UI for if a single user is moved from stage to stage by arrows vs drags and drop, so we can estimate this as well?

Thanks
Ines

**Comment by SimonLab** [comment]
To  apply the action on a candidate (reject, next stage), I'm thinking of using some ajax call and update the DOM candidate depending on the response of the ajax call. I think it can enhance the experience of the clients. @iteles @nelsonic do you think it's a good idea or should we keep with a simple form submission and refresh the dashboard page of the client?

**Comment by iteles** [comment]
@SimonLab @heron2014 This is quite a big topic and the last two comments here might be better off in a linked technical issue rather than the main user issue 😊

**Comment by heron2014** [comment]
structure of the new object to be able to display information on the view: 

```js
{"idJob": {title: "title", stages: {"idStage": {name: "name", candidates: {"idCandidate": {name: "name", next: {"idCanididate": "123", "idJob": "123", "idClient": "22", "idCurrentStage": "3", "newStage": "2"}}}}}}}

````

**Comment by heron2014** [comment]
Drag and drop functionality has been replace by button action - next.
