### ISSUE TITLE
Custom Interview Stages

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#437]
As director's of Global {M} we would like our client's to have the capacity to create their own hiring process by selecting the relevant steps they want for each vacancy.

For instance - Vacancy 1 = Phone Screen, Face to Face, Technical Test, References Requested, Placement.

Vacancy 2 = Phone Screen, Face to Face, CTO Meeting, Placement.

**Comment by iteles** [comment]
If a client can create these, what happens if they delete/change a stage which already has a candidate assigned to it?

**Comment by Adam-JF** [comment]
Answered in #434 

> Each client should only have the capacity to select the stages from the pre-determined list from issue #421
The client should be unable to delete a stage with candidates within it. They must choose to either progress the candidates from that stage or reject them. Only an empty stage may be removed.

**Comment by SimonLab** [comment]
# Steps

The client can select the stages from a pre selected list. The client can change the order of the stages. To display the stages in order and to know what is a next stage for a candidate we need to add a new property to the stage objects:

- [ ] Add the "order" property to the stages. The order value must be unique

By default all the stages are linked to a new job:

- [ ] Add a property stagesAllowed which is an array of stages Ids. The value of this property **must not be analysed** in Elasticsearch to keep the orignal value of the id

- [ ] Create the endpoint POST /job/stages which display the stages for a specific job

- [ ] Create the endpoint POST POST /job/stages/edit which update the stages allowed for a job

**Comment by heron2014** [comment]
@Adam-JF Can client unselect all the stages for the particular job which would mean that the job doesn't have any stages?

**Comment by heron2014** [comment]
This has been resolved by #479 & #496
