### ISSUE TITLE
Download Emails for CM

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#444]
As a member of the marketing team of Global {M} I would like a download all of the email addresses within the app marked against their Names, Job Titles (Headline) and Locations to update our Campaign Monitor lists.

Would it be possible to get a big Excel file of these?

**Comment by SimonLab** [comment]
@Adam-JF I don't remember as I haven't use a lot Kibina but does it allow to select the emails and then copy them (or download) in an csv file?

**Comment by Adam-JF** [comment]
@SimonLab I can copy 1000 results at a time from Kibana - however, i'm proposing a mass download of every email address in the app (circa 50,000) - ultimately this loops back to issue #403 where I need a way of going through Kibana and extracting more information at a time - I just wondered if you can download the details of the people in the app now from the back-end and then we'll manipulate the data accordingly?

**Comment by SimonLab** [comment]
@Adam-JF let us know if you need a new update of the list

**Comment by Adam-JF** [comment]
How long does the process take to replicate now? (for future reference)

**Comment by SimonLab** [comment]
It should take around 30 mn to run the script again, we need a bit of time to configure the script and to verify the data the script receive
