### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#445]
The application seems to use all the memory:

![memoryusage1](https://cloud.githubusercontent.com/assets/6057298/15324621/1a5f663c-1c3f-11e6-93e1-ef975a5a4050.png)

![memoryusage2](https://cloud.githubusercontent.com/assets/6057298/15324624/1e1029a6-1c3f-11e6-9ff8-31e82ba020bb.png)

I can see two reasons this might happend:
- People are using more and more the application and there is not enough memory -> Should we upgrade the dyno to get more memory

- There is a leak of memory in the application

@nelsonic from the screenshot what is your first thought?

**Comment by nelsonic** [comment]
@SimonLab this *looks* like a leak. you can *temporarily* increase the size of the dyno.
but to *diagnose* the issue you will probably need to use New Relic ... https://docs.newrelic.com/docs/accounts-partnerships/partnerships/heroku-new-relic/heroku-install-new-relic-add-on (*14-day free trial*)

**Comment by nelsonic** [comment]
@SimonLab please confirm if you are still seeing this issue. 👍

**Comment by SimonLab** [comment]
I've done some test by requesting some candidate (between 50 to 100 I think) pages in a short period of time. The memory usage went up but didn't reach the limit and it looks like this morning the garbage collector clean the memory too, so for now it's look that it works.

![memoryusage](https://cloud.githubusercontent.com/assets/6057298/15354080/cb561536-1ce3-11e6-8e14-733943a9c565.png)

However I'm still thinking how to reduce the memory usage of the app. On the [dashboard](https://github.com/FAC-GM/app/blob/29d88477c1662c95bef4ec25072580344c8c9816/lib/handlers/dashboard/get_list.js#L15) and on the [candidateView](https://github.com/FAC-GM/app/blob/29d88477c1662c95bef4ec25072580344c8c9816/lib/candidateView.js#L98-L120) endpoints we are requesting some data from Elasticsearch (jobs, users, clients) and it might be why we have some pick in the memory use. I'm wondering if we should instead requesting this data with some ajax call from the browser, do you think it will help?

**Comment by nelsonic** [comment]
Looks like you can Close the issue and add this to your list of node.js lessons learned. ✅

**Comment by SimonLab** [comment]
resolve with #446
