### ISSUE TITLE
Dependencies out of Date

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#447]
[![Dependency Status](https://david-dm.org/FAC-GM/app.svg)](https://david-dm.org/FAC-GM/app)
![fac-gm-dependencies](https://cloud.githubusercontent.com/assets/194400/15370642/c57c25b4-1d2f-11e6-8978-f024ca8b407d.png)
https://david-dm.org/FAC-GM/app

@SimonLab  / @heron2014 Please update as soon as possible.

**Comment by SimonLab** [comment]
resolved with #448
