### ISSUE TITLE
Decode characters on the api call

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#45]
All skills should be in human-readable formats.

![skillcharacter](https://cloud.githubusercontent.com/assets/6057298/10981966/9efa3b90-8402-11e5-9561-b8cb1c758c3f.png) should read `node.js`.

This appears to be a bug whenever there are special characters, e.g. `C#`, `Research & Development`, etc.

**Comment by nelsonic** [comment]
http://stackoverflow.com/questions/4292914/javascript-url-decode-function

**Comment by SimonLab** [comment]
:+1:

**Comment by SimonLab** [comment]
Some characters (# &) are still encoded

**Comment by iteles** [comment]
Clearing sprint 3 milestone as this is not in our final agreed scope for this sprint.

**Comment by heron2014** [comment]
By testing few search query line node.js, d3, c++, c#: 

![c](https://cloud.githubusercontent.com/assets/8476884/16461104/d3aec7ea-3e22-11e6-87fd-4605322358ed.png)
![skills-nodejs](https://cloud.githubusercontent.com/assets/8476884/16461117/e4cbe0c6-3e22-11e6-8a71-55c6d196ad45.png)

I haven't notice any bugs so far.

@Adam-JF can you please test it.

**Comment by Adam-JF** [comment]
@heron2014 Looking good to me.
