### ISSUE TITLE
App Is Down

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#450]
![screen shot 2016-05-20 at 08 57 03](https://cloud.githubusercontent.com/assets/15364186/15421117/71b15fcc-1e69-11e6-8d93-6dec02bbd92e.png)

**Comment by nelsonic** [comment]
@Adam-JF its available for me... 
<img width="919" alt="gm-app-avaialbe" src="https://cloud.githubusercontent.com/assets/194400/15421217/e617ec14-1e69-11e6-8edc-afea5ef9e94c.png">

Please refresh and confirm you still see an error. thanks.

**Comment by SimonLab** [comment]
It's up again. It might have been just an update on the heroku server. I'm going to check the log to be sure

**Comment by nelsonic** [comment]
Thanks for investigating @SimonLab 👍

**Comment by SimonLab** [comment]
@Adam-JF Thanks for the report, I checked the logs and it seems that Heroku and especially Elasticsearch couldn't response to our requests in time. I think there were a short issue with Heroku connection, it should work normally now.

**Comment by Adam-JF** [comment]
Sorted, thanks guys.

**Comment by SimonLab** [comment]
@Adam-JF just before the app was down do you remember if you were using Kibana? It seems that Elasticsearch take a long time to respond to the requests.

**Comment by SimonLab** [comment]
It seems that Elasticsearch try to resolve the problem
![errorelasticsearch](https://cloud.githubusercontent.com/assets/6057298/15431236/bf7b2fc6-1ea0-11e6-904d-c9d5da942201.png)
