### ISSUE TITLE
Create User Client

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#451]
As a manager I would like to be able to add a client by saving his email and password to the application. This will allow the new client to have an access to the application. 

### Steps to do that:

Create a form to allow an admin to create a client user:

- [x] Create an endpoint to access the form : GET /client-users/create (email, password, active)
- [x] Create a view to display the form: clientUserForm.html
- [x] Create an endpoint to save a client-user: POST /client-users/save
- [x] Create an endpoint which list the client-user: GET /client-users/list
- [x] Create an endpoint which allow an admin to access a form to edit a user: GET /client-users/edit
- [x] Tests for each of the endpoint
- [x] UI

**Comment by iteles** [comment]
@SimonLab Can we please get a user story for this which our PO can update with wireframes next week, a sprint milestone and some labels? 😉

**Comment by Adam-JF** [comment]
Tested, working great.
