### ISSUE TITLE
Proposed UI Client Dashboard

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#453]
![screen shot 2016-05-24 at 12 54 15](https://cloud.githubusercontent.com/assets/15364186/15503278/02e75eac-21b1-11e6-8d37-08070e56f63c.png)

![screen shot 2016-05-24 at 13 44 45](https://cloud.githubusercontent.com/assets/15364186/15504205/b92f4e28-21b5-11e6-961e-8ef5bbfd4b7b.png)

If it's in bold it's a priority for Sprint 10.

**- Candidate images will link to profiles so they can look at their pipeline and the information we have on them - This will link to their LI page initially but with later versions it will link to their internal application page.**
**- They will be able to view the job listings on our website by clicking the job titles.**
**- They will be able to decide custom interview stages.**
- _Eventual_ goal would be clients having an inbox where they would see submissions - submitted would no longer be a stage, a candidate must be 'in process' to appear on the dashboard.
**- To progress a candidate they would need to click on the individuals icon where they would have three options - 'Candidate Profile - Progress Candidate - Reject Candidate' - these rejected candidates will need to be stored together somewhere and the candidates will need a new status.**
**- Account manager is in top right (aka. Nick), client can click at any time and contact details will appear in a box (phone number, email addresss). Email address will have a quick link which will open a new email addressed to Nick on their email client.**
- Similarly the primary account manager/ or client user is displayed in the far top right so they know who is logged on.
- The map displays where our search is currently focused, in this instance Europe and Russia, with a new dot appearing when a new candidate is found (pretty...)
- They can see the terms (20% in this case) and clicking this will link to our terms of business document for them to look at.

The colour scheme is customised to their branding, aka. dark blue and yellow. The yellow for the text is from their logo and the background is a more attractive variation of the blue used in their logo

**The image in the heading (the plane) id like to have as a moving image, as in a short looping video of a plane going through clouds (just because it would look pretty) which I will find separately.**

There is a heavy focus on aesthetics for this work as this is the first time we'll be showing clients what the app is/could be. I am however very willing to hear optimisation suggestions from you all. For now, this is the starting point :)

**Comment by iteles** [comment]
@Adam-JF As discussed, @SimonLab @heron2014 and I will go through this in detail tomorrow and put together estimates for the additional functionality not in our original proposed scope 👍

**Comment by Adam-JF** [comment]
Mobile View

![screen shot 2016-05-24 at 15 13 34](https://cloud.githubusercontent.com/assets/15364186/15507119/23a10af6-21c2-11e6-8b94-10f839a0d828.png)

**Comment by iteles** [comment]
@Adam-JF As discussed over the phone earlier today, could you please let us know ASAP how you intend to deal with submitted candidates if they are not part of the main dashboard?

**Comment by iteles** [comment]
@Adam-JF This is now urgent. Could you please advise?

**Comment by Adam-JF** [comment]
@iteles Submitted should remain a stage for now. Until there is a separate, internal client inbox for submissions, general inquiries etc. there is no simple way to separate them.

**Comment by heron2014** [comment]
@Adam-JF the newest version of dashboard/stages/client-login is on a staging domain. Looking forward to your feedback.

**Comment by heron2014** [comment]
Resolved by #496 with the current design. If there is a new design, we can open new issue - enhancement.
