### ISSUE TITLE
Client Blacklisting

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#454]
I made eGym 'inactive' but eGym contacts are still listed as 'Client Employees' and are still not able to be contacted on the list view.

**Comment by SimonLab** [comment]
@Adam-JF do you mind to check if the error is fixed on the staging area, thanks

**Comment by Adam-JF** [comment]
Working on staging area.

**Comment by SimonLab** [comment]
This issue should be solved on the production app now.

**Comment by Adam-JF** [comment]
Fixed.
