### ISSUE TITLE
Remove Playabl Client Dulplicates

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#456]
Can we remove these two duplicates from appearing on the client list.

AVTeQB31rpl4VzRBHU6v
AVTjYZxwrpl4VzRBHWFn

They were uploaded by mistake.

We would like to keep the one with the single job vacancy attached to it.

**Comment by SimonLab** [comment]
@Adam-JF can you precise which one do you want to keep, there are no more jobs attached to any of them I think

**Comment by Adam-JF** [comment]
This is the one i'd like to keep - https://global-m.herokuapp.com/clients/AVTNwbTNln0IhCC9ww00

![Uploading Screen Shot 2016-05-25 at 08.58.13.png…]()

**Comment by SimonLab** [comment]
I've deleted the duplicates, you shouldn't see them in the list anymore

**Comment by Adam-JF** [comment]
Perfect, thank you.
