### ISSUE TITLE
Info Bug

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#457]
The 'Info' being saved on a candidate profile is being deleted when the page is refreshed.

This issue was not there during the initial testing.

**Comment by SimonLab** [comment]
Thanks for reporting the error, it will be fixed with the Pull Request #459

**Comment by SimonLab** [comment]
@Adam-JF this issue should be resolved with #459 , you can test it on the app.

**Comment by Adam-JF** [comment]
Fixed, working great.
