### ISSUE TITLE
Contact information on mobile

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#46]
At the moment contact information appeared like that:
![mobile](https://cloud.githubusercontent.com/assets/8476884/10997403/d2d7b30c-8484-11e5-9b95-51995fa389e2.png)

I can hide these information under a button (on click we will show the contact info)

**Comment by iteles** [comment]
Definitely something we need to test with our users :+1:

**Comment by heron2014** [comment]
@iteles agree, so perhaps we can leave it as it is now and update once we have feedback.

**Comment by Adam-JF** [comment]
Will consider mobile as a separate issue later on.
