### ISSUE TITLE
Travis not passing because of possibly linux/ubuntu issue with npm 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#461]
I have this issue with my machine: 

![ubuntu-error](https://cloud.githubusercontent.com/assets/8476884/15545844/a5be99a8-2295-11e6-99ad-e065e15f7132.png)

Anyone experiences similar issue? @SimonLab @nelsonic

**Comment by nelsonic** [comment]
@heron2014 what version of Node are you running?
have you tried `rm -rf node_modules` then `npm install` and `npm t` ?

**Comment by heron2014** [comment]
my node version is 4.1.0 , I think I am really behind. I will follow your advise @nelsonic

**Comment by SimonLab** [comment]
@heron2014 the test are passing on my ubuntu and my node version is 4.0.0 too. I think you can reinstall your npm packages if fix some problem for me yesterday. However there is still a problem with Travis that we need to identify, maybe a Travis vs bcrypt problem?

**Comment by nelsonic** [comment]
Hmm... can you send a link to the failed build?

**Comment by SimonLab** [comment]
This is the [build](https://travis-ci.org/FAC-GM/app/builds/132875454)

**Comment by heron2014** [comment]
This is very bizarre, I followed few suggestions from this issue [here](https://github.com/ncb000gt/node.bcrypt.js/issues/90#issue-5482289) but with no lack, still have problem with one of dependency from bcrypt. (I assume)

**Comment by heron2014** [comment]
@SimonLab my test are passing , I think the problem is with 'node-gyp rebuild' module.

**Comment by nelsonic** [comment]
@heron2014 / @SimonLab I suggest we _all_ agree on a (*latest stable*) version of Node.js to use for this project and use it *everywhere*...

**Comment by heron2014** [comment]
Resolved with this [460](https://github.com/FAC-GM/app/pull/460)
