### ISSUE TITLE
Update particular client view 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#462]
As a gm user I would like to see in client detailed page/or list of clients which client has an access to the application.  

- display information on particular client such as: Authorized to the application, email address used for the login (these information are not editable)

**Comment by heron2014** [comment]
This feature looks like this at the moment: 

example of client users Unauthorized: 

![authorized1](https://cloud.githubusercontent.com/assets/8476884/15577610/22b8d364-2355-11e6-928d-976251165cb9.png)

Authorized is the same but green.

**Comment by Adam-JF** [comment]
Working great.
