### ISSUE TITLE
unique email client user

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#464]
Before creating the new client user we need to check if the email already exist in database.

**Comment by SimonLab** [comment]
The idea is to search in our type if an email already exists or not. Elasticsearch provide the [Term Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html):

> The term query finds documents that contain the **exact** term specified in the **inverted index**

So by using the Term Query on our email field of the client user document we are expecting the result to return only documents with this email (the result will contain 0 or 1 document). To execute the search Elasticsearch is using the [Inverted Index](https://www.elastic.co/guide/en/elasticsearch/guide/current/inverted-index.html). The Inverted Index is a mapping between the keywords (generated from the fields of the documents by the [Analyser](https://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html)) and the documents.

If a mapping is not specified for the email field, Elasticsearch will automatically define the type of the field (String for the email in our case) and will automatically apply a default Analyser:

```
curl -XGET 'localhost:9200/_analyze?pretty' -d "email.test@gmail.com"
```

Will return the analyzed value which will be used in the inverted index:

```
{
  "tokens" : [ {
    "token" : "email.test",
    "start_offset" : 0,
    "end_offset" : 10,
    "type" : "<ALPHANUM>",
    "position" : 1
  }, {
    "token" : "gmail.com",
    "start_offset" : 11,
    "end_offset" : 20,
    "type" : "<ALPHANUM>",
    "position" : 2
  } ]
}
```

So we see that two keywords (tokens) have been created: **email.test** and **gmail.com**. The character '@' has been removed and the all value 'email.test@gmail.com' is not indexed! So if we use the Term Query on the field email with the value 'email.test@gmail.com' the search result  will be empty!

The solution is to not analyzed the field that we sure we will only search for the "complete" value! For that we need to redefine the mapping on the email field. However the mapping is immutable, so if a mapping has already been defined you can't change it anymore, this is to avoid error when trying to convert existing values to the new type of the mapping (String to Int for example will in most case fail).
At the moment we only have two values in our database so the simple solution is to:

- Extract the existing value (search) and save them in a json file on our machine
- Delete our current type (I suppose that by delete the type it will also delete the mapping, need to be verified!)
- Define the new mapping with the email field not_analyzed
- Insert our values saved

Each time we are creating a new type we need to try to define the type of the values and try to know if the fields of the type will be searchable or not.

**Comment by SimonLab** [comment]
# Steps

Extract existing values. Just a simple search will display the information we need

```
curl -XGET localhost:9200/theIndex/clientuser/_search?pretty
```
The _source properties of the result give us the information we need to store.

Delete the current type which will reset the mapping

```
curl -XDELETE localhost:9200/theIndex/clientuser
```

Define the new mapping for the email field:

```
curl -XPUT localhost:9200/theIndex/_mapping/clientuser -d '{"properties": {"email": {"type": "string", "index": "not_analyzed"} } }'
```

Reindex the values:

```
curl -XPUT localhost:9200/theIndex/clientuser/theId -d '{"email": "test@gmail.com", "password": "123"}'
```

Each time we are running our tests we are deleting all our database and indexing again some values from our fixtures. So we need to define the mapping of our user client field for our test too.

**Comment by Adam-JF** [comment]
How do I test this?

**Comment by SimonLab** [comment]
You need to try to create a new client user with an email which is already used by another client user

**Comment by Adam-JF** [comment]
Working great.

![screen shot 2016-06-01 at 13 54 34](https://cloud.githubusercontent.com/assets/15364186/15710104/672d9c1e-2800-11e6-9deb-509c47afc872.png)

**Comment by iteles** [comment]
@SimonLab @heron2014 
> How do I test this?

:arrow_right: That's the use of user stories :blush:
