### ISSUE TITLE
Select active user with a term query

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#467]
We are using [match_phrase](https://github.com/FAC-GM/app/blob/3e34e80671a755f0857a87c89ae9f178b480bb23/lib/database-helpers/elasticsearch/exist_active_users.js#L12) to select the active user. A better solution is to use the term query (see also #464 on why term query is good). For that we need to define a new mapping for the user type and for the value we don't want to be analyzed (email, phone, url...)

Because we can't redefine a mapping of an existing type we need to delete first. We apply the new mapping and then we can reindex the values on the new type

**Comment by heron2014** [comment]
Resolved by #466
