### ISSUE TITLE
App Duplicates

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#468]
The app is duplicating some profiles which are coming in from LI.

https://global-m.herokuapp.com/query?job=&fullname=alejandro+garcia+gill&location=&current=visual+engineering&skills=&page=1&totalPages=5

https://www.linkedin.com/in/alejandro-garc%C3%ADa-gil-95687b15

The LI address on all of the profiles is the same - the skills however, differ between profiles, as does the experience (some versions are incomplete).

![screen shot 2016-06-02 at 09 58 36](https://cloud.githubusercontent.com/assets/15364186/15739606/b5fc5634-28a8-11e6-93ba-5e850d5ee0e3.png)

**Comment by Adam-JF** [comment]
This is still an issue with the app.

**Comment by heron2014** [comment]
@Adam-JF Can you please test this again? By changing the mapping on email we improve duplicates. Also I can clean database if you need it.

**Comment by Adam-JF** [comment]
@heron2014 I've tested it again and it's working great.

It will be getting some pretty intensive testing over the next few weeks as we use Campaign Monitor more, but for now i'm happy with it.

With the cleaning up, it will only remove the profiles without matches in the app yes? If so, yes, please do run the script so everything is looking nice for the demo 👍

**Comment by heron2014** [comment]
I can removed the profiles with empty LI url - but that means the lists that you have uploaded will be removed? So maybe lets run it when we really have a need it for it.  Feel free to close this issue for now.

**Comment by Adam-JF** [comment]
@heron2014 Sorry, I misunderstood your comment, was thinking about the other issue with the csv lists!

I've done some checks and it's looking good, also, you've managed to fix the issue with my name, I just searched for Adam Foster and it worked! 👍
