### ISSUE TITLE
Client Side of App is Down

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#474]
The Clients List page is down.

 https://global-m.herokuapp.com/clients/list

![screen shot 2016-06-02 at 14 33 42](https://cloud.githubusercontent.com/assets/15364186/15746568/07df34a0-28cf-11e6-9088-57b155cf0753.png)

**Comment by SimonLab** [comment]
Thanks for reporting we are investigating the issue now

**Comment by SimonLab** [comment]
It should be ok now. We needed to update the list of users for #466 and some data didn't match the old list of client. We just update to the right structure for the client. Sorry for that

**Comment by Adam-JF** [comment]
Client list is back.

Dashboards are now unhappy.

![screen shot 2016-06-02 at 15 01 38](https://cloud.githubusercontent.com/assets/15364186/15747503/ed9903e2-28d2-11e6-9ab3-36b4a5e4896b.png)

**Comment by SimonLab** [comment]
@Adam-JF the list should be clean now, please can you check if the list is complete? Thanks

**Comment by Adam-JF** [comment]
Fixed. Thanks guys.
