### ISSUE TITLE
Customize stages depending on a client-user

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#475]
As a client user I want to be able to customize stages for particular jobs that I offer.

**Comment by SimonLab** [comment]
A user will be allow to select and unselect stages for a job, however a stage can't be unselected if there are any candidates on this stage

**Comment by heron2014** [comment]
![stages](https://cloud.githubusercontent.com/assets/8476884/15807360/4b9b0584-2b54-11e6-91e8-68c633263cb0.png)

**Comment by heron2014** [comment]
Resolved by #437
