### ISSUE TITLE
GMR API Email

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#477]
Nick hasn't been receiving all website applicants to his inbox for his Senior C# Developer role for Oak Capital. 

He received an email notification for the application of the following:
Manuelito Amor Cortez Cortez
Mina Abd El-Hakim
Nimish Tandon Tandon
Nader Kamel

![screen shot 2016-06-06 at 08 14 41](https://cloud.githubusercontent.com/assets/15364186/15815530/97ee4600-2bc5-11e6-91a2-8095c6e13cc9.png)

However, as you can see, the number of applicants for the role was far higher, he didn't receive an email from the GMR API address about these other candidates.

**Comment by iteles** [comment]
@Adam-JF For applicants coming from the website, it's TOAD you need to speak to as we have no control over this.

**Comment by Adam-JF** [comment]
@iteles Thought as much, will send them over an email. Thank you.
