### ISSUE TITLE
Better font colors to be more distinguish

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#48]
at the moment on front page we have :

![colors](https://cloud.githubusercontent.com/assets/8476884/10999961/f222edc8-8496-11e5-9686-5b4881f55663.png)

Same apply to detailed view page

**Comment by nelsonic** [comment]
@heron2014 please re-phrase this as a story focussing on the benefit to the user of the application. 
Are we including this in **Sprint 3**? (*thanks*)

**Comment by iteles** [comment]
I would also keep this a bit more general - moving away from just font colours and as an improvement to the UI.

**Comment by heron2014** [comment]
@iteles I think this issue is covered in [issue 67](https://github.com/FAC-GM/app/issues/67)

**Comment by iteles** [comment]
Ok, closing this issue for now as it's a little dated given our UI has changed and will keep changing. We'll open a UI-specific issue at some point in the near future!
