### ISSUE TITLE
Client Dashboard is Down

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#488]
I was editing the stages for the System Engineer job posting for 360T and manually refreshing the page so the new stages would be displayed and the test app stopped working and displayed the 500 Internal Server Error message.

This only affects the client dashboard page.

**Comment by iteles** [comment]
Hi @Adam-JF Is it still down for you? And is it just for this client or is it down across the board?

I'm using a test foundersandcoders email address and it seems to be working!

**Comment by Adam-JF** [comment]
@iteles It's still down for the 360T account I made - and its just for the new client dashboard, the login itself works fine, I just can't get any further than that.

**Comment by SimonLab** [comment]
@Adam-JF did you logged again before changing the stages or you didn't have to?

**Comment by Adam-JF** [comment]
I started at the client login screen where autofill has stored my login details for it and then proceeded to move some aspects of the dashboard around (progressing people through stages, removing people etc.) then when I changed the stages for the first job and refreshed the page a few times, I got the 500 error message.

**Comment by SimonLab** [comment]
@Adam-JF Thanks for the details. Just to confirm when you change the stages allowed for the job did you select only one?

**Comment by Adam-JF** [comment]
At one point I attempted to remove the stages for the System Engineer job all together - this didn't work.

Then I made it so just one stage would be there, refreshed the page several times and then I got the error.

**Comment by Adam-JF** [comment]
It's back up. Thanks guys.

**Comment by SimonLab** [comment]
@Adam-JF It should work now with all the stages unselected and also with only one stage selected.
