### ISSUE TITLE
On detailed view page more information next to the photo

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#49]
Should we add for example title of current job, or other information ?

**Comment by nelsonic** [comment]
We should ask the people using the app what they want in the feedback session on Tuesday. but *before* then we could add some relevant details. the current job + company could be a good set of *useful* data to add. :+1:

**Comment by iteles** [comment]
@heron2014 Do you have a list from your conversations with GM on what the most important information is to them?

**Comment by heron2014** [comment]
Agree with @nelsonic.  I will update information like current company and title. On Tuesday they can decide what is more useful for them. @iteles I think this iteration and results from Tuesday meeting will really shape the UX and guide us how we can tweak the design for them to be the most efficient regards what information should be placed where and how etc.

**Comment by iteles** [comment]
Agreed with @Adam-JF that this will be a requirement based on his evolving vision for the app. This will stay open until he is able to fill this out with more information.

**Comment by heron2014** [comment]
This issue can be closed due to the new design and new content see #484
