### ISSUE TITLE
360T Roles

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#490]
Client dashboard is only displaying 6 open roles when on the 360T client there are 22.

Where are the missing ones? Are they not being displayed deliberately?

**Comment by SimonLab** [comment]
@Adam-JF the client page display all the roles, active and inactive, however the dashboard only show the jobs which are currently active. It's true that the term open roles should be rename to just "jobs" maybe, or should we only display the active roles on the client page?

**Comment by Adam-JF** [comment]
Understood. This is all going to change relatively soon, will be submitting my client and dashboard designs/changes to you guys this afternoon. This will include renaming features etc.

**Comment by iteles** [comment]
Thanks @Adam-JF, that would be great. We'll be focusing on the dashboard today but will take a look tomorrow.

Can we close this issue for now?

**Comment by Adam-JF** [comment]
Yep.
