### ISSUE TITLE
Add rejected tag

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#495]
As a recruiter I want to see on the detailed page of a candidate a list of tags which represent the jobs where the candidate has been rejected

**Comment by heron2014** [comment]
@Adam-JF we have implemented rejected tags on candidate page. Please can you review it, thanks.

**Comment by Adam-JF** [comment]
Firstly, thank you so much for doing that so quickly. 

It's working great on the test site - I used Simon Duff's profile for the example.

I did add him to the dashboard and remove him twice though (not a bug), hence the double on the profile (my bad)

One thing, can we add the word 'Rejected' to the status tag - aka. 'Kaufland - DevOps - Rejected' just to be crystal clear.

**Comment by heron2014** [comment]
@Adam-JF We have deployed last changed to staging area.

**Comment by Adam-JF** [comment]
Works great.
