### ISSUE TITLE
Create label list

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#498]
Create a new label list item on the type csv-list:
The document structure on the csv-list type is 
```
{
  listName: "the name of the list"
}
```
The mapping of listName must not be analyzed!

- [x]  Define the mapping of the csv-list on test/initialize.js
- [x] Define the mapping of csv-list with curl for the production database
```
curl -XPUT urlServer/theiIndex/_mapping/csv-list -d '{"properties": {"listName": {"type": "string", "index": "not_analyzed"} } }'
```
- [x] Create a form which let a user creates the labe list item
- [x] Create the handler which index a new label list only if the label name doesn't exist yet (that's why we don't want the listName to be indexed which allow us to search for the exact name)
- [x] Create a mapping on the new candidate property listNames  to not_analyzed
- [x] Create mapping not_analyzed for contacts.email

**Comment by SimonLab** [comment]
The email on the candidate is currently analyzed by ES. To be able to use the terms query to search on the email we need the value to be not analyzed. Instead of reindexing the email value with the new mapping we are creating a new property "emailRaw" which is a copy of the email but not analyzed. We don't want to reindex because changing the mapping can break the extension especially the way we are updating information of a profile from the extension.

**Comment by SimonLab** [comment]
@Adam-JF you can review the first version on the staging area, let us know what you think. At the moment you can create a list and see all the lists:
![list](https://cloud.githubusercontent.com/assets/6057298/16275685/f6827882-38a2-11e6-9fd9-37d21cef56c3.png)

The number next to the name of the list is the number of candidates in this list. Maybe test this feature with a small number of profiles in the csv file otherwise if the profiles don't exists yet on the application it will create a lot of new profiles (but you can try this also if you want)

**Comment by Adam-JF** [comment]
I added a new list called Windows and it uploaded as expected and displayed the correct number of results (19)
I could see the list you created and my own.
The options for uploading a file and naming it worked great.

All looking good so far.
