### ISSUE TITLE
Download the list of candidate who belongs to specific list

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#502]
As a user I would like to be able to download the list of candidates who belong to specific group. 

Basic wireframe for the list of groups with action button (the first one is download): 

![fron-end](https://cloud.githubusercontent.com/assets/8476884/16199746/a6b0a942-3702-11e6-8e7d-b6794cd5f63f.png)

**Comment by SimonLab** [comment]
@Adam-JF you can now test the new version on the staging area.

**Comment by Adam-JF** [comment]
I uploaded a test file called Windows and renamed it Test with the just the columns Email and Name.

Upload worked as expected.

Downloaded file and the file was renamed to 'Test' (as expected) it now contained original contents in alphabetical order as well as 'id, location and current (job title)'.

Amazing work - looking great.

**Comment by iteles** [comment]
Can we close this issue @Adam-JF ? 😊
