### ISSUE TITLE
Display list of candidates who belongs to specific group

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#503]
As a user I want to see all the candidates who belong to specific group. 

- [x] create an endpoint /csv-list/{param} - param will be name of the specific group
- [x] create helper to search in ES for only candidates who belongs to this group
- [x] replace paragraph with the name of the list by anchor tag with above url
- [x] reuse home page to display candidates
- [x] add condition for search bar on home page to only display custom search bar for this endpoint (search bar will have only one input to search for skills - ATM)
- [x] tests

**Comment by heron2014** [comment]
@Adam-JF you can now test this feature in the staging area. Looking forward to your feedback.

**Comment by heron2014** [comment]
@Adam-JF can this issue be closed now?

**Comment by Adam-JF** [comment]
@heron2014 Yes, great work.
