### ISSUE TITLE
Delete a csv list

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#504]
- [x] For each candidates belonging to the list delete the name of the list from the property listNames of the candidates

- [x]  Delete the document on the type csv-list which represent the list: 
- [x] Tests

**Comment by SimonLab** [comment]
@Adam-JF we have deploy a new version on the staging area, you can now test the new features and let us know what you think, thanks

**Comment by Adam-JF** [comment]
I was able to delete my test file successfully.

Note - I had to refresh the page for these changes to take effect.
