### ISSUE TITLE
Display and remove list of specific groups on candidate profile

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#505]
As a user I would like to see on candidate profile to which list that candidate belongs to. Also I want to be able to remove that candidate from one of the lists.

- [x] add property listNames on the candidate profile 
- [x] display listNames on the candidate profile 
- [x] create an endpoint /candidate/list-delete [POST] 
- [x] ajax call to delete candidate from the specific list
- [x] tests

**Comment by heron2014** [comment]
Basic wireframe for this feature: 

![listnames](https://cloud.githubusercontent.com/assets/8476884/16303852/bf275ad0-394a-11e6-9b15-6cecfc179fc6.png)

**Comment by SimonLab** [comment]
@Adam-JF the version of this feature is on the stagin area, you can now test it.

**Comment by Adam-JF** [comment]
@SimonLab Working great. 

I removed Aarti N Vanodiya from the Development Manager list and she was removed from the list but her profile remained in the app.
