### ISSUE TITLE
Navigation Buttons - Homepage

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#508]
Currently the navigation buttons on the homepage jump to the other font awesome arrow, not to the bottom of the page - I intend to reposition these buttons to the right hand side of the page so will need some HTML changing.

![screen shot 2016-06-21 at 15 01 54](https://cloud.githubusercontent.com/assets/15364186/16232158/5c4d53b8-37c1-11e6-92c8-ca87c469f4ff.png)

**Comment by iteles** [comment]
@Adam-JF When you know the changes needed, please let us know and assign to @heron2014

**Comment by heron2014** [comment]
@Adam-JF I will push this change of html into your branch, then you will be able to test it.

**Comment by Adam-JF** [comment]
@heron2014 Thank you so much! I've been running round in circles thinking of how to make this work.

**Comment by Adam-JF** [comment]
@heron2014 Do I need to pull the changes from the test-branch in the same way i'd do it from master branch?

**Comment by heron2014** [comment]
@Adam-JF I just pushed the recent changes , use these commands:
```git checkout test-branch``` 
```git pull origin test-branch```

I already merged with master, so your branch is up to date with master.

Please, test the changes and let me know :+1:

**Comment by heron2014** [comment]
@Adam-JF can this issue be closed?

**Comment by Adam-JF** [comment]
@heron2014 Perfect, thank you.
