### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#509]
I noticed the client dashboard work has been merged! 

Would it be possible to change the font to Myriad Pro across the app now?

Is there anything I need to do in advance to make this work?

**Comment by heron2014** [comment]
@Adam-JF I will move the fonts from the client folder to the general one, in this way we can use the fonts across both pages.

**Comment by heron2014** [comment]
@Adam-JF can this issue be closed?

**Comment by Adam-JF** [comment]
@heron2014 Yep.
