### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#51]
Would be good to have our dependecies up to date for the end of sprint review on Tuesday :blush: 

<img width="505" alt="screen shot 2015-11-08 at 17 52 38" src="https://cloud.githubusercontent.com/assets/4185328/11021662/8a127b66-8641-11e5-8f2b-4c4d3708e50f.png">

<img width="968" alt="screen shot 2015-11-08 at 17 51 41" src="https://cloud.githubusercontent.com/assets/4185328/11021658/6ffdec88-8641-11e5-9664-a67c908a619c.png">

**Comment by SimonLab** [comment]
@iteles the [current PR](https://github.com/FAC-GM/app/pull/50) should update the version of dependencies as soon as it is merged to master.
see also the issue [31](https://github.com/FAC-GM/app/issues/31)

**Comment by iteles** [comment]
:+1: Perfect, I searched for the wider dependencies but didn't find them so this is great.

**Comment by SimonLab** [comment]
![dependencies](https://cloud.githubusercontent.com/assets/6057298/11022191/73530d82-8650-11e5-8e09-c09ebdb6c8d4.png)

Updated on branch api

**Comment by nelsonic** [comment]
:+1:

**Comment by SimonLab** [comment]
All dependencies are now up to date
![dependencies](https://cloud.githubusercontent.com/assets/6057298/11095712/42ed74da-888e-11e5-8f43-d162370e6ff0.png)

**Comment by nelsonic** [comment]
For now... :wink:
Good stuff @simonlab :+1:
