### ISSUE TITLE
search by skills on a list

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#510]
- [x] Create endpoint for skill search on csv list
- [x] Search by skills on ES
- [x] Display results

@Adam-JF searching by skills is the same as applying a filter on the list of candidates. So either the candidates have the skills and we display them or they don't have the skills and we don't display them. This means that the relevance of the search will always be 100% for each candidates. So from my point of view I don't think we should display the relevance on this search, what do you think?

**Comment by heron2014** [comment]
@Adam-JF this feature has been deployed to the staging area. Please test.

**Comment by Adam-JF** [comment]
@heron2014 Working great.

However, are we going to display the matched skills in a similar fashion to how we do with profiles?

aka.
![screen shot 2016-06-30 at 11 15 14](https://cloud.githubusercontent.com/assets/15364186/16484926/f90ff720-3eb3-11e6-81d7-167b9c2f8534.png)

It's not a make or break addition but might be nice to give users a bit of feedback that the app has in fact returned what they searched for.

**Comment by heron2014** [comment]
@Adam-JF good point. I will work on this.

**Comment by heron2014** [comment]
@Adam-JF Please test the newest version. Searched skills should appear on the profile now.

**Comment by Adam-JF** [comment]
@heron2014 Perfect!
