### ISSUE TITLE
Local Host Issue

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#511]
Getting an internal server error message on my local host site whenever I try to visit a profile.

I've re-run npm start... any ideas?

![screen shot 2016-06-22 at 12 45 03](https://cloud.githubusercontent.com/assets/15364186/16265456/59d9a47c-3877-11e6-9bd1-fb4119b4e962.png)

**Comment by heron2014** [comment]
@Adam-JF Could you paste a photo from your terminal?

**Comment by Adam-JF** [comment]
![screen shot 2016-06-22 at 12 54 28](https://cloud.githubusercontent.com/assets/15364186/16265654/7af7892a-3878-11e6-83cc-b0af74f455f9.png)
Aether:app adam$ npm start

> gmapp@1.0.2 start /Users/adam/gm-app/app
> node --max_old_space_size=400 lib/start.js --production

The server is running on:  http://Aether.local:8000
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'forEach' of undefined
    at module.exports (/Users/adam/gm-app/app/lib/handlers/candidate-view/helpers/rejected_jobs.js:28:15)
    at /Users/adam/gm-app/app/lib/candidateView.js:118:50
    at /Users/adam/gm-app/app/lib/database-helpers/elasticsearch/list_stages.js:25:12
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at respond (/Users/adam/gm-app/app/node_modules/elasticsearch/src/lib/transport.js:310:9)
    at checkRespForFailure (/Users/adam/gm-app/app/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/Users/adam/gm-app/app/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/Users/adam/gm-app/app/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)

**Comment by heron2014** [comment]
@Adam-JF can you try to run your tests by : ```npm test``` ? Let us know if you still have the issue after.

**Comment by Adam-JF** [comment]
![screen shot 2016-06-22 at 13 09 38](https://cloud.githubusercontent.com/assets/15364186/16266026/a4b0ce1e-387a-11e6-95a8-a9c81ca3192a.png)

**Comment by Adam-JF** [comment]
It's back up - thanks :)
