### ISSUE TITLE
Add horizontal line

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#512]
Can we add a horizontal line in HTML between each candidate box? - i'm aware I can achieve a similar effect using border-bottom, but I want to have more free scope to change the width and size properties of the line.

Attached are images of the homepage without a candidate box, with a border-bottom and then the original plan for the design.

![screen shot 2016-06-22 at 14 36 31](https://cloud.githubusercontent.com/assets/15364186/16268664/2c3afa74-3887-11e6-8326-d3f7761b7576.png)

![screen shot 2016-06-22 at 14 36 53](https://cloud.githubusercontent.com/assets/15364186/16268705/462ba6d6-3887-11e6-92d1-f0a51d51f834.png)

![home page view](https://cloud.githubusercontent.com/assets/15364186/16268721/58e8252e-3887-11e6-9fc0-ae626db8d6e7.png)

**Comment by heron2014** [comment]
@Adam-JF Do you mean to have a horizontal line which goes up to the checkboxes area for sending emails?

**Comment by Adam-JF** [comment]
@heron2014 Yes - ideally i'd just like the lines themselves inserted, probably at about 2/3px and then I could edit the width accordingly?

**Comment by heron2014** [comment]
@Adam-JF I made a quick change in developer tool:

This is ugly for now because it is a wrong background and still while box around the candidate (but is it what you meant? ) 
 
```.list-wrapper
    border-bottom: 1px black;
   border-bottom-width: thick;
``` 
I believe from the quick look the first line shouldn't appear if you add border only to .list-wraper and not to .title-wrapper. 

This is the result:
 
![border](https://cloud.githubusercontent.com/assets/8476884/16269792/c118b600-388b-11e6-8dcc-8c3faf40c775.png)

**Comment by Adam-JF** [comment]
Yes and no, I think attaching it to the the list wrapper might be a good plan.

But i'd like some padding either side, similarly, I want to be able to change the width without the formatting for the candidate boxes changing, I don't want to stretch across the entire page, I want it to stop more or less just before the send email boxes on the left of the profiles - hence why I thought the line might have to be a <hr> addition, not a border.

**Comment by Adam-JF** [comment]
If we add a ``<hr>`` to recur underneath each profile with a class name then I can change/define the style in the CSS?

**Comment by heron2014** [comment]
@Adam-JF yes, I will push some changes soon and you can then style it.

**Comment by heron2014** [comment]
@Adam-JF I have added ```horizontal-profile``` class to hr , feel free to change the class name - I haven't styled it at all - I leave it to you. If you need any help let me know. :+1:

**Comment by Adam-JF** [comment]
![screen shot 2016-06-22 at 17 10 45](https://cloud.githubusercontent.com/assets/15364186/16274185/5e44c22e-389c-11e6-9518-482a7115fcb8.png)

**Comment by SimonLab** [comment]
You need first to commit your changes: ``` git commit -am 'your message'``

**Comment by Adam-JF** [comment]
What do I do about this? 🆘 

![screen shot 2016-06-23 at 10 02 50](https://cloud.githubusercontent.com/assets/15364186/16297651/a98e34d0-3929-11e6-9c98-8b62b7d0f104.png)

**Comment by heron2014** [comment]
@Adam-JF have you managed to commit your changes before that message?

**Comment by Adam-JF** [comment]
Yeah I did, it said that there were no new changes to commit.

**Comment by heron2014** [comment]
@Adam-JF From stackoverflow: http://stackoverflow.com/questions/13361729/found-a-swap-file-by-the-name and http://stackoverflow.com/questions/14513349/e325-attention-found-a-swap-file-by-the-name-git-commit-editmsg-swp , they recommend to delete that swap file

**Comment by heron2014** [comment]
@Adam-JF Try to remove this file : ```git rm .git/.MERGE_MSG.swp```

**Comment by Adam-JF** [comment]
Ok, i'm not concerned about losing anything on my end, just want to make sure I don't impact you guys.

I'll delete it now.

**Comment by Adam-JF** [comment]
![screen shot 2016-06-23 at 10 17 26](https://cloud.githubusercontent.com/assets/15364186/16298134/bad23d34-392b-11e6-9ec3-e896833e374c.png)

**Comment by heron2014** [comment]
@Adam-JF yes, merge it with commit message.

**Comment by Adam-JF** [comment]
@heron2014 Sorry to sound thick... but, how do I do that, where do I type... how do I then merge it... 😨

**Comment by heron2014** [comment]
@Adam-JF by default your terminal opened editor called ```vim```.  We can use vim to insert your commit or you can quit this editor and go back to normal terminal by ```:q```

**Comment by Adam-JF** [comment]
Should I just press ctrl C and then go back into the app and make a new commit message now?

Will the conflicting file I tried to merge again have been removed?

**Comment by Adam-JF** [comment]
Typed :q and got this...

![screen shot 2016-06-23 at 10 29 13](https://cloud.githubusercontent.com/assets/15364186/16298445/57b3e58e-392d-11e6-957a-c2dbe923c42d.png)

**Comment by heron2014** [comment]
Press enter

**Comment by Adam-JF** [comment]
Nothing happens... shall I add the '!' at the end of :q ?

**Comment by heron2014** [comment]
you can also try: ```:wq``` to write quite, also you can try what they suggest

**Comment by Adam-JF** [comment]
Ok, now we're getting somewhere (really sorry about this)

Next steps?

![screen shot 2016-06-23 at 10 32 32](https://cloud.githubusercontent.com/assets/15364186/16298540/d27901dc-392d-11e6-9b0f-54297149a5c0.png)

**Comment by heron2014** [comment]
@Adam-JF ok cool! is said git commit to complete merge - try to do that.

**Comment by heron2014** [comment]
```git commit -am 'problem fix' ``` or something like that

**Comment by Adam-JF** [comment]
Yayyyy - I think it worked :D

I'm going to try and pull from test branch now.

**Comment by heron2014** [comment]
@Adam-JF great! yes try to pull.

**Comment by Adam-JF** [comment]
I pulled and it said it was up to date.

![screen shot 2016-06-23 at 10 47 54](https://cloud.githubusercontent.com/assets/15364186/16299016/ff9c13b4-392f-11e6-9898-b4e6f8f908bf.png)

Checked the code for the changes to candidate.html in partials and I can't see your changes. I have done npm test and npm start to see whether everything just needed refreshing and it's still not there...

Should I pull again? (also, hilariously, this is now a 30 comment conversation about a horizontal line, haha)

![screen shot 2016-06-23 at 10 47 43](https://cloud.githubusercontent.com/assets/15364186/16299049/2960c37a-3930-11e6-8bac-02128110aae6.png)

**Comment by heron2014** [comment]
@Adam-JF hmmm, try to close everything and open again.

**Comment by Adam-JF** [comment]
Still not working for me. I closed everything, restarted my terminal and atom and it's still not there.

**Comment by heron2014** [comment]
@Adam-JF the point of this story is : to never add horizontal line hahaha

**Comment by Adam-JF** [comment]
@heron2014 Noted - horizontal lines are shi*

**Comment by Adam-JF** [comment]
For now should I just copy the code you put into the candidate html and then push it all together later on once i've done the styling?

**Comment by heron2014** [comment]
@Adam-JF. I guess that's easier, you can do that and try to push.

**Comment by heron2014** [comment]
@Adam-JF I would recommend you to read about the git fetch, git pull, git merge, git reset, git log :+1:

**Comment by Adam-JF** [comment]
@heron2014 Thank you for all your help - will keep that in mind!

Working great now!

![screen shot 2016-06-23 at 12 53 30](https://cloud.githubusercontent.com/assets/15364186/16302177/9c22d1e4-3941-11e6-9adb-561a5b7a6bc4.png)

**Comment by heron2014** [comment]
@Adam-JF Great! :+1:

**Comment by Adam-JF** [comment]
Would it be possible to input the horizontal lines across the rest of the app today?

Aka. between job posts, user lists etc.

**Comment by heron2014** [comment]
@Adam-JF regards to the horizontal line on job posts and user lists pages, are these changes goes to the current [PR](https://github.com/FAC-GM/app/pull/507) into test-branch? Or these modification will be in the next PR?

**Comment by Adam-JF** [comment]
@heron2014 Ideally they'd be in this PR - however, i've been having some issues today so will be with you guys tomorrow morning to go through everything :) we can make a plan then.

**Comment by heron2014** [comment]
This has been resolved.
