### ISSUE TITLE
Add csv format validation

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#515]
- [x] Check the file received is a csv
- [x] Check the Email and Name columns exist

**Comment by SimonLab** [comment]
@Adam-JF a new versin is on the staging area. The validation of the csv file is now imlemented, please test, thanks

**Comment by Adam-JF** [comment]
Attempted to add .xls file - was unable to select it whilst browsing through my files, was only allowed to upload .csv files.

Great work.
