### ISSUE TITLE
Select All - Help

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#518]
@heron2014 I've done something stupid - whilst moving the Select All button to the left of the screen and fixing it in position (did this so someone can always hit the select all regardless of where they are on the page) - i've managed to remove its ability to actually 'Select All' of the email addresses.

I'm not sure how i've done that. Help would be much appreciated.

## Update

It's not completely broken, it just works sporadically now...

**Comment by heron2014** [comment]
I have also noticed (not sure if this is your intention) - checkboxes for sending emails are not aligned to the Select all - label?
![home-page](https://cloud.githubusercontent.com/assets/8476884/16306754/b47b4ab8-3956-11e6-882b-bdcd4d83f996.png)

And if you do search query :

![search-query](https://cloud.githubusercontent.com/assets/8476884/16306809/e028a73c-3956-11e6-9140-58ad7015188e.png)

Also small thing , when you scroll down the page overlap the navigation...

**Comment by heron2014** [comment]
@Adam-JF yes you right, the select all doesn't work on my computer now, I am investigating it now.

**Comment by Adam-JF** [comment]
The select all shouldn't be aligned, I didn't want it to overlap with the other boxes so yes that's correct.

With the second point by the navigation did you mean the actual search header? If so, yes I wanted it to be slightly transparent.

Everything aligns perfectly on my screen - worried I've made the styling rules too specific for my macbook though.

![screen shot 2016-06-23 at 15 32 23](https://cloud.githubusercontent.com/assets/15364186/16307036/b905b39c-3957-11e6-9e25-a0f5ef63f580.png)

**Comment by heron2014** [comment]
@Adam-JF 
The relevance circles on scroll they are on top of the search header , just checking if this is your intention?

**Comment by Adam-JF** [comment]
@heron2014 No, sorry they shouldn't do that - what's the z-index of the header?

Need the relevance circles to be one underneath that.

**Comment by heron2014** [comment]
@Adam-JF to fix : select all to be clickable add to : 

- mobile-first.css line 377

```js
.title-wrapper .aside-1 {
  padding-right: 60px;
  position: fixed;
//add this:
  z-index: 2
}
```

Please, let me know if that works.

**Comment by heron2014** [comment]
@Adam-JF z-index of the header is super high: ```z-index: 1002; line 41 on mobile-first.css```

**Comment by Adam-JF** [comment]
@heron2014 Changing z-index to 2 for Select All worked perfectly - thank you!

**Comment by Adam-JF** [comment]
@heron2014 I've changed the header so it's no longer transparent - decided it looks better.

**Comment by heron2014** [comment]
@Adam-JF cool!
