### ISSUE TITLE
Boxes/Containers

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#519]
I've removed the box borders throughout the app whilst I was doing the edits for the profiles view on the homepage - this wasn't completely unintentional, but I did intend to/need to replace the boxes with the same horizontal line styling as i've made on the homepage - same padding/margin/style etc.

How would I go about doing this?

Homepage with horizontal lines

![screen shot 2016-06-23 at 14 59 13](https://cloud.githubusercontent.com/assets/15364186/16305768/1e78bfa8-3953-11e6-87e4-977b715d2aac.png)

Current Client Page View

![screen shot 2016-06-23 at 14 59 28](https://cloud.githubusercontent.com/assets/15364186/16305784/319d12be-3953-11e6-86a3-6ab21ec44719.png)

**Comment by heron2014** [comment]
@Adam-JF just to clarify , you want to add <hr> with the same styling to client page view?

**Comment by Adam-JF** [comment]
Yep, to every view that used to have a box around it, so jobs/clients - everything that we've listed really...

**Comment by heron2014** [comment]
@Adam-JF to add hr to the client view page :

add the same hr with the same class to:
```
partials/client.html line 32 just before closing </article> tag
```

Also please rename this class into something more general because we will re-use it to all sort of views. Once you do that , I will assist you with other views. :+1:

**Comment by heron2014** [comment]
@Adam-JF Let me know if all good!

**Comment by Adam-JF** [comment]
@heron2014 Works perfectly 👌

**Comment by heron2014** [comment]
Issue resolved by the PO comment above :+1:
