### ISSUE TITLE
Wait for the list to be deleted

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#521]
Elasticsearch take some time to index or update a document which means that on certain case the document updated or indexed is not available immediately on a search. This issue will be resolve on the next version of Elasticsearch.

see https://github.com/FAC-GM/app/issues/504#issuecomment-228269086
An easy way to resolve this issue is to wait a few seconds before executing a new search.

**Comment by heron2014** [comment]
Resolved by #517
