### ISSUE TITLE
Profile Button Styling

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#527]
CSS Styling for candidate profile buttons.

**Comment by iteles** [comment]
@adam-jf always useful to have a screenshot for reference on these :)

**Comment by Adam-JF** [comment]
@iteles These are the edits I was trying to push earlier, but my thing was acting up (I was doing something wrong) - very minor edits though.

**Comment by Adam-JF** [comment]
@iteles I've pushed all my changes to test-branch but I can see this has been closed now - is there anything I need to do?

**Comment by heron2014** [comment]
Resolved by #533 PR
