### ISSUE TITLE
CSV Upload Bug

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#529]
Adding a CSV file to the app results in the contents of the csv being re-uploaded as new profiles.

I had uploaded the skills csv's that the guys wanted on the app - I will forward all of these CSV files to you guys now for testing - all of these lists are composed exclusively of people who should have profiles within the app as such, none should be 'new profiles'.

I have deleted all the list uploads in the hope it would temporarily remove the duplicate profiles but it hasn't.

I'm aware Nick wanted to work on the testing feedback, but as some general points we'll need to check tomorrow.

**We need to make sure that the app pairs with the existing profiles and does not create duplicates, the email i'm hoping will work as confirmation of a profile match - there will be edge cases as a result of usernames being lost in translation as we transfer from Campaign Monitor etc.

We need to make sure that when a csv file is deleted it will not remove any profiles that have been added to the app (even though it would have been handy for now!)

We need to make sure the app does not duplicate a new profile even if it's present on two lists.**

![screen shot 2016-06-29 at 22 13 45](https://cloud.githubusercontent.com/assets/15364186/16469028/c4f2a36a-3e46-11e6-8477-1c81b461125c.png)

![screen shot 2016-06-29 at 22 18 27](https://cloud.githubusercontent.com/assets/15364186/16469164/728693d8-3e47-11e6-9662-85520a4f441c.png)

**Comment by SimonLab** [comment]
@Adam-JF are you sure that the profiles were already on the application and especially if the emails are already defined in the application? Do you still want to clean the database and delete the profiles where no LI url is defined?
We don't delete any profiles when a list is deleted (as you noticed).

**Comment by Adam-JF** [comment]
@SimonLab The lists were created using the master list you downloaded for me a few weeks ago.

I made the lists personally so there should be a perfect crossover with the app.

Yes, I'd like to clean up the database by deleting the profiles without the LI URL defined please.

Below is an example of a duplicate upload. Hubert has a full profile as well as the additional one made by the CSV upload.

![screen shot 2016-06-30 at 09 21 22](https://cloud.githubusercontent.com/assets/15364186/16481630/1e90b6d4-3ea4-11e6-8b83-a47ad4bcc86a.png)

**Comment by heron2014** [comment]
- [ ] create a script to delete the profile with empty li-url

**Comment by heron2014** [comment]
@Adam-JF 1634 profiles with empty LI has been now deleted.

**Comment by Adam-JF** [comment]
@heron2014 Perfect, thank you.

**Comment by Adam-JF** [comment]
@heron2014 In order to test this i'm going to re-upload all the lists from last night.

I'll let you know if there's any issue.

**Comment by Adam-JF** [comment]
@heron2014 Unfortunately there is still a problem with it - please see below Cosmin has the same email address, one on a full profile, the other one on a blank profile which was uploaded in the CTO csv file.

![screen shot 2016-06-30 at 16 49 36](https://cloud.githubusercontent.com/assets/15364186/16494816/b09601c2-3ee2-11e6-8f07-48d6f2d4699f.png)

![screen shot 2016-06-30 at 16 50 22](https://cloud.githubusercontent.com/assets/15364186/16494842/cd988c54-3ee2-11e6-801d-b833dc88fb0d.png)

![screen shot 2016-06-30 at 16 50 38](https://cloud.githubusercontent.com/assets/15364186/16494846/d2491624-3ee2-11e6-9e76-454dae339cb9.png)

**Comment by Adam-JF** [comment]
@heron2014 Might be worth running that script again as well.

**Comment by heron2014** [comment]
@Adam-JF thanks for that. I will run the script shortly after I do some tests.

**Comment by heron2014** [comment]
@Adam-JF new version is now deployed into the staging area. Please test it and let me know your feedback. Also I can after clean the database before the demo if there is a need for it.

**Comment by Adam-JF** [comment]
@heron2014 Looks to be working much better now, uploaded the rest of the lists and there only seem to be about 10 or so new profiles and they're accounted for by a change in the email address.

Only thing now is the fact the contents number being displayed next to the list title isn't consistent, sometimes it disappears - see C++ and CTOs etc.

![screen shot 2016-07-01 at 12 53 22](https://cloud.githubusercontent.com/assets/15364186/16520875/1068b9fc-3f8b-11e6-921f-edb463644073.png)

**Comment by heron2014** [comment]
@Adam-JF thanks for that. We will investigate it.

**Comment by iteles** [comment]
@heron2014 Could you please open a separate issue for this so that this one can be closed?

**Comment by heron2014** [comment]
@Adam-JF Please can you test it again, the new version is up in the staging area. Also this issue is open as [539](https://github.com/FAC-GM/app/issues/539)

**Comment by Adam-JF** [comment]
@heron2014 Fixed - working great.
