### ISSUE TITLE
Searching with nested object on ES

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#53]
How to search on a [nested object](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html) with Elasticsearch
```json
skills: [{skill: theSkillName, level: 98}, {...}, ...]
```

**Comment by SimonLab** [comment]
I follow the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-query.html) and apply a specific [query DSL](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/lib/search.js#L35-L51)

**Comment by iteles** [comment]
Would this be a useful addition to https://github.com/dwyl/learn-elasticsearch?
