### ISSUE TITLE
CSV Upload Bug 2

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#530]
Some files do not register on the app as having names/emails and the lists appear to have no contents.

Note development managers has a blank space where there should be a number - both the 'Email' and 'Name' fields were named correctly on the csv upload file and yet apparently it has nothing in it.

![screen shot 2016-06-29 at 22 18 27](https://cloud.githubusercontent.com/assets/15364186/16469310/327c4142-3e48-11e6-961d-d4e032f574a2.png)

**Comment by SimonLab** [comment]
Can you send the Development Manager file for Anita to check. It might have been an connection to the database problem or maybe the file is too big.

**Comment by heron2014** [comment]
This issue is also related to [528](https://github.com/FAC-GM/app/issues/528). @Adam-JF can you please send me the list files: c# and Development Manager, thank you.

**Comment by heron2014** [comment]
@Adam-JF just seen the files. Thanks

**Comment by heron2014** [comment]
@Adam-JF I have deployed the new version csv-list into the staging area. Please test upload the small files (as we might need to delete the duplicates ) - try to name the same like last time : for example C# list and then try to access the list, the same with Development Managers. Let me know if all works as expected.

**Comment by Adam-JF** [comment]
@heron2014 Just re-tested this and I can click onto the file and there are the appropriate number of contacts in there, however there is a new issue. If there is someone on the app with the same name, both profiles are added to the list but the same email address is applied to both.

![screen shot 2016-06-30 at 10 44 52](https://cloud.githubusercontent.com/assets/15364186/16484179/d16dfa22-3eaf-11e6-9e78-e9ce31106cd7.png)

![screen shot 2016-06-30 at 10 46 10](https://cloud.githubusercontent.com/assets/15364186/16484197/de9ff6dc-3eaf-11e6-8449-fad0d55a40c3.png)

![screen shot 2016-06-30 at 10 46 40](https://cloud.githubusercontent.com/assets/15364186/16484215/f43d082c-3eaf-11e6-8986-714f3ba993e9.png)

**Comment by heron2014** [comment]
Thanks @Adam-JF . Looking into that.

**Comment by heron2014** [comment]
@Adam-JF I was testing on my locahost by copying some of the profiles into the csv file - the same name and the same email - and it worked as expected (I had them once) Although there is a scenario like maybe the above one where David Adam was already in the app - twice. Its a rare scenerio but it might happen that two people have the same email but different Li url . So when you uploaded the new list he appeared twice. 

We need couple of more test to see if this is true: If you can create a list with few profiles - the same name and the same email but make sure they are appearing once in the app before uploading the list. Let me know how it worked.

**Comment by heron2014** [comment]
@Adam-JF I have tested again and it worked ok. Please can you test it again, if this bug occurs every time or if it was an edge case.

**Comment by Adam-JF** [comment]
@heron2014 Tested, working great.
