### ISSUE TITLE
CSV Styling

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#532]
Keep csv upload feature similar in style to the rest of the app.

**Comment by iteles** [comment]
Would be good to add a screenshot here so that your Product Owner (I'm guessing Nick?) can see what you were aiming for 👍

**Comment by Adam-JF** [comment]
Original:

![screen shot 2016-06-30 at 19 28 38](https://cloud.githubusercontent.com/assets/15364186/16499544/e77097a0-3ef8-11e6-9060-ce6d28e8730d.png)

Proposed:
![screen shot 2016-06-30 at 19 28 49](https://cloud.githubusercontent.com/assets/15364186/16499554/f2650a2e-3ef8-11e6-9af0-a93d50b0bae7.png)

**Comment by heron2014** [comment]
@Adam-JF do I see more horizontal lines? haha

**Comment by Adam-JF** [comment]
@heron2014 Your eyes do not deceive you, those are indeed, more horizontal lines - I added them earlier today.

Feel like we should start a support group...

**Comment by heron2014** [comment]
Resolved by #533
