### ISSUE TITLE
Horizontal Line

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#535]
@heron2014 Would it be possible to add a horizontal line between each job wrapper on the dashboard view? (i'm not even joking, more horizontal lines)

I know how to add the html, but I can't find the correct file to put it in 😬

**Comment by heron2014** [comment]
@Adam-JF I didn't know that horizontal line will make me laugh haha 

Do you also want more horizontal lines on http://globalm-test.herokuapp.com/client-users/list ? :laughing:

**Comment by Adam-JF** [comment]
@heron2014 You literally read my mind!

Let's make a rule; when in doubt... add a horizontal line 🙌🏼

**Comment by heron2014** [comment]
Dashboard view:

![hr](https://cloud.githubusercontent.com/assets/8476884/16490778/02f3cdd8-3ed3-11e6-8984-6fa42775b455.png)

@Adam-JF is this ok?

**Comment by Adam-JF** [comment]
@heron2014 In this instance it would probably be best to have a different style for the line.

Can we make this ones class name 'horizontal-profile2' for now so that I can edit it?

Likely i'll be wanting it the full width of the page and without the transparent effect.

**Comment by heron2014** [comment]
@Adam-JF ok I will call it horizontal-dash and you can edit as you like :+1:

**Comment by Adam-JF** [comment]
@heron2014 Perfect, thank you!

**Comment by heron2014** [comment]
@Adam-JF I just pushed these changes, I added rule in enhanced.css for horizontal-dash - ready to be edit.

**Comment by Adam-JF** [comment]
@heron2014 Working beautifully, thanks again.
