### ISSUE TITLE
App is Down

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#556]
Both main and test site of the app are down.

![screen shot 2016-07-19 at 15 00 53](https://cloud.githubusercontent.com/assets/15364186/16952567/a5bd9d58-4dc1-11e6-9912-1cf68860c91c.png)

**Comment by iteles** [comment]
Up for me @Adam-JF! Could you please check again?

**Comment by Adam-JF** [comment]
@iteles Weird... but brilliant, yes it's back up for us!

**Comment by iteles** [comment]
Heroku having a senior moment ;)

**Comment by Adam-JF** [comment]
@iteles I thought the same! Tried to get into Heroku whilst it was down and had an error message for that as well - bad Heroku, that's not how we behave.
