### ISSUE TITLE
csv Upload Issue

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#559]
Getting this error message when uploading a csv file.

![screen shot 2016-07-20 at 12 01 42](https://cloud.githubusercontent.com/assets/15364186/16984429/d08dc426-4e71-11e6-9557-e0c313482f68.png)

It is definitely a .csv file and both Name and Email columns are defined.

![screen shot 2016-07-20 at 12 02 37](https://cloud.githubusercontent.com/assets/15364186/16984449/ef3f1816-4e71-11e6-8374-b7a0f21466da.png)

![screen shot 2016-07-20 at 12 02 42](https://cloud.githubusercontent.com/assets/15364186/16984455/f2956d62-4e71-11e6-8cc3-fa7de48d360a.png)

**Comment by iteles** [comment]
Hey @Adam-JF Could you please email Anita and myself the file so we can replicate the problem?

**Comment by heron2014** [comment]
@Adam-JF before uploading any list please make sure of the following: 
- there are  no empty rows 
- there are no empty email or name entry
- there are no gaps between rows

In other words every single row with email and name has to be filled. Also please make sure that you have a correct data : for example I have noticed in your doc: 

![desc](https://cloud.githubusercontent.com/assets/8476884/16985537/0c29348c-4e79-11e6-9839-2cfe76a23ada.png)

When I cleaned all the above I was able to submit the list. Please test this on **staging area** as there is one PR pending to master.

![frijof](https://cloud.githubusercontent.com/assets/8476884/16985536/0a666764-4e79-11e6-8d89-bcbe91965783.png)

Let me know how it went. Thanks

**Comment by iteles** [comment]
Hi @Adam-JF, can you please confirm this? As @heron2014, from what we can see this was an issue with the file so the basic validation is operating as expected.

**Comment by Adam-JF** [comment]
All sorted - thank you for checking this!
