### ISSUE TITLE
Request limit nested search

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#56]
![threadpool](https://cloud.githubusercontent.com/assets/6057298/11059928/c2cd448c-8794-11e5-92c1-7c5a7270d4d2.png)

**Comment by SimonLab** [comment]
http://stackoverflow.com/questions/27793530/esrejectedexecutionexception-in-elasticsearch-for-parallel-search

**Comment by SimonLab** [comment]
Resolved with the Pull request 50 and by using a correct [query DSL](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/lib/search.js#L35-L51)

**Comment by iteles** [comment]
Worth adding to https://github.com/dwyl/learn-elasticsearch?
