### ISSUE TITLE
Big Favour

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#561]
Would it be possible for one of you to do a very brief review of a coding challenge we had submitted for our internal role?

Functionality wise everything appears to be working well, but a technical 'Ok' would be really reassuring.

Would be much appreciated.

"I’ve done the sample test. You can find it here: https://global-m-test.herokuapp.com/
The source code is here: https://github.com/EgidioCaprino/global-m-test

The front-end is composed by an AngularJS application while the backend is a NodeJS application based on Redis. All run in Heroku.
Please note that once you applied for the role, the ID of your application is stored in a localStorage entry so you can’t apply again."

**Comment by nelsonic** [comment]
@Adam-JF Sorry, only got notification now. sure, code looks ok. would expect to see a test tho... was a test/docs specified as a requirement of the challenge? 😉

**Comment by iteles** [comment]
Does this mean you found a dev @Adam-JF? 😱 🎉
