### ISSUE TITLE
Heroku Billing

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#563]
The app was displaying the below message...

![screen shot 2016-08-11 at 23 12 11](https://cloud.githubusercontent.com/assets/15364186/17606748/171f8448-6019-11e6-8efa-b0589e63410f.png)

Having logged into Heroku there appears to be an outstanding bill for the month of June (and presumably July)

![screen shot 2016-08-11 at 23 11 51](https://cloud.githubusercontent.com/assets/15364186/17606768/2d8398dc-6019-11e6-8798-a13e5f800d5f.png)

Just to confirm with you guys, if we pay this bill then the app will come back online and hosting will be restored?

**Comment by nelsonic** [comment]
@Adam-JF can you please confirm which URL you are attempting to access? (_thanks_)
( and yes, usually when payment is made to a service provider (Heroku), service resumes )

**Comment by nelsonic** [comment]
@Adam-JF please let us know if you still require our assistance with this. (_thanks!_)

**Comment by Adam-JF** [comment]
@nelsonic All resolved, thank you.
