### ISSUE TITLE
App is Down

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/app#565]
![screen shot 2016-09-09 at 14 47 05](https://cloud.githubusercontent.com/assets/15364186/18389129/4d3fa186-769c-11e6-9943-6a986229d725.png)

**Comment by nelsonic** [comment]
Hi @Adam-JF, 
Sadly, the outage was beyond our control see: https://status.heroku.com/incidents/941
It was resolved quite quickly but that's no consolation to you when you need to _use_ the app. 😞 
Hope you have a good weekend.
