### ISSUE TITLE
Log in to the app

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#59]
As a user I want to get a ***personal experience*** when *using* the app.
To enable this I will need to be individually identifiable when *using* the app.

Having an ***Authentication*** process will ensure that ***only authorised people*** can access the app
and ***prevent unauthorised access*** to the app and its content.

***How?***

The users *already* ***all*** use Google Mail for their email, therefore we propose they use their Google Account to authenticate with the app.

**Comment by SimonLab** [comment]
Our first step is to redirect a non logged-in user to the login page if he tries to access a 'private' page. My first idea was to user a method similar to redirectTo of the [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie) plugin. Can we use a similar function?

**Comment by nelsonic** [comment]
this one: http://hapijs.com/api#replyredirecturi ?

**Comment by SimonLab** [comment]
I wasn't exactly thinking of this one but if we can manage to catch the error of not being authenticated before sending the following reply: 
![notauth](https://cloud.githubusercontent.com/assets/6057298/11245922/435f88a2-8e0d-11e5-8f66-3b75536ab150.png)

then yes we can use this function reply.redirect(uri)

**Comment by heron2014** [comment]
```
auth: {
        mode: 'try',
        strategy: 'jwt'
      },
 handler: function (request, reply) {
          if (!request.auth.isAuthenticated) {
            return reply.redirect('/');
          }
          return reply('This is a private page');
        }
```
With a try mode you can execute the handler and check if you are authenticated or not.  

Have a look at [hapi athentication mode docs](http://hapijs.com/tutorials/auth)

**Comment by SimonLab** [comment]
Thanks @heron2014 :+1: , I think it's what we need!

**Comment by SimonLab** [comment]
Should our [validate authentication function](https://github.com/FAC-GM/app/blob/authentication/lib/validate.js) check the format of the emails?

**Comment by nelsonic** [comment]
@SimonLab the email address of the person *logging in*...?

**Comment by SimonLab** [comment]
Yes, it can be used to create some categories.

**Comment by heron2014** [comment]
@SimonLab By validation format email did you mean to be able recognise people from the company and let them login versus any other people?

**Comment by SimonLab** [comment]
I was thinking of defining permission depending on the user email, but now I think this functionality shouldn't be linked to the validate function

**Comment by iteles** [comment]
@heron2014 Could you please check the time label on this and change to actual time taken (if different to the original estimate) and confirm this issue can be closed with the merging of PR #88?

**Comment by heron2014** [comment]
It took us a double time to implement this feature because we spend most of the time understanding the process of authentication. We also made a real world example using hapi-auth-google-plugin [hapi-auth-google-example](https://github.com/SimonLab/hapi-auth-google-example).

**Comment by iteles** [comment]
@heron2014 The time label for this task needs to be the time taken for this task and not the overall task (which we now know took 4 days). We estimated it would take 3 hours, so we need to know how good that estimate was and learn from it.
