### ISSUE TITLE
Monitor "favourite/star" user profile

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#60]
As a user I want to be able to "***favourite***" **a candidate** so I can find them quickly later.

**Requires** ***Authentication*** [ see issue 59](https://github.com/FAC-GM/app/issues/59)

**Comment by nelsonic** [comment]
We need to think about how this data will be stored by considering how the feature will be *used*.
Just being able to "*Favourite*" something is simple enough, but what will we *do* with that data?
Are we going to need a "*My Favourites*" Page where all the person's favourite candidates can be viewed? if so, this will dictate how the data is stored.

**Comment by heron2014** [comment]
@nelsonic good point.

**Comment by SimonLab** [comment]
I think each profile in the database should have a property "favorite" with an array of ids google account as value: 
```json
profile1: {
  favorite: [1223, 5435543, 65445353],
}
```
It's also true that we need a specif page where a user can access easily her favorite profiles.

**Comment by heron2014** [comment]
This is a proposition of UI for this feature for Sprint 3:

![favourite](https://cloud.githubusercontent.com/assets/8476884/11368237/7faa2e14-92b0-11e5-9a5c-daefc059dd9b.png)

What do you think? @iteles @nelsonic @SimonLab

**Comment by nelsonic** [comment]
@heron2014 *wireframe* looks good. :+1:

**Comment by iteles** [comment]
@heron2014 Are you creating the 'My Favourites' view as part of Sprint 3 as well or is it just in the wireframe for reference?

Looking good for this sprint :+1: We'll tweak the UI as we start to get user feedback.

**Comment by SimonLab** [comment]
Current status of the features:
- We are displaying a basic star on [candidate partial view](https://github.com/FAC-GM/app/blob/457f2518d2e5d4809eaba0bc9db24f61f0f74375/views/partials/candidate.html#L6-L8) and the [candidate view](https://github.com/FAC-GM/app/blob/457f2518d2e5d4809eaba0bc9db24f61f0f74375/views/candidateView.html#L19-L23)

-We have created a new endpoint: [Favourite](https://github.com/FAC-GM/app/blob/favorite-profiles/lib/favourite.js) to handle the status of favorite for a profile

- We generate a post [request from the front-end](https://github.com/FAC-GM/app/blob/457f2518d2e5d4809eaba0bc9db24f61f0f74375/assets/js/main.js#L30-L45) to the favourite endpoint

The last two points are in progress!

**Comment by heron2014** [comment]
We have completed part which is storing our favourites profiles in DB  with user id and we are displaying stars accordingly : 
- view when we already clicked on star to save the profile: 
![star](https://cloud.githubusercontent.com/assets/8476884/11402048/c9a3a60c-938d-11e5-8287-dd8503a65836.png)
- view when profile hasn't yet saved as favourite
![grey](https://cloud.githubusercontent.com/assets/8476884/11402119/1512949a-938e-11e5-8fdc-8384413d1bff.png)

Next step is to place the link to **my favourite page** to display list of favourite profiles

**Comment by iteles** [comment]
@SimonLab @heron2014 Before we merge in PR #101, I've been thinking about the interface.

For now, I would suggest that we remove the 'My Favourites' link at the top and replace it with just a :star:  icon. This will:
+ Improve the mobile interface (the navigation bar looks very crowded with the 'My favourites' wording there)
+ Ensure that we're not adding unnecessary details to the UI that will be difficult to remove once our users get used to having it there
  + As it's much smaller, the star is a good starting point - if we find that it doesn't work once we've tested it with our users, we can roll back to a link with words :+1:

**Comment by SimonLab** [comment]
This functionality is done with the [PR 101](https://github.com/FAC-GM/app/pull/101)
