### ISSUE TITLE
Delete unused file and commented code

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#61]
To avoid code pollution and confusion on the main goal of a file we need to delete the files that are not used anymore and the commented code:

* [L7 on main.js](https://github.com/FAC-GM/app/blob/master/assets/js/main.js#L7): We don't use this filter functionality.
* [L6-L13 on search_bar](https://github.com/FAC-GM/app/blob/master/views/partials/search_bar.html#L6-L13): We don't need the html for the filter functionality
* [L1 on candidateView](https://github.com/FAC-GM/app/blob/master/lib/candidateView.js#L1): The fixture is not use anymore as we have now a database
* [L54-L76 on search.js](https://github.com/FAC-GM/app/blob/master/lib/search.js#L54-L76): This is a body request for elasticsearch which is mal-formed and can use too much memory of elasticsearch. This request has been replase by a much simpler one
* The [tmp folder](https://github.com/FAC-GM/app/tree/master/tmp) was used has fixtures, we are now using the elasticsearch database
* The [tag helper](https://github.com/FAC-GM/app/blob/master/views/helpers/tagsHelper.js) is not used as we don't have any tags to display
* [tags on candidate view](https://github.com/FAC-GM/app/blob/master/views/partials/candidate.html#L8-L10): we don't use tags
* [footer tag](https://github.com/FAC-GM/app/blob/master/views/partials/footer_mobile.html): we don't use the footer tags UI
* [footer mobile](https://github.com/FAC-GM/app/blob/master/views/partials/footer_mobile_candidate_view.html#L4-L6): delete commented tags
* [Header mobile](https://github.com/FAC-GM/app/blob/master/views/partials/header_mobile.html) has been replaced by search_bar
* [pagination](https://github.com/FAC-GM/app/blob/master/views/partials/pagination.html#L5-L7): The links for the pagination are done on the server side
* The [pagination search](https://github.com/FAC-GM/app/blob/master/views/partials/pagination_search.html) is not used
* The [search view](https://github.com/FAC-GM/app/blob/master/views/search.html) is not used. We reuse the home view to display the results of a search
* In the home view the [reference to the tags view](https://github.com/FAC-GM/app/blob/master/views/home.html#L3) is not used

**Comment by SimonLab** [comment]
The last item of the modification list: "In the home view the reference to the tags view is not used" influence the space between the result list and the search bar. Need to increase the space has there will not be any more [div and css](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/views/partials/tags_icons_desktop.html#L1)

Also we don't need anymore the file: [tags_icons_deskop](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/views/partials/tags_icons_desktop.html)
Do we need the css reference to the class [box-wrapper](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/views/partials/tags_icons_desktop.html#L1)

**Comment by iteles** [comment]
@SimonLab Sounds like fixing this issue has created a big which is worth opening a separate issue about? :blush:

**Comment by SimonLab** [comment]
@iteles 'a big ' issue?
I think we need a new issue for css cleaning.
Otherwise the 'backend code cleaning' is almost done.

**Comment by SimonLab** [comment]
Some last cleaning:
* Delete commented code in [candidateView.html](https://github.com/FAC-GM/app/blob/8b7315a742d21f50f950845db541b83b797df186/views/candidateView.html#L66-L71)
* Delete commented code in [home.html](https://github.com/FAC-GM/app/blob/8b7315a742d21f50f950845db541b83b797df186/views/home.html#L8)
* Delete the partial [footer_mobile](https://github.com/FAC-GM/app/blob/8b7315a742d21f50f950845db541b83b797df186/views/partials/footer_mobile.html)
* Delete commented code in the partial [candidate.html](https://github.com/FAC-GM/app/blob/8b7315a742d21f50f950845db541b83b797df186/views/partials/candidate.html#L8-L10)
* Delete commented code in the partial [search_bar](https://github.com/FAC-GM/app/blob/8b7315a742d21f50f950845db541b83b797df186/views/partials/search_bar.html#L3)
* Delete the commented css import line in [default.html](https://github.com/FAC-GM/app/blob/8b7315a742d21f50f950845db541b83b797df186/views/layout/default.html#L9)

**Comment by iteles** [comment]
A 'bug'! Sorry about the typo!

**Comment by SimonLab** [comment]
The [PR7](https://github.com/FAC-GM/app/pull/75) is ready for a code review if someone is up for it!
