### ISSUE TITLE
Activity page/view/tab

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#65]
As a user I want to go to a page/tab where I can see all other user's activities, this way I can monitor it under 1 click and not duplicate possibly the same action 

**Pre require** [issue 59](https://github.com/FAC-GM/app/issues/59)

**Comment by iteles** [comment]
@heron2014 As we discussed, we need to make your feature idea a bit clearer in your user story - what you're suggesting is a constant stream of every activity undertaken by every user within the app. 

If the github news feed inspired your idea it would also be worth adding a comment below stating that and including a screenshot :+1:

**Comment by heron2014** [comment]
We have implemented search query activity page #388.
