### ISSUE TITLE
Indicator/icon (already contacted) on user profile 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#66]
As a user I want to be able to see that specific candidate has been already been contacted by someone in the team, this way I can ask that specific person for feedback on the candidate.

**Requires** ***Authentication*** [issue 59](https://github.com/FAC-GM/app/issues/59)

**Comment by nelsonic** [comment]
@heron2014 I updated the story description to use the word "*candidate*" to make it clearer. hope you don't mind...

**Comment by heron2014** [comment]
:+1:

**Comment by Adam-JF** [comment]
Will be a nice thing to have once email functionality has been incorporated in the app. Till then it remains a low priority issue.

**Comment by heron2014** [comment]
Resolved by #272
