### ISSUE TITLE
Visual indicator of who on the team is connected to specific candidates

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#67]
As a user of the app, I want to be able to see **who on my team is connected to a specific candidate**, so I can ask that person for contact details or feedback.  I want to be able to see this _at a glance_ in the search results and also in the full profile page.

<img width="609" alt="gm-ui-who-am-i-connected-to" src="https://cloud.githubusercontent.com/assets/4185328/11181925/8340c22a-8c5e-11e5-971a-e49a05ba4b99.png">

**Comment by iteles** [comment]
@heron2014 Is this user story related to just the full profile page, the search results or both?

**Comment by heron2014** [comment]
@iteles I would place that feature in both. However on search results that could be minimized version.

**Comment by iteles** [comment]
@heron2014 It's very much worth adding in a screenshot of the original wireframe (highlighting the section you're talking about) that we put together when we were coming up with ideas so that this concept is easier to understand.   
I would definitely add a note that it's a rough idea and we still need to put more thought into the placement of the feature in the UI :+1:

**Comment by heron2014** [comment]
This is our first wireframe for this feature:

![contacted](https://cloud.githubusercontent.com/assets/8476884/11143131/c88e8054-89ea-11e5-8977-df6932385c35.png)

**Comment by SimonLab** [comment]
We are updating the elasticsearch database with the new information. We are not using yet the "update" api of elasticsearch but we are updating manually the values, see: [api lib L25-29](https://github.com/FAC-GM/app/blob/b07452f70cc6baea34950a7bea82dcb2c73d1ea2/lib/api.js#L25-L29)

**Comment by heron2014** [comment]
Current UI for this feature: 
![initials](https://cloud.githubusercontent.com/assets/8476884/11369712/4d49ad2a-92b8-11e5-869a-be074a421821.png)

**Comment by nelsonic** [comment]
Looks good for this iteration. lets see with the people *using* the app say when we deliver the feature.

**Comment by iteles** [comment]
:+1: Merged in PR #94

**Comment by iteles** [comment]
@SimonLab Could you please change the time label to denote how long this took?

**Comment by heron2014** [comment]
Time: 1d (exactly as we have estimated).
