### ISSUE TITLE
Email indicator

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#69]
As a person looking through a list of people **in the app search results** I want to **see _at a glance_ if a person has an email address listed** so I can make more informed decisions about whether to consider those people without having to click into their full profile.
<hr>
I estimate this task to be done in **1h**

<img width="609" alt="gm-ui-email-indicator" src="https://cloud.githubusercontent.com/assets/4185328/11181779/19343548-8c5d-11e5-82a1-6090861ef42a.png">

**Comment by nelsonic** [comment]
Hi @SimonLab please include a picture of where the Email icon will appear in the search result ("row") so its clear to others viewing this issue.

https://docs.google.com/presentation/d/1eDu2nlwB7s1NzQX8DLUaEhNobzf20uDur-p23_Tdv84/edit#slide=id.ge84f5fddd_3_45

**Comment by iteles** [comment]
@nelsonic 👍🏻 We need to do this for a number of the UI issues for sure.

**Comment by iteles** [comment]
Clearing sprint 3 milestone as this was not in our final agreed scope.

**Comment by heron2014** [comment]
There are 2 options for this feature (1 or 2): 

![email_indicator](https://cloud.githubusercontent.com/assets/8476884/11472352/cab5249c-9763-11e5-810a-efa9df5d1433.png)

I would propose to build option number 1 in case of  long candidate name and to separate star and @ symbol feature as they have two different functionality.

**Comment by SimonLab** [comment]
resolved with [PR](https://github.com/FAC-GM/app/pull/120)

**Comment by iteles** [comment]
This was _not_ originally in sprint 3 scope but was picked up as an additional story at the end of the sprint.
