### ISSUE TITLE
See people who are not directly linked to me or my colleagues

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#70]
As a user of this app, I want to be able to see people who are not _directly_ linked to me or my colleagues (as well as those that are directly linked to us) so that I am able to see information on even more people than I already do.

<hr/>

**Time estimate:** 1 day for the whole team

**Comment by SimonLab** [comment]
This feature is currently in the state of code review. We have manage to get the information from people who are not directly linked to me.

**Comment by Adam-JF** [comment]
We need it to be able to see the relationship we have with any given individual and then be able to expand the search beyond our internal network.

**Comment by iteles** [comment]
Everyone can now see details for _any candidate_, whether they are linked to them in some way or not.
