### ISSUE TITLE
What is the elasticsearch database strucuture?

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#73]
# What
Documentation of the database structure with an example of an elasticsearch document.

# Why
The database structure will be continuously improved with the development of new features and with the corrections of bugs. We want to keep track of these changes! This documentation allows us (and future developers) to **quickly** understand the current structure of the database.

# How
The file DATA.md describes the database structure and includes an example.

**Comment by iteles** [comment]
**Note:** Can we please make sure that the DATA.md file is linked in the README so it's easy for future developers to know where to find this information as well? :blush:

**Comment by SimonLab** [comment]
The elasticsearch database is now on the Readme see [PR](https://github.com/FAC-GM/app/pull/115)
