### ISSUE TITLE
Cleaning the css code

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#76]
The css need some cleaning: there are some commented code and some files seem not to be used:
* Is the [lineicons folder](https://github.com/FAC-GM/app/tree/master/assets/css/lineicons) used?
* There are some [commented css](https://github.com/FAC-GM/app/blob/b234425115474f9401ddb8e58f26a9ef909e35c9/assets/css/mobile-first.css#L97-L134), do we still need that?

**Comment by iteles** [comment]
@heron2014 You've assigned yourself to this, does that mean you're working on this now?

**Comment by heron2014** [comment]
@iteles not yet, I will work on this one at the end of today. I will add badge in progress.

**Comment by heron2014** [comment]
Time: 1h

**Comment by heron2014** [comment]
thanks @SimonLab
