### ISSUE TITLE
Escape values with Handlebars

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#77]
We need to be sure that every values return with Handlebars are escaped:
* [pagination L3](https://github.com/FAC-GM/app/blob/e16e4f6cd9d81e513eb5b07595120608b0b5122d/views/partials/pagination.html#L3)
* [candidateView.html](https://github.com/FAC-GM/app/blob/master/views/candidateView.html)
* [layout.html](https://github.com/FAC-GM/app/blob/master/views/layout/default.html#L16)

see also the [handlbars documentation](http://handlebarsjs.com/#html-escaping)

**Comment by iteles** [comment]
Linked to comment https://github.com/FAC-GM/app/pull/75#issuecomment-157375018

**Comment by SimonLab** [comment]
Starting research and example, see: https://github.com/SimonLab/handlebar-xss

**Comment by SimonLab** [comment]
The code of the [basic example](https://github.com/SimonLab/handlebar-xss) is done. The next step is to start to implement the example to the app

**Comment by SimonLab** [comment]
values on the pagination helper are now escaped.
Working on the skill helper values

**Comment by SimonLab** [comment]
skill and language done. I need to keep only one {{{ }}} in [default layout](https://github.com/FAC-GM/app/blob/master/views/layout/default.html#L15) otherwise the partials won't display properly.

**Comment by SimonLab** [comment]
resolved with [PR](https://github.com/FAC-GM/app/pull/119)
