### ISSUE TITLE
Undefined location in experiences

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#79]
As a user I don't want to have an indicator (undefined) if the location is not defined in a candidate's 'experience' section as I don't want my candidate page to have information that I'm not going to use.
![nolocation](https://cloud.githubusercontent.com/assets/6057298/11267134/7531c8a6-8ea1-11e5-8326-768a89438bb5.png)

**Comment by iteles** [comment]
Is it part of the agreed scope for sprint 3?

**Comment by SimonLab** [comment]
No, it something  we can  add at the end of the sprint if we have time.

**Comment by iteles** [comment]
:+1: :blush:

**Comment by Adam-JF** [comment]
We would like to have a search functionality that will allow us to search by location.

**Comment by iteles** [comment]
@Adam-JF :+1: I think that should be a separate user story. 
This one is currently concerned with the fact that some people don't have a defined location and therefore it's showing up as 'undefined' rather than just a blank!

**Comment by heron2014** [comment]
This issue has been resolved in Sprint 3/4
