### ISSUE TITLE
Applying tests for authentication

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#80]
Create and improve tests for authentication feature 
Relates to [issue 59](https://github.com/FAC-GM/app/issues/59)

**Comment by heron2014** [comment]
Time: 2h

**Comment by iteles** [comment]
@heron2014 Does your [comment above](https://github.com/FAC-GM/app/issues/80#issuecomment-158047975) mean this task is complete?

**Comment by heron2014** [comment]
@iteles we haven't close this task because we are applying login page and design into this branch authentication. We have related issue [issue 81](https://github.com/FAC-GM/app/issues/81) which is under umbrella of authentication branch.

**Comment by iteles** [comment]
@heron2014  Could you please check the time label on this and change to actual time taken (if different to the original estimate) and confirm this issue can be closed with the merging of PR #88?

**Comment by heron2014** [comment]
This issue is very much tied with full authentication process [ussue59](https://github.com/FAC-GM/app/issues/59)

**Comment by iteles** [comment]
@heron2014 The time label for this task needs to be the time taken for _this task_ and not the overall task (which we now know took 4 days). We estimated it would take 3 hours, so we need to know how good that estimate was and learn from it.
