### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#81]
As a user I want to be able to access a login page where as I want to be able to identify myself and access my data
Sub issue of [issue 59](https://github.com/FAC-GM/app/issues/59)

**Comment by heron2014** [comment]
First version of login page:

![prop](https://cloud.githubusercontent.com/assets/8476884/11273469/52296df8-8ecb-11e5-9aaa-7bf19f5732e4.png)

Any thoughts @iteles , @SimonLab , @nelsonic ?

**Comment by iteles** [comment]
:+1: This is all we need for an MVP @heron2014. Let's spend time on styling at the end of the sprint if we have it. We'll add 'beautifying' as a task for sprint 4 if it's important to the client.

**Comment by heron2014** [comment]
Ok, thanks @iteles

**Comment by heron2014** [comment]
Time: 1h

**Comment by heron2014** [comment]
This issue is resolved with this [PR](https://github.com/FAC-GM/app/pull/83)

**Comment by nelsonic** [comment]
@heron2014 the button is the *standard* one prescribed by google.
and the idea is they will only need to auth *once* per device so not something they will look at regularly...
