### ISSUE TITLE
Create google app

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#82]
As a user I want to use a specific Google app as I want to be able to authenticate with it

**Comment by iteles** [comment]
@SimonLab Could you please check the time label on this and change to actual time taken (if different to the original estimate) and confirm this issue can be closed with the merging of PR #88?

**Comment by SimonLab** [comment]
This task has been completed (thanks for the [nice guide](https://github.com/dwyl/hapi-auth-google/blob/master/GOOGLE-APP-STEP-BY-STEP-GUIDE.md) @nelsonic). The google App has been created with the [PR 88](https://github.com/FAC-GM/app/pull/88)
