### ISSUE TITLE
Redirection after authentication

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#85]
As a user I want to be redirected to the home page after authentication as I want to start to use the app as soon as I have logged in.

**Comment by iteles** [comment]
@SimonLab Could you please check the time label on this and change to actual time taken (if different to the original estimate) and confirm this issue can be closed with the merging of PR #88?

**Comment by SimonLab** [comment]
This functionality **took us 15 mn**. The [PR 88](https://github.com/FAC-GM/app/pull/88) resolved this issue!
