### ISSUE TITLE
Define topics that need to be covered in Product Owner training

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#89]
As a [Product Owner](https://www.mountaingoatsoftware.com/agile/scrum/product-owner) I want to understand my role more clearly so that I can ensure the team is as effective as possible.

**Comment by iteles** [comment]
To include documentation outline.

**Comment by iteles** [comment]
Additional things to ask/communicate:
+ Team time off over the holiday season
+ Letter of engagement sprint 3

**Comment by iteles** [comment]
@nelsonic 
<img width="400" alt="screen shot 2015-11-23 at 15 32 23" src="https://cloud.githubusercontent.com/assets/4185328/11340789/84a22f70-91f7-11e5-8bc8-c0c7b53b3c4a.png">

Not very catchy?

**Comment by iteles** [comment]
@nelsonic No good? :wink:

**Comment by nelsonic** [comment]
`learn-product-ownership`

**Comment by iteles** [comment]
Why break a good pattern indeed.

**Comment by nelsonic** [comment]
`product-owner-guide` then...

**Comment by iteles** [comment]
Product Owner training with @Adam-JF complete :+1:
