### ISSUE TITLE
Split main.js to specific html pages 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#97]
How can we split main.js to only load this code :[L30-L43](https://github.com/FAC-GM/app/blob/457f2518d2e5d4809eaba0bc9db24f61f0f74375/assets/js/main.js#L30-L43) to candidateView.html ? 

Error on home view
![error](https://cloud.githubusercontent.com/assets/8476884/11422024/882a4458-9430-11e5-8d15-07a71e3c93ad.png)

**Comment by nelsonic** [comment]
@heron2014 did you fix this?

**Comment by heron2014** [comment]
@nelsonic yes, we have created [candidate_view.js](https://github.com/FAC-GM/app/blob/master/assets/js/candidate_view.js) which was before in [main.js](https://github.com/FAC-GM/app/blob/master/assets/js/main.js) and  we only apply it to the candidateView.html [L93](https://github.com/FAC-GM/app/blob/b14f1b66a020539935c166ee43cd114b930419a8/views/candidateView.html#L93)

**Comment by nelsonic** [comment]
Ok. We can do this with DOM detection to avoid the error.
