### ISSUE TITLE
Post requests: js vs html form

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/app#98]
Is it better to avoid as much as possible javascript to create request from the front-end (and using form with html) or is it ok to use it if the UX is better?

**Comment by iteles** [comment]
@SimonLab Could you give us the example you're thinking of where this might have an impact on US (for context) please? :blush:

**Comment by SimonLab** [comment]
@iteles sorry yes. At the moment we are creating a [post request](https://github.com/FAC-GM/app/blob/457f2518d2e5d4809eaba0bc9db24f61f0f74375/assets/js/main.js#L30-L45) to update the status of a favourite profile.

**Comment by iteles** [comment]
As discussed in the standup this morning, we want to create an HTML form with an action and then use javascript to [`preventDefault()`](https://developer.mozilla.org/en/docs/Web/API/Event/preventDefault).

**Comment by SimonLab** [comment]
Like this even if the javascript is disabled on the browser the form action will do the job! Nice

**Comment by heron2014** [comment]
Resolved by this [PR](https://github.com/FAC-GM/app/pull/101)
